In [ ]:
print("===== GPU =====")
!nvidia-smi

print("===== CUDA =====")
!nvcc --version

print("===== GCC =====")
!gcc --version | head -n 1

print("===== CPU =====")
!nproc

print("===== CURRENT DIRECTORY =====")
!pwd

print("===== KAGGLE INPUT =====")
!ls -lah /kaggle/input

:

In [ ]:
print("===== DATASETS =====")
!find /kaggle/input/datasets -maxdepth 3 -type d | head -100

===== DATASETS =====
/kaggle/input/datasets
/kaggle/input/datasets/tanvibhardwaj24
/kaggle/input/datasets/tanvibhardwaj24/rodinia-data
/kaggle/input/datasets/tanvibhardwaj24/rodinia-data/rodinia_data

In [ ]:
print("===== DATASET FILE COUNT =====")
!find /kaggle/input/datasets -type f | wc -l

===== DATASET FILE COUNT =====
88

In [ ]:
print("===== RODINIA DATA ROOT =====")
!ls -lah /kaggle/input/datasets/tanvibhardwaj24/rodinia-data/rodinia_data

print("\n===== BFS DATA =====")
!ls -lah /kaggle/input/datasets/tanvibhardwaj24/rodinia-data/rodinia_data/bfs

print("\n===== SEARCH FOR graph1MW_6.txt =====")
!find /kaggle/input/datasets/tanvibhardwaj24/rodinia-data/rodinia_data -name "graph1MW_6.txt"

===== RODINIA DATA ROOT =====
total 0
drwxr-xr-x 19 nobody nogroup 0 Sep 25 09:01 .
drwxr-xr-x  3 nobody nogroup 0 Sep 25 09:01 ..
drwxr-xr-x  3 nobody nogroup 0 Sep 25 09:01 bfs
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 b+tree
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 cfd
drwxr-xr-x  3 nobody nogroup 0 Sep 25 09:01 dwt2d
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 gaussian
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 heartwall
drwxr-xr-x  3 nobody nogroup 0 Sep 25 09:01 hotspot
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 hotspot3D
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 huffman
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 hybridsort
drwxr-xr-x  3 nobody nogroup 0 Sep 25 09:01 kmeans
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 leukocyte
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 lud
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 mummergpu
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 myocyte
drwxr-xr-x  3 nobody nogroup 0 Sep 25 09:01 nn
drwxr-xr-x  2 nobody nogroup 0 Sep 25 09:01 srad

===== BFS DATA =====
total 66M
drwxr-xr-x  3 nobody nogroup    0 Sep 25 09:01 .
drwxr-xr-x 19 nobody nogroup    0 Sep 25 09:01 ..
-rw-r--r--  1 nobody nogroup  62M Sep 25 09:01 graph1MW_6.txt
-rw-r--r--  1 nobody nogroup 195K Sep 25 09:01 graph4096.txt
-rw-r--r--  1 nobody nogroup 3.7M Sep 25 09:01 graph65536.txt
drwxr-xr-x  2 nobody nogroup    0 Sep 25 09:01 inputGen

===== SEARCH FOR graph1MW_6.txt =====
/kaggle/input/datasets/tanvibhardwaj24/rodinia-data/rodinia_data/bfs/graph1MW_6.txt

In [ ]:
%cd /kaggle/working

!git clone https://github.com/socal-ucr/Rodinia.git

print("\n===== RODINIA DIRECTORY =====")
!ls -lah /kaggle/working/Rodinia

/kaggle/working
fatal: destination path 'Rodinia' already exists and is not an empty directory.

===== RODINIA DIRECTORY =====
total 64K
drwxr-xr-x  8 root root 4.0K Sep 25 09:03 .
drwxr-xr-x  4 root root 4.0K Sep 25 09:11 ..
drwxr-xr-x  2 root root 4.0K Sep 25 09:03 common
drwxr-xr-x 25 root root 4.0K Sep 25 09:03 cuda
lrwxrwxrwx  1 root root   64 Sep 25 09:03 data -> /kaggle/input/datasets/tanvibhardwaj24/rodinia-data/rodinia_data
-rwxr-xr-x  1 root root  125 Sep 25 09:03 get_data.sh
drwxr-xr-x  8 root root 4.0K Sep 25 09:03 .git
-rwxr-xr-x  1 root root 3.2K Sep 25 09:03 LICENSE
-rwxr-xr-x  1 root root 4.4K Sep 25 09:03 Makefile
drwxr-xr-x 23 root root 4.0K Sep 25 09:03 opencl
drwxr-xr-x 21 root root 4.0K Sep 25 09:03 openmp
drwxr-xr-x  3 root root 4.0K Sep 25 09:03 others
-rwxr-xr-x  1 root root 9.1K Sep 25 09:03 README

In [ ]:
%cd /kaggle/working/Rodinia

print("===== AVAILABLE RODINIA TAGS =====")
!git tag

print("\n===== CURRENT VERSION =====")
!git branch --show-current
!git describe --tags --always

/kaggle/working/Rodinia
===== AVAILABLE RODINIA TAGS =====
1.0
2.0
2.0.1
2.1
2.2
2.3
2.4
3.0
3.1

===== CURRENT VERSION =====
3.1

In [ ]:
%cd /kaggle/working/Rodinia

!git checkout 3.1

print("\n===== VERIFIED VERSION =====")
!git describe --tags --exact-match

/kaggle/working/Rodinia
M	cuda/bfs/bfs
M	cuda/bfs/bfs.cu
HEAD is now at 6aa74ca Rodinia 3.1

===== VERIFIED VERSION =====
3.1

In [ ]:
%cd /kaggle/working/Rodinia

# Create a link from Rodinia/data to the Kaggle-mounted dataset
!ln -s /kaggle/input/datasets/tanvibhardwaj24/rodinia-data/rodinia_data data

print("===== RODINIA DATA LINK =====")
!ls -ld data

print("\n===== BFS DATA THROUGH RODINIA =====")
!ls -lh data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia
ln: failed to create symbolic link 'data/rodinia_data': Read-only file system
===== RODINIA DATA LINK =====
lrwxrwxrwx 1 root root 64 Sep 25 09:03 data -> /kaggle/input/datasets/tanvibhardwaj24/rodinia-data/rodinia_data

===== BFS DATA THROUGH RODINIA =====
-rw-r--r-- 1 nobody nogroup 62M Sep 25 09:01 data/bfs/graph1MW_6.txt

# INSPECT BFS BEFORE COMPILING

In [ ]:
%cd /kaggle/working/Rodinia

print("===== OPENMP BFS =====")
!ls -lah openmp/bfs
print("\n===== OPENMP RUN SCRIPT =====")
!cat openmp/bfs/run

print("\n===== CUDA BFS =====")
!ls -lah cuda/bfs
print("\n===== CUDA RUN SCRIPT =====")
!cat cuda/bfs/run

/kaggle/working/Rodinia
===== OPENMP BFS =====
total 15M
drwxr-xr-x  2 root root 4.0K Sep 25 09:03 .
drwxr-xr-x 21 root root 4.0K Sep 25 09:03 ..
-rwxr-xr-x  1 root root  39K Sep 25 09:03 bfs
-rwxr-xr-x  1 root root 4.8K Sep 25 09:03 bfs.cpp
-rwxr-xr-x  1 root root  252 Sep 25 09:03 Makefile
-rw-r--r--  1 root root  15M Sep 25 09:10 result.txt
-rwxr-xr-x  1 root root   38 Sep 25 09:03 run
-rw-r--r--  1 root root   46 Sep 25 09:03 run_offload

===== OPENMP RUN SCRIPT =====
./bfs 4 ../../data/bfs/graph1MW_6.txt
===== CUDA BFS =====
total 17M
drwxr-xr-x  2 root root 4.0K Sep 25 09:09 .
drwxr-xr-x 25 root root 4.0K Sep 25 09:03 ..
-rwxr-xr-x  1 root root 989K Sep 25 09:09 bfs
-rwxr-xr-x  1 root root 7.0K Sep 25 09:07 bfs_before_transfer_timing.cu
-rwxr-xr-x  1 root root 7.0K Sep 25 09:08 bfs_before_transfer_timing_v2.cu
-rwxr-xr-x  1 root root 7.8K Sep 25 09:09 bfs.cu
-rwxr-xr-x  1 root root 989K Sep 25 09:07 bfs_kernel_timed
-rwxr-xr-x  1 root root 7.0K Sep 25 09:07 bfs_kernel_timed.cu
-rwxr-xr-x  1 root root 6.8K Sep 25 09:03 bfs_original.cu
-rwxr-xr-x  1 root root 1.3K Sep 25 09:03 kernel2.cu
-rwxr-xr-x  1 root root 1.5K Sep 25 09:03 kernel.cu
-rwxr-xr-x  1 root root  491 Sep 25 09:03 Makefile
-rwxr-xr-x  1 root root 2.0K Sep 25 09:03 Makefile_nvidia
-rwxr-xr-x  1 root root  174 Sep 25 09:03 README
-rw-r--r--  1 root root  15M Sep 25 09:11 result.txt
-rwxr-xr-x  1 root root   36 Sep 25 09:03 run

===== CUDA RUN SCRIPT =====
./bfs ../../data/bfs/graph1MW_6.txt

In [ ]:
%cd /kaggle/working/Rodinia/openmp/bfs

print("===== MAKEFILE =====")
!cat Makefile

print("\n===== COMPILING OPENMP BFS =====")
!make clean
!make

print("\n===== CHECKING EXECUTABLE =====")
!ls -lh bfs

/kaggle/working/Rodinia/openmp/bfs
===== MAKEFILE =====
# C compiler
CC = g++
ICC = icc
CC_FLAGS = -g -fopenmp -O2

all: bfs bfs_offload

bfs: bfs.cpp
	$(CC) $(CC_FLAGS) bfs.cpp -o bfs

bfs_offload: bfs.cpp
	$(ICC) $(CC_FLAGS) -DOMP_OFFLOAD bfs.cpp -o bfs_offload

clean:
	rm -f bfs bfs_offload result.txt

===== COMPILING OPENMP BFS =====
rm -f bfs bfs_offload result.txt
g++ -g -fopenmp -O2 bfs.cpp -o bfs
bfs.cpp: In function ‘void BFSGraph(int, char**)’:
bfs.cpp:65:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result]8;;]
   65 |         fscanf(fp,"%d",&no_of_nodes);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~
bfs.cpp:77:23: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result]8;;]
   77 |                 fscanf(fp,"%d %d",&start,&edgeno);
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
bfs.cpp:86:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result]8;;]
   86 |         fscanf(fp,"%d",&source);
      |         ~~~~~~^~~~~~~~~~~~~~~~~
bfs.cpp:93:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result]8;;]
   93 |         fscanf(fp,"%d",&edge_list_size);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
bfs.cpp:99:23: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result]8;;]
   99 |                 fscanf(fp,"%d",&id);
      |                 ~~~~~~^~~~~~~~~~~~~
bfs.cpp:100:23: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result]8;;]
  100 |                 fscanf(fp,"%d",&cost);
      |                 ~~~~~~^~~~~~~~~~~~~~~
icc -g -fopenmp -O2 -DOMP_OFFLOAD bfs.cpp -o bfs_offload
make: icc: No such file or directory
make: *** [Makefile:12: bfs_offload] Error 127

===== CHECKING EXECUTABLE =====
-rwxr-xr-x 1 root root 39K Sep 25 09:15 bfs

In [ ]:
%cd /kaggle/working/Rodinia/openmp/bfs

print("===== CPU BFS TEST RUN =====")
!./bfs 4 ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/openmp/bfs
===== CPU BFS TEST RUN =====
Reading File
Start traversing the tree
Compute time: 0.039252
Result stored in result.txt

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

print("===== GPU INFORMATION =====")
!nvidia-smi --query-gpu=name,memory.total --format=csv,noheader

print("\n===== CUDA BFS TEST RUN =====")
!./bfs ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/cuda/bfs
===== GPU INFORMATION =====
Tesla T4, 15360 MiB
Tesla T4, 15360 MiB

===== CUDA BFS TEST RUN =====
Reading File
Read File
Copied Everything to GPU memory
Start traversing the tree
GPU Kernel Time: 3.834496 ms
Kernel Executed 12 times
Initial Host to Device Time: 14.124096 ms
Final Device to Host Time: 0.774144 ms
Result stored in result.txt

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

print("===== TIMING / KERNEL CODE =====")
!grep -n -E "time|timer|Start traversing|Kernel Executed|cudaMemcpy|cudaMalloc|cudaThreadSynchronize" bfs.cu kernel.cu kernel2.cu

/kaggle/working/Rodinia/cuda/bfs
===== TIMING / KERNEL CODE =====
bfs.cu:144:	float h2d_time_ms = 0.0f;
bfs.cu:145:	float d2h_time_ms = 0.0f;
bfs.cu:149:	cudaMalloc( (void**) &d_graph_nodes, sizeof(Node)*no_of_nodes) ;
bfs.cu:151:	cudaMemcpy( d_graph_nodes, h_graph_nodes, sizeof(Node)*no_of_nodes, cudaMemcpyHostToDevice) ;
bfs.cu:155:	cudaMalloc( (void**) &d_graph_edges, sizeof(int)*edge_list_size) ;
bfs.cu:156:	cudaMemcpy( d_graph_edges, h_graph_edges, sizeof(int)*edge_list_size, cudaMemcpyHostToDevice) ;
bfs.cu:160:	cudaMalloc( (void**) &d_graph_mask, sizeof(bool)*no_of_nodes) ;
bfs.cu:161:	cudaMemcpy( d_graph_mask, h_graph_mask, sizeof(bool)*no_of_nodes, cudaMemcpyHostToDevice) ;
bfs.cu:164:	cudaMalloc( (void**) &d_updating_graph_mask, sizeof(bool)*no_of_nodes) ;
bfs.cu:165:	cudaMemcpy( d_updating_graph_mask, h_updating_graph_mask, sizeof(bool)*no_of_nodes, cudaMemcpyHostToDevice) ;
bfs.cu:169:	cudaMalloc( (void**) &d_graph_visited, sizeof(bool)*no_of_nodes) ;
bfs.cu:170:	cudaMemcpy( d_graph_visited, h_graph_visited, sizeof(bool)*no_of_nodes, cudaMemcpyHostToDevice) ;
bfs.cu:180:	cudaMalloc( (void**) &d_cost, sizeof(int)*no_of_nodes);
bfs.cu:181:	cudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;
bfs.cu:185:	cudaEventElapsedTime(&h2d_time_ms, h2d_start_event, h2d_stop_event);
bfs.cu:189:	cudaMalloc( (void**) &d_over, sizeof(bool));
bfs.cu:198:	printf("Start traversing the tree\n");
bfs.cu:210:		cudaMemcpy( d_over, &stop, sizeof(bool), cudaMemcpyHostToDevice) ;
bfs.cu:219:		cudaMemcpy( &stop, d_over, sizeof(bool), cudaMemcpyDeviceToHost) ;
bfs.cu:227:		float kernel_time_ms = 0.0f;
bfs.cu:228:		cudaEventElapsedTime(&kernel_time_ms, bfs_start_event, bfs_stop_event);
bfs.cu:230:		printf("GPU Kernel Time: %.6f ms\n", kernel_time_ms);
bfs.cu:236:	printf("Kernel Executed %d times\n",k);
bfs.cu:240:	cudaMemcpy( h_cost, d_cost, sizeof(int)*no_of_nodes, cudaMemcpyDeviceToHost) ;
bfs.cu:244:	cudaEventElapsedTime(&d2h_time_ms, d2h_start_event, d2h_stop_event);
bfs.cu:246:	printf("Initial Host to Device Time: %.6f ms\n", h2d_time_ms);
bfs.cu:247:	printf("Final Device to Host Time: %.6f ms\n", d2h_time_ms);

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

print("===== BFS GPU EXECUTION SECTION =====")
!sed -n '175,215p' bfs.cu

/kaggle/working/Rodinia/cuda/bfs
===== BFS GPU EXECUTION SECTION =====
		h_cost[i]=-1;
	h_cost[source]=0;

	// allocate device memory for result
	int* d_cost;
	cudaMalloc( (void**) &d_cost, sizeof(int)*no_of_nodes);
	cudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;

	cudaEventRecord(h2d_stop_event);
	cudaEventSynchronize(h2d_stop_event);
	cudaEventElapsedTime(&h2d_time_ms, h2d_start_event, h2d_stop_event);

	//make a bool to check if the execution is over
	bool *d_over;
	cudaMalloc( (void**) &d_over, sizeof(bool));

	printf("Copied Everything to GPU memory\n");

	// setup execution parameters
	dim3  grid( num_of_blocks, 1, 1);
	dim3  threads( num_of_threads_per_block, 1, 1);

	int k=0;
	printf("Start traversing the tree\n");
	bool stop;

		cudaEvent_t bfs_start_event, bfs_stop_event;
		cudaEventCreate(&bfs_start_event);
		cudaEventCreate(&bfs_stop_event);
	//Call the Kernel untill all the elements of Frontier are not false
		cudaEventRecord(bfs_start_event);
	do
	{
		//if no thread changes this value then the loop stops
		stop=false;
		cudaMemcpy( d_over, &stop, sizeof(bool), cudaMemcpyHostToDevice) ;
		Kernel<<< grid, threads, 0 >>>( d_graph_nodes, d_graph_edges, d_graph_mask, d_updating_graph_mask, d_graph_visited, d_cost, no_of_nodes);
		// check if kernel execution generated and error


		Kernel2<<< grid, threads, 0 >>>( d_graph_mask, d_updating_graph_mask, d_graph_visited, d_over, no_of_nodes);

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

print("===== CUDA EVENT REFERENCES =====")
!grep -n "cudaEvent" bfs.cu

/kaggle/working/Rodinia/cuda/bfs
===== CUDA EVENT REFERENCES =====
136:	cudaEvent_t h2d_start_event, h2d_stop_event;
137:	cudaEvent_t d2h_start_event, d2h_stop_event;
139:	cudaEventCreate(&h2d_start_event);
140:	cudaEventCreate(&h2d_stop_event);
141:	cudaEventCreate(&d2h_start_event);
142:	cudaEventCreate(&d2h_stop_event);
150:	cudaEventRecord(h2d_start_event);
183:	cudaEventRecord(h2d_stop_event);
184:	cudaEventSynchronize(h2d_stop_event);
185:	cudaEventElapsedTime(&h2d_time_ms, h2d_start_event, h2d_stop_event);
201:		cudaEvent_t bfs_start_event, bfs_stop_event;
202:		cudaEventCreate(&bfs_start_event);
203:		cudaEventCreate(&bfs_stop_event);
205:		cudaEventRecord(bfs_start_event);
224:		cudaEventRecord(bfs_stop_event);
225:		cudaEventSynchronize(bfs_stop_event);
228:		cudaEventElapsedTime(&kernel_time_ms, bfs_start_event, bfs_stop_event);
232:		cudaEventDestroy(bfs_start_event);
233:		cudaEventDestroy(bfs_stop_event);
239:	cudaEventRecord(d2h_start_event);
242:	cudaEventRecord(d2h_stop_event);
243:	cudaEventSynchronize(d2h_stop_event);
244:	cudaEventElapsedTime(&d2h_time_ms, d2h_start_event, d2h_stop_event);

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!cp bfs.cu bfs_original.cu

print("Backup created:")
!ls -lh bfs.cu bfs_original.cu

/kaggle/working/Rodinia/cuda/bfs
Backup created:
-rwxr-xr-x 1 root root 7.8K Sep 25 09:09 bfs.cu
-rwxr-xr-x 1 root root 7.8K Sep 25 09:15 bfs_original.cu

# ============================================================
# CFD SOURCE INSPECTION
# We are only reading the source code.
# Nothing is being changed.
# ============================================================

from pathlib import Path

SOURCE_FILE = Path("/kaggle/working/Rodinia/cuda/cfd/euler3d.cu")

# ------------------------------------------------------------
# 1. Check that the source file exists
# ------------------------------------------------------------

if not SOURCE_FILE.exists():
    print("ERROR: CFD source file was not found.")
else:

    print("=" * 80)
    print("CFD SOURCE FILE")
    print("=" * 80)
    print(SOURCE_FILE)

    # Read the source
    lines = SOURCE_FILE.read_text(errors="ignore").splitlines()

    print(f"\nTotal source-code lines: {len(lines)}")

    # --------------------------------------------------------
    # 2. Search for timing-related code
    # --------------------------------------------------------

    keywords_timing = [
        "seconds per iteration",
        "gettimeofday",
        "clock",
        "cudaEvent",
        "cudaEventRecord",
        "cudaEventElapsedTime",
        "time"
    ]

    print("\n" + "=" * 80)
    print("TIMING-RELATED LINES")
    print("=" * 80)

    for i, line in enumerate(lines, start=1):

        if any(keyword.lower() in line.lower()
               for keyword in keywords_timing):

            print(f"{i:5d}: {line}")

    # --------------------------------------------------------
    # 3. Search for CUDA memory transfers
    # --------------------------------------------------------

    keywords_transfer = [
        "cudaMemcpy",
        "cudaMemcpyHostToDevice",
        "cudaMemcpyDeviceToHost",
        "cudaMemcpyDeviceToDevice"
    ]

    print("\n" + "=" * 80)
    print("CUDA MEMORY-TRANSFER LINES")
    print("=" * 80)

    for i, line in enumerate(lines, start=1):

        if any(keyword.lower() in line.lower()
               for keyword in keywords_transfer):

            print(f"{i:5d}: {line}")

    # --------------------------------------------------------
    # 4. Search for the main computation loop
    # --------------------------------------------------------

    keywords_loop = [
        "for (",
        "while (",
        "iterations",
        "iteration"
    ]

    print("\n" + "=" * 80)
    print("LOOP / ITERATION-RELATED LINES")
    print("=" * 80)

    for i, line in enumerate(lines, start=1):

        if any(keyword.lower() in line.lower()
               for keyword in keywords_loop):

            print(f"{i:5d}: {line}")

    # --------------------------------------------------------
    # 5. Search for kernel launches
    # --------------------------------------------------------

    print("\n" + "=" * 80)
    print("CUDA KERNEL LAUNCHES")
    print("=" * 80)

    for i, line in enumerate(lines, start=1):

        if "<<<" in line and ">>>" in line:

            print(f"{i:5d}: {line}")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!nl -ba bfs.cu | sed -n '175,215p'

/kaggle/working/Rodinia/cuda/bfs
   175			h_cost[i]=-1;
   176		h_cost[source]=0;
   177
   178		// allocate device memory for result
   179		int* d_cost;
   180		cudaMalloc( (void**) &d_cost, sizeof(int)*no_of_nodes);
   181		cudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;
   182
   183		cudaEventRecord(h2d_stop_event);
   184		cudaEventSynchronize(h2d_stop_event);
   185		cudaEventElapsedTime(&h2d_time_ms, h2d_start_event, h2d_stop_event);
   186
   187		//make a bool to check if the execution is over
   188		bool *d_over;
   189		cudaMalloc( (void**) &d_over, sizeof(bool));
   190
   191		printf("Copied Everything to GPU memory\n");
   192
   193		// setup execution parameters
   194		dim3  grid( num_of_blocks, 1, 1);
   195		dim3  threads( num_of_threads_per_block, 1, 1);
   196
   197		int k=0;
   198		printf("Start traversing the tree\n");
   199		bool stop;
   200
   201			cudaEvent_t bfs_start_event, bfs_stop_event;
   202			cudaEventCreate(&bfs_start_event);
   203			cudaEventCreate(&bfs_stop_event);
   204		//Call the Kernel untill all the elements of Frontier are not false
   205			cudaEventRecord(bfs_start_event);
   206		do
   207		{
   208			//if no thread changes this value then the loop stops
   209			stop=false;
   210			cudaMemcpy( d_over, &stop, sizeof(bool), cudaMemcpyHostToDevice) ;
   211			Kernel<<< grid, threads, 0 >>>( d_graph_nodes, d_graph_edges, d_graph_mask, d_updating_graph_mask, d_graph_visited, d_cost, no_of_nodes);
   212			// check if kernel execution generated and error
   213
   214
   215			Kernel2<<< grid, threads, 0 >>>( d_graph_mask, d_updating_graph_mask, d_graph_visited, d_over, no_of_nodes);

%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

# 1. Add CUDA event declarations after bool stop;
old = "\tbool stop;"
new = """\tbool stop;

\tcudaEvent_t kernel_start, kernel_stop;
\tcudaEventCreate(&kernel_start);
\tcudaEventCreate(&kernel_stop);"""

if old not in text:
    raise RuntimeError("Could not find 'bool stop;'")

text = text.replace(old, new, 1)

# 2. Start GPU timing immediately before the BFS loop
old = """\t//Call the Kernel untill all the elements of Frontier are not false
\tdo"""

new = """\t//Call the Kernel untill all the elements of Frontier are not false
\tcudaEventRecord(kernel_start);

\tdo"""

if old not in text:
    raise RuntimeError("Could not find BFS loop start")

text = text.replace(old, new, 1)

# 3. Stop GPU timing after the BFS loop
old = """\twhile(stop);


\tprintf("Kernel Executed %d times\\\\n",k);"""

new = """\twhile(stop);

\tcudaEventRecord(kernel_stop);
\tcudaEventSynchronize(kernel_stop);

\tfloat kernel_time_ms = 0.0f;
\tcudaEventElapsedTime(&kernel_time_ms, kernel_start, kernel_stop);

\tprintf("Kernel Executed %d times\\\\n",k);
\tprintf("GPU kernel loop time: %.6f ms\\\\n", kernel_time_ms);

\tcudaEventDestroy(kernel_start);
\tcudaEventDestroy(kernel_stop);"""

if old not in text:
    raise RuntimeError("Could not find BFS loop end")

text = text.replace(old, new, 1)

path.write_text(text)

print("CUDA timing code added successfully.")

%cd /kaggle/working/Rodinia/cuda/bfs

!nl -ba bfs.cu | sed -n '178,225p'

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!cp bfs_original.cu bfs.cu

print("Original CUDA source restored.")

/kaggle/working/Rodinia/cuda/bfs
Original CUDA source restored.

In [ ]:
!nl -ba bfs.cu | sed -n '181,208p'

   181		cudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;
   182
   183		cudaEventRecord(h2d_stop_event);
   184		cudaEventSynchronize(h2d_stop_event);
   185		cudaEventElapsedTime(&h2d_time_ms, h2d_start_event, h2d_stop_event);
   186
   187		//make a bool to check if the execution is over
   188		bool *d_over;
   189		cudaMalloc( (void**) &d_over, sizeof(bool));
   190
   191		printf("Copied Everything to GPU memory\n");
   192
   193		// setup execution parameters
   194		dim3  grid( num_of_blocks, 1, 1);
   195		dim3  threads( num_of_threads_per_block, 1, 1);
   196
   197		int k=0;
   198		printf("Start traversing the tree\n");
   199		bool stop;
   200
   201			cudaEvent_t bfs_start_event, bfs_stop_event;
   202			cudaEventCreate(&bfs_start_event);
   203			cudaEventCreate(&bfs_stop_event);
   204		//Call the Kernel untill all the elements of Frontier are not false
   205			cudaEventRecord(bfs_start_event);
   206		do
   207		{
   208			//if no thread changes this value then the loop stops

%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

# Add CUDA event declarations before the BFS loop
old = """int k=0;
printf("Start traversing the tree\\n");
bool stop;"""

new = """int k=0;
printf("Start traversing the tree\\n");
bool stop;

cudaEvent_t start, stop_event;
cudaEventCreate(&start);
cudaEventCreate(&stop_event);"""

if old not in text:
    raise RuntimeError("Could not find the expected timing insertion point.")

text = text.replace(old, new, 1)

# Start timing immediately before the BFS kernel loop
old = """//Call the Kernel untill all the elements of Frontier are not false
do
{"""

new = """//Call the Kernel untill all the elements of Frontier are not false
cudaEventRecord(start);

do
{"""

if old not in text:
    raise RuntimeError("Could not find the BFS loop start.")

text = text.replace(old, new, 1)

# Stop timing after the loop
old = """}
while(stop);


printf("Kernel Executed %d times\\n",k);"""

new = """}
while(stop);

cudaEventRecord(stop_event);
cudaEventSynchronize(stop_event);

float kernel_time_ms = 0.0f;
cudaEventElapsedTime(&kernel_time_ms, start, stop_event);

printf("Kernel Executed %d times\\n",k);
printf("GPU Kernel Time: %.6f ms\\n", kernel_time_ms);

cudaEventDestroy(start);
cudaEventDestroy(stop_event);"""

if old not in text:
    raise RuntimeError("Could not find the BFS loop end.")

text = text.replace(old, new, 1)

path.write_text(text)

print("CUDA timing code inserted successfully.")

%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

# Add CUDA event declarations before the BFS loop
old = """int k=0;
printf("Start traversing the tree\\n");
bool stop;"""

new = """int k=0;
printf("Start traversing the tree\\n");
bool stop;

cudaEvent_t start, stop_event;
cudaEventCreate(&start);
cudaEventCreate(&stop_event);"""

if old not in text:
    raise RuntimeError("Could not find the expected timing insertion point.")

text = text.replace(old, new, 1)

# Start timing immediately before the BFS kernel loop
old = """//Call the Kernel untill all the elements of Frontier are not false
do
{"""

new = """//Call the Kernel untill all the elements of Frontier are not false
cudaEventRecord(start);

do
{"""

if old not in text:
    raise RuntimeError("Could not find the BFS loop start.")

text = text.replace(old, new, 1)

# Stop timing after the loop
old = """}
while(stop);


printf("Kernel Executed %d times\\n",k);"""

new = """}
while(stop);

cudaEventRecord(stop_event);
cudaEventSynchronize(stop_event);

float kernel_time_ms = 0.0f;
cudaEventElapsedTime(&kernel_time_ms, start, stop_event);

printf("Kernel Executed %d times\\n",k);
printf("GPU Kernel Time: %.6f ms\\n", kernel_time_ms);

cudaEventDestroy(start);
cudaEventDestroy(stop_event);"""

if old not in text:
    raise RuntimeError("Could not find the BFS loop end.")

text = text.replace(old, new, 1)

path.write_text(text)

print("CUDA timing code inserted successfully.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!nl -ba bfs.cu | sed -n '178,210p'

/kaggle/working/Rodinia/cuda/bfs
   178		// allocate device memory for result
   179		int* d_cost;
   180		cudaMalloc( (void**) &d_cost, sizeof(int)*no_of_nodes);
   181		cudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;
   182
   183		cudaEventRecord(h2d_stop_event);
   184		cudaEventSynchronize(h2d_stop_event);
   185		cudaEventElapsedTime(&h2d_time_ms, h2d_start_event, h2d_stop_event);
   186
   187		//make a bool to check if the execution is over
   188		bool *d_over;
   189		cudaMalloc( (void**) &d_over, sizeof(bool));
   190
   191		printf("Copied Everything to GPU memory\n");
   192
   193		// setup execution parameters
   194		dim3  grid( num_of_blocks, 1, 1);
   195		dim3  threads( num_of_threads_per_block, 1, 1);
   196
   197		int k=0;
   198		printf("Start traversing the tree\n");
   199		bool stop;
   200
   201			cudaEvent_t bfs_start_event, bfs_stop_event;
   202			cudaEventCreate(&bfs_start_event);
   203			cudaEventCreate(&bfs_stop_event);
   204		//Call the Kernel untill all the elements of Frontier are not false
   205			cudaEventRecord(bfs_start_event);
   206		do
   207		{
   208			//if no thread changes this value then the loop stops
   209			stop=false;
   210			cudaMemcpy( d_over, &stop, sizeof(bool), cudaMemcpyHostToDevice) ;

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
lines = path.read_text().splitlines(keepends=True)

# Make sure we are modifying the original, unmodified structure
if "cudaEvent_t start, stop_event;" in "".join(lines):
    raise RuntimeError("Timing code already exists. Do not run this cell again.")

# 1. Insert CUDA event declarations after: bool stop;
for i, line in enumerate(lines):
    if line.strip() == "bool stop;":
        lines[i+1:i+1] = [
            "\n",
            "\t\tcudaEvent_t start, stop_event;\n",
            "\t\tcudaEventCreate(&start);\n",
            "\t\tcudaEventCreate(&stop_event);\n"
        ]
        break
else:
    raise RuntimeError("Could not find 'bool stop;'.")

# 2. Insert start event immediately before the do loop
for i, line in enumerate(lines):
    if line.strip() == "do":
        lines[i:i] = [
            "\t\tcudaEventRecord(start);\n"
        ]
        break
else:
    raise RuntimeError("Could not find the BFS 'do' loop.")

# 3. Find the while(stop); and insert timing code after it
for i, line in enumerate(lines):
    if line.strip() == "while(stop);":
        lines[i+1:i+1] = [
            "\n",
            "\t\tcudaEventRecord(stop_event);\n",
            "\t\tcudaEventSynchronize(stop_event);\n",
            "\n",
            "\t\tfloat kernel_time_ms = 0.0f;\n",
            "\t\tcudaEventElapsedTime(&kernel_time_ms, start, stop_event);\n",
            "\n",
            "\t\tprintf(\"GPU Kernel Time: %.6f ms\\n\", kernel_time_ms);\n",
            "\n",
            "\t\tcudaEventDestroy(start);\n",
            "\t\tcudaEventDestroy(stop_event);\n"
        ]
        break
else:
    raise RuntimeError("Could not find 'while(stop);'.")

path.write_text("".join(lines))

print("CUDA timing code inserted successfully.")

/kaggle/working/Rodinia/cuda/bfs
CUDA timing code inserted successfully.

In [ ]:
!nl -ba bfs.cu | sed -n '178,225p'

   178		// allocate device memory for result
   179		int* d_cost;
   180		cudaMalloc( (void**) &d_cost, sizeof(int)*no_of_nodes);
   181		cudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;
   182
   183		cudaEventRecord(h2d_stop_event);
   184		cudaEventSynchronize(h2d_stop_event);
   185		cudaEventElapsedTime(&h2d_time_ms, h2d_start_event, h2d_stop_event);
   186
   187		//make a bool to check if the execution is over
   188		bool *d_over;
   189		cudaMalloc( (void**) &d_over, sizeof(bool));
   190
   191		printf("Copied Everything to GPU memory\n");
   192
   193		// setup execution parameters
   194		dim3  grid( num_of_blocks, 1, 1);
   195		dim3  threads( num_of_threads_per_block, 1, 1);
   196
   197		int k=0;
   198		printf("Start traversing the tree\n");
   199		bool stop;
   200
   201			cudaEvent_t start, stop_event;
   202			cudaEventCreate(&start);
   203			cudaEventCreate(&stop_event);
   204
   205			cudaEvent_t bfs_start_event, bfs_stop_event;
   206			cudaEventCreate(&bfs_start_event);
   207			cudaEventCreate(&bfs_stop_event);
   208		//Call the Kernel untill all the elements of Frontier are not false
   209			cudaEventRecord(bfs_start_event);
   210			cudaEventRecord(start);
   211		do
   212		{
   213			//if no thread changes this value then the loop stops
   214			stop=false;
   215			cudaMemcpy( d_over, &stop, sizeof(bool), cudaMemcpyHostToDevice) ;
   216			Kernel<<< grid, threads, 0 >>>( d_graph_nodes, d_graph_edges, d_graph_mask, d_updating_graph_mask, d_graph_visited, d_cost, no_of_nodes);
   217			// check if kernel execution generated and error
   218
   219
   220			Kernel2<<< grid, threads, 0 >>>( d_graph_mask, d_updating_graph_mask, d_graph_visited, d_over, no_of_nodes);
   221			// check if kernel execution generated and error
   222
   223
   224			cudaMemcpy( &stop, d_over, sizeof(bool), cudaMemcpyDeviceToHost) ;
   225			k++;

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!make clean
!make

/kaggle/working/Rodinia/cuda/bfs
rm -f bfs bfs.linkinfo result.txt
/usr/local/cuda/bin/nvcc bfs.cu -o bfs -I/usr/local/cuda/include -L/usr/local/cuda/lib64
nvcc warning : Support for offline compilation for architectures prior to '<compute/sm/lto>_75' will be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
bfs.cu(201): error: "start" has already been declared in the current scope
    cudaEvent_t start, stop_event;
                ^

bfs.cu(243): error: "kernel_time_ms" has already been declared in the current scope
    float kernel_time_ms = 0.0f;
          ^

2 errors detected in the compilation of "bfs.cu".
make: *** [Makefile:12: release] Error 2

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

text = text.replace(
    "cudaEvent_t start, stop_event;",
    "cudaEvent_t bfs_start_event, bfs_stop_event;"
)

text = text.replace(
    "cudaEventCreate(&start);",
    "cudaEventCreate(&bfs_start_event);"
)

text = text.replace(
    "cudaEventCreate(&stop_event);",
    "cudaEventCreate(&bfs_stop_event);"
)

text = text.replace(
    "cudaEventRecord(start);",
    "cudaEventRecord(bfs_start_event);"
)

text = text.replace(
    "cudaEventRecord(stop_event);",
    "cudaEventRecord(bfs_stop_event);"
)

text = text.replace(
    "cudaEventSynchronize(stop_event);",
    "cudaEventSynchronize(bfs_stop_event);"
)

text = text.replace(
    "cudaEventElapsedTime(&kernel_time_ms, start, stop_event);",
    "cudaEventElapsedTime(&kernel_time_ms, bfs_start_event, bfs_stop_event);"
)

text = text.replace(
    "cudaEventDestroy(start);",
    "cudaEventDestroy(bfs_start_event);"
)

text = text.replace(
    "cudaEventDestroy(stop_event);",
    "cudaEventDestroy(bfs_stop_event);"
)

path.write_text(text)

print("Renamed BFS timing events successfully.")

/kaggle/working/Rodinia/cuda/bfs
Renamed BFS timing events successfully.

In [ ]:
!nl -ba bfs.cu | sed -n '178,220p'

   178		// allocate device memory for result
   179		int* d_cost;
   180		cudaMalloc( (void**) &d_cost, sizeof(int)*no_of_nodes);
   181		cudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;
   182
   183		cudaEventRecord(h2d_stop_event);
   184		cudaEventSynchronize(h2d_stop_event);
   185		cudaEventElapsedTime(&h2d_time_ms, h2d_start_event, h2d_stop_event);
   186
   187		//make a bool to check if the execution is over
   188		bool *d_over;
   189		cudaMalloc( (void**) &d_over, sizeof(bool));
   190
   191		printf("Copied Everything to GPU memory\n");
   192
   193		// setup execution parameters
   194		dim3  grid( num_of_blocks, 1, 1);
   195		dim3  threads( num_of_threads_per_block, 1, 1);
   196
   197		int k=0;
   198		printf("Start traversing the tree\n");
   199		bool stop;
   200
   201			cudaEvent_t bfs_start_event, bfs_stop_event;
   202			cudaEventCreate(&bfs_start_event);
   203			cudaEventCreate(&bfs_stop_event);
   204
   205			cudaEvent_t bfs_start_event, bfs_stop_event;
   206			cudaEventCreate(&bfs_start_event);
   207			cudaEventCreate(&bfs_stop_event);
   208		//Call the Kernel untill all the elements of Frontier are not false
   209			cudaEventRecord(bfs_start_event);
   210			cudaEventRecord(bfs_start_event);
   211		do
   212		{
   213			//if no thread changes this value then the loop stops
   214			stop=false;
   215			cudaMemcpy( d_over, &stop, sizeof(bool), cudaMemcpyHostToDevice) ;
   216			Kernel<<< grid, threads, 0 >>>( d_graph_nodes, d_graph_edges, d_graph_mask, d_updating_graph_mask, d_graph_visited, d_cost, no_of_nodes);
   217			// check if kernel execution generated and error
   218
   219
   220			Kernel2<<< grid, threads, 0 >>>( d_graph_mask, d_updating_graph_mask, d_graph_visited, d_over, no_of_nodes);

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!make clean
!make

/kaggle/working/Rodinia/cuda/bfs
rm -f bfs bfs.linkinfo result.txt
/usr/local/cuda/bin/nvcc bfs.cu -o bfs -I/usr/local/cuda/include -L/usr/local/cuda/lib64
nvcc warning : Support for offline compilation for architectures prior to '<compute/sm/lto>_75' will be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
bfs.cu(205): error: "bfs_start_event" has already been declared in the current scope
    cudaEvent_t bfs_start_event, bfs_stop_event;
                ^

bfs.cu(205): error: "bfs_stop_event" has already been declared in the current scope
    cudaEvent_t bfs_start_event, bfs_stop_event;
                                 ^

bfs.cu(243): error: "kernel_time_ms" has already been declared in the current scope
    float kernel_time_ms = 0.0f;
          ^

3 errors detected in the compilation of "bfs.cu".
make: *** [Makefile:12: release] Error 2

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!./bfs ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/cuda/bfs
/bin/bash: line 1: ./bfs: No such file or directory

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!./bfs ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/cuda/bfs
/bin/bash: line 1: ./bfs: No such file or directory

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!./bfs ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/cuda/bfs
/bin/bash: line 1: ./bfs: No such file or directory

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!./bfs ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/cuda/bfs
/bin/bash: line 1: ./bfs: No such file or directory

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!./bfs ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/cuda/bfs
/bin/bash: line 1: ./bfs: No such file or directory

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!./bfs ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/cuda/bfs
/bin/bash: line 1: ./bfs: No such file or directory

In [ ]:
%cd /kaggle/working/Rodinia/openmp/bfs

!./bfs 4 ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/openmp/bfs
Reading File
Start traversing the tree
Compute time: 0.035782
Result stored in result.txt

In [ ]:
%cd /kaggle/working/Rodinia/openmp/bfs

!./bfs 4 ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/openmp/bfs
Reading File
Start traversing the tree
Compute time: 0.038879
Result stored in result.txt

In [ ]:
%cd /kaggle/working/Rodinia/openmp/bfs

!./bfs 4 ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/openmp/bfs
Reading File
Start traversing the tree
Compute time: 0.038598
Result stored in result.txt

In [ ]:
%cd /kaggle/working/Rodinia/openmp/bfs

!./bfs 4 ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/openmp/bfs
Reading File
Start traversing the tree
Compute time: 0.035484
Result stored in result.txt

In [ ]:
%cd /kaggle/working/Rodinia/openmp/bfs

!./bfs 4 ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/openmp/bfs
Reading File
Start traversing the tree
Compute time: 0.041035
Result stored in result.txt

In [ ]:
%cd /kaggle/working/Rodinia/openmp/bfs

!./bfs 4 ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/openmp/bfs
Reading File
Start traversing the tree
Compute time: 0.038074
Result stored in result.txt

In [ ]:
%cd /kaggle/working/Rodinia/openmp/bfs

!./bfs 4 ../../data/bfs/graph1MW_6.txt

/kaggle/working/Rodinia/openmp/bfs
Reading File
Start traversing the tree
Compute time: 0.038373
Result stored in result.txt

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!cp bfs.cu bfs_kernel_timed.cu
!cp bfs bfs_kernel_timed

/kaggle/working/Rodinia/cuda/bfs
cp: cannot stat 'bfs': No such file or directory

In [ ]:
!ls -lh bfs.cu bfs bfs_kernel_timed.cu bfs_kernel_timed

ls: cannot access 'bfs': No such file or directory
-rwxr-xr-x 1 root root 8.3K Sep 25 09:15 bfs.cu
-rwxr-xr-x 1 root root 989K Sep 25 09:07 bfs_kernel_timed
-rwxr-xr-x 1 root root 8.3K Sep 25 09:15 bfs_kernel_timed.cu

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!grep -n "cudaMemcpy" bfs.cu

/kaggle/working/Rodinia/cuda/bfs
151:	cudaMemcpy( d_graph_nodes, h_graph_nodes, sizeof(Node)*no_of_nodes, cudaMemcpyHostToDevice) ;
156:	cudaMemcpy( d_graph_edges, h_graph_edges, sizeof(int)*edge_list_size, cudaMemcpyHostToDevice) ;
161:	cudaMemcpy( d_graph_mask, h_graph_mask, sizeof(bool)*no_of_nodes, cudaMemcpyHostToDevice) ;
165:	cudaMemcpy( d_updating_graph_mask, h_updating_graph_mask, sizeof(bool)*no_of_nodes, cudaMemcpyHostToDevice) ;
170:	cudaMemcpy( d_graph_visited, h_graph_visited, sizeof(bool)*no_of_nodes, cudaMemcpyHostToDevice) ;
181:	cudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;
215:		cudaMemcpy( d_over, &stop, sizeof(bool), cudaMemcpyHostToDevice) ;
224:		cudaMemcpy( &stop, d_over, sizeof(bool), cudaMemcpyDeviceToHost) ;
256:	cudaMemcpy( h_cost, d_cost, sizeof(int)*no_of_nodes, cudaMemcpyDeviceToHost) ;

In [ ]:
!nl -ba bfs.cu | sed -n '125,225p'

   125		{
   126			fscanf(fp,"%d",&id);
   127			fscanf(fp,"%d",&cost);
   128			h_graph_edges[i] = id;
   129		}
   130
   131		if(fp)
   132			fclose(fp);
   133
   134		printf("Read File\n");
   135
   136		cudaEvent_t h2d_start_event, h2d_stop_event;
   137		cudaEvent_t d2h_start_event, d2h_stop_event;
   138
   139		cudaEventCreate(&h2d_start_event);
   140		cudaEventCreate(&h2d_stop_event);
   141		cudaEventCreate(&d2h_start_event);
   142		cudaEventCreate(&d2h_stop_event);
   143
   144		float h2d_time_ms = 0.0f;
   145		float d2h_time_ms = 0.0f;
   146
   147		//Copy the Node list to device memory
   148		Node* d_graph_nodes;
   149		cudaMalloc( (void**) &d_graph_nodes, sizeof(Node)*no_of_nodes) ;
   150		cudaEventRecord(h2d_start_event);
   151		cudaMemcpy( d_graph_nodes, h_graph_nodes, sizeof(Node)*no_of_nodes, cudaMemcpyHostToDevice) ;
   152
   153		//Copy the Edge List to device Memory
   154		int* d_graph_edges;
   155		cudaMalloc( (void**) &d_graph_edges, sizeof(int)*edge_list_size) ;
   156		cudaMemcpy( d_graph_edges, h_graph_edges, sizeof(int)*edge_list_size, cudaMemcpyHostToDevice) ;
   157
   158		//Copy the Mask to device memory
   159		bool* d_graph_mask;
   160		cudaMalloc( (void**) &d_graph_mask, sizeof(bool)*no_of_nodes) ;
   161		cudaMemcpy( d_graph_mask, h_graph_mask, sizeof(bool)*no_of_nodes, cudaMemcpyHostToDevice) ;
   162
   163		bool* d_updating_graph_mask;
   164		cudaMalloc( (void**) &d_updating_graph_mask, sizeof(bool)*no_of_nodes) ;
   165		cudaMemcpy( d_updating_graph_mask, h_updating_graph_mask, sizeof(bool)*no_of_nodes, cudaMemcpyHostToDevice) ;
   166
   167		//Copy the Visited nodes array to device memory
   168		bool* d_graph_visited;
   169		cudaMalloc( (void**) &d_graph_visited, sizeof(bool)*no_of_nodes) ;
   170		cudaMemcpy( d_graph_visited, h_graph_visited, sizeof(bool)*no_of_nodes, cudaMemcpyHostToDevice) ;
   171
   172		// allocate mem for the result on host side
   173		int* h_cost = (int*) malloc( sizeof(int)*no_of_nodes);
   174		for(int i=0;i<no_of_nodes;i++)
   175			h_cost[i]=-1;
   176		h_cost[source]=0;
   177
   178		// allocate device memory for result
   179		int* d_cost;
   180		cudaMalloc( (void**) &d_cost, sizeof(int)*no_of_nodes);
   181		cudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;
   182
   183		cudaEventRecord(h2d_stop_event);
   184		cudaEventSynchronize(h2d_stop_event);
   185		cudaEventElapsedTime(&h2d_time_ms, h2d_start_event, h2d_stop_event);
   186
   187		//make a bool to check if the execution is over
   188		bool *d_over;
   189		cudaMalloc( (void**) &d_over, sizeof(bool));
   190
   191		printf("Copied Everything to GPU memory\n");
   192
   193		// setup execution parameters
   194		dim3  grid( num_of_blocks, 1, 1);
   195		dim3  threads( num_of_threads_per_block, 1, 1);
   196
   197		int k=0;
   198		printf("Start traversing the tree\n");
   199		bool stop;
   200
   201			cudaEvent_t bfs_start_event, bfs_stop_event;
   202			cudaEventCreate(&bfs_start_event);
   203			cudaEventCreate(&bfs_stop_event);
   204
   205			cudaEvent_t bfs_start_event, bfs_stop_event;
   206			cudaEventCreate(&bfs_start_event);
   207			cudaEventCreate(&bfs_stop_event);
   208		//Call the Kernel untill all the elements of Frontier are not false
   209			cudaEventRecord(bfs_start_event);
   210			cudaEventRecord(bfs_start_event);
   211		do
   212		{
   213			//if no thread changes this value then the loop stops
   214			stop=false;
   215			cudaMemcpy( d_over, &stop, sizeof(bool), cudaMemcpyHostToDevice) ;
   216			Kernel<<< grid, threads, 0 >>>( d_graph_nodes, d_graph_edges, d_graph_mask, d_updating_graph_mask, d_graph_visited, d_cost, no_of_nodes);
   217			// check if kernel execution generated and error
   218
   219
   220			Kernel2<<< grid, threads, 0 >>>( d_graph_mask, d_updating_graph_mask, d_graph_visited, d_over, no_of_nodes);
   221			// check if kernel execution generated and error
   222
   223
   224			cudaMemcpy( &stop, d_over, sizeof(bool), cudaMemcpyDeviceToHost) ;
   225			k++;

In [ ]:
!cp bfs.cu bfs_before_transfer_timing.cu

!ls -lh bfs.cu bfs_kernel_timed.cu bfs_before_transfer_timing.cu

-rwxr-xr-x 1 root root 8.3K Sep 25 09:15 bfs_before_transfer_timing.cu
-rwxr-xr-x 1 root root 8.3K Sep 25 09:15 bfs.cu
-rwxr-xr-x 1 root root 8.3K Sep 25 09:15 bfs_kernel_timed.cu

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

# Make sure this modification has not already been applied
if "h2d_start_event" in text:
    raise RuntimeError("Transfer timing code already exists.")

# Insert transfer event declarations before the existing BFS timing events
old = "\t\tcudaEvent_t bfs_start_event, bfs_stop_event;"

new = """\t\tcudaEvent_t bfs_start_event, bfs_stop_event;
\t\tcudaEvent_t h2d_start_event, h2d_stop_event;
\t\tcudaEvent_t d2h_start_event, d2h_stop_event;

\t\tcudaEventCreate(&h2d_start_event);
\t\tcudaEventCreate(&h2d_stop_event);
\t\tcudaEventCreate(&d2h_start_event);
\t\tcudaEventCreate(&d2h_stop_event);

\t\tfloat h2d_time_ms = 0.0f;
\t\tfloat d2h_time_ms = 0.0f;"""

if old not in text:
    raise RuntimeError("Could not find the existing BFS timing declarations.")

text = text.replace(old, new, 1)

path.write_text(text)

print("Transfer timing variables inserted.")

/kaggle/working/Rodinia/cuda/bfs

RuntimeError: Transfer timing code already exists.

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

# Start timing immediately before the first initial H->D copy
old = """\t//Copy the Node list to device memory
\tNode* d_graph_nodes;
\tcudaMalloc( (void**) &d_graph_nodes, sizeof(Node)*no_of_nodes) ;
\tcudaMemcpy( d_graph_nodes, h_graph_nodes, sizeof(Node)*no_of_nodes, cudaMemcpyHostToDevice) ;"""

new = """\t//Copy the Node list to device memory
\tNode* d_graph_nodes;
\tcudaMalloc( (void**) &d_graph_nodes, sizeof(Node)*no_of_nodes) ;

\tcudaEventRecord(h2d_start_event);

\tcudaMemcpy( d_graph_nodes, h_graph_nodes, sizeof(Node)*no_of_nodes, cudaMemcpyHostToDevice) ;"""

if old not in text:
    raise RuntimeError("Could not find the first Host-to-Device copy.")

text = text.replace(old, new, 1)

# Stop timing after the final initial H->D copy
old = """\t// allocate device memory for result
\tint* d_cost;
\tcudaMalloc( (void**) &d_cost, sizeof(int)*no_of_nodes);
\tcudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;

\t//make a bool to check if the execution is over"""

new = """\t// allocate device memory for result
\tint* d_cost;
\tcudaMalloc( (void**) &d_cost, sizeof(int)*no_of_nodes);
\tcudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;

\tcudaEventRecord(h2d_stop_event);
\tcudaEventSynchronize(h2d_stop_event);
\tcudaEventElapsedTime(&h2d_time_ms, h2d_start_event, h2d_stop_event);

\t//make a bool to check if the execution is over"""

if old not in text:
    raise RuntimeError("Could not find the final initial Host-to-Device copy.")

text = text.replace(old, new, 1)

path.write_text(text)

print("Initial Host-to-Device timing inserted.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

old = """\t// copy result from device to host
\tcudaMemcpy( h_cost, d_cost, sizeof(int)*no_of_nodes, cudaMemcpyDeviceToHost) ;"""

new = """\t// copy result from device to host
\tcudaEventRecord(d2h_start_event);

\tcudaMemcpy( h_cost, d_cost, sizeof(int)*no_of_nodes, cudaMemcpyDeviceToHost) ;

\tcudaEventRecord(d2h_stop_event);
\tcudaEventSynchronize(d2h_stop_event);
\tcudaEventElapsedTime(&d2h_time_ms, d2h_start_event, d2h_stop_event);

\tprintf("Host to Device Time: %.6f ms\\n", h2d_time_ms);
\tprintf("Device to Host Time: %.6f ms\\n", d2h_time_ms);
\tprintf("Total Transfer Time: %.6f ms\\n", h2d_time_ms + d2h_time_ms);"""

if old not in text:
    raise RuntimeError("Could not find the final Device-to-Host copy.")

text = text.replace(old, new, 1)

path.write_text(text)

print("Final Device-to-Host timing inserted.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

old = """\t\tcudaEventDestroy(bfs_start_event);
\t\tcudaEventDestroy(bfs_stop_event);"""

new = """\t\tcudaEventDestroy(bfs_start_event);
\t\tcudaEventDestroy(bfs_stop_event);
\t\tcudaEventDestroy(h2d_start_event);
\t\tcudaEventDestroy(h2d_stop_event);
\t\tcudaEventDestroy(d2h_start_event);
\t\tcudaEventDestroy(d2h_stop_event);"""

if old not in text:
    raise RuntimeError("Could not find existing BFS event cleanup.")

text = text.replace(old, new, 1)

path.write_text(text)

print("CUDA transfer timing cleanup inserted.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!nl -ba bfs.cu | sed -n '130,245p'

In [ ]:
!grep -n -E "h2d_|d2h_|bfs_.*event|Host to Device|Device to Host|Total Transfer" bfs.cu

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!cp bfs_before_transfer_timing.cu bfs.cu

print("Restored BFS source to pre-transfer-timing version.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!grep -n -E "h2d_|d2h_|Host to Device|Device to Host|Total Transfer" bfs.cu

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!cp bfs.cu bfs_before_transfer_timing_v2.cu

print("Backup created: bfs_before_transfer_timing_v2.cu")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

old = """\tprintf("Read File\\n");

\t//Copy the Node list to device memory"""

new = """\tprintf("Read File\\n");

\tcudaEvent_t h2d_start_event, h2d_stop_event;
\tcudaEvent_t d2h_start_event, d2h_stop_event;

\tcudaEventCreate(&h2d_start_event);
\tcudaEventCreate(&h2d_stop_event);
\tcudaEventCreate(&d2h_start_event);
\tcudaEventCreate(&d2h_stop_event);

\tfloat h2d_time_ms = 0.0f;
\tfloat d2h_time_ms = 0.0f;

\t//Copy the Node list to device memory"""

if old not in text:
    raise RuntimeError("Could not find the correct location for transfer event declarations.")

text = text.replace(old, new, 1)

path.write_text(text)

print("Transfer event declarations and creation inserted correctly.")

%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

old = """\tNode* d_graph_nodes;

\tcudaMalloc( (void**) &d_graph_nodes, sizeof(Node)*no_of_nodes) ;

\tcudaMemcpy( d_graph_nodes, h_graph_nodes, sizeof(Node)*no_of_nodes, cudaMemcpyHostToDevice) ;"""

new = """\tNode* d_graph_nodes;

\tcudaMalloc( (void**) &d_graph_nodes, sizeof(Node)*no_of_nodes) ;

\tcudaEventRecord(h2d_start_event);

\tcudaMemcpy( d_graph_nodes, h_graph_nodes, sizeof(Node)*no_of_nodes, cudaMemcpyHostToDevice) ;"""

if old not in text:
    raise RuntimeError("Could not find the first H-to-D transfer.")

text = text.replace(old, new, 1)

path.write_text(text)

print("H-to-D timing started before the first transfer.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

target = "cudaMemcpy( d_graph_nodes, h_graph_nodes, sizeof(Node)*no_of_nodes, cudaMemcpyHostToDevice) ;"

if target not in text:
    raise RuntimeError("The expected Node Host-to-Device cudaMemcpy line was not found.")

if "cudaEventRecord(h2d_start_event);" in text:
    print("H-to-D start timing is already present. No change made.")
else:
    text = text.replace(
        target,
        "cudaEventRecord(h2d_start_event);\n\t" + target,
        1
    )

    path.write_text(text)
    print("H-to-D start timing inserted.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!nl -ba bfs.cu | sed -n '130,175p'

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

target = "cudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;"

if target not in text:
    raise RuntimeError("The expected d_cost Host-to-Device cudaMemcpy line was not found.")

if "cudaEventElapsedTime(&h2d_time_ms" in text:
    print("H-to-D stop timing is already present. No change made.")
else:
    replacement = """cudaMemcpy( d_cost, h_cost, sizeof(int)*no_of_nodes, cudaMemcpyHostToDevice) ;

\tcudaEventRecord(h2d_stop_event);
\tcudaEventSynchronize(h2d_stop_event);
\tcudaEventElapsedTime(&h2d_time_ms, h2d_start_event, h2d_stop_event);"""

    text = text.replace(target, replacement, 1)
    path.write_text(text)

    print("H-to-D stop timing inserted.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!grep -n -E "h2d_|cudaMemcpy.*HostToDevice" bfs.cu

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!nl -ba bfs.cu | sed -n '130,190p'

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!nl -ba bfs.cu | sed -n '215,250p'

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

target = "cudaMemcpy( h_cost, d_cost, sizeof(int)*no_of_nodes, cudaMemcpyDeviceToHost) ;"

if target not in text:
    raise RuntimeError("The final Device-to-Host copy was not found.")

if "cudaEventRecord(d2h_start_event);" in text:
    print("D-to-H start timing is already present. No change made.")
else:
    text = text.replace(
        target,
        "cudaEventRecord(d2h_start_event);\n\t" + target,
        1
    )

    path.write_text(text)
    print("D-to-H start timing inserted.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

target = "cudaMemcpy( h_cost, d_cost, sizeof(int)*no_of_nodes, cudaMemcpyDeviceToHost) ;"

replacement = """cudaEventRecord(d2h_start_event);
\tcudaMemcpy( h_cost, d_cost, sizeof(int)*no_of_nodes, cudaMemcpyDeviceToHost) ;

\tcudaEventRecord(d2h_stop_event);
\tcudaEventSynchronize(d2h_stop_event);
\tcudaEventElapsedTime(&d2h_time_ms, d2h_start_event, d2h_stop_event);"""

if "cudaEventElapsedTime(&d2h_time_ms" in text:
    print("D-to-H stop timing is already present. No change made.")
elif target in text:
    text = text.replace(target, replacement, 1)
    path.write_text(text)
    print("D-to-H timing completed.")
else:
    raise RuntimeError("The final Device-to-Host copy was not found.")

%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

target = '\t//Store result in a file'

replacement = """\tprintf("Initial Host to Device Time: %.6f ms\\n", h2d_time_ms);
\tprintf("Final Device to Host Time: %.6f ms\\n", d2h_time_ms);

\t//Store result in a file"""

if "Initial Host to Device Time:" in text:
    print("Transfer timing output is already present. No change made.")
elif target in text:
    text = text.replace(target, replacement, 1)
    path.write_text(text)
    print("Transfer timing output added.")
else:
    raise RuntimeError("Could not find the result-storage section.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!nl -ba bfs.cu | sed -n '235,275p'

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

duplicate = """\t// copy result from device to host
\tcudaEventRecord(d2h_start_event);
\tcudaEventRecord(d2h_start_event);"""

correct = """\t// copy result from device to host
\tcudaEventRecord(d2h_start_event);"""

if duplicate not in text:
    raise RuntimeError("Duplicate D-to-H start pattern was not found.")

text = text.replace(duplicate, correct, 1)

path.write_text(text)

print("Duplicate D-to-H start event removed.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

from pathlib import Path

path = Path("bfs.cu")
text = path.read_text()

target = "\t//Store the result into a file"

replacement = """\tprintf("Initial Host to Device Time: %.6f ms\\n", h2d_time_ms);
\tprintf("Final Device to Host Time: %.6f ms\\n", d2h_time_ms);

\t//Store the result into a file"""

if "Initial Host to Device Time:" in text:
    print("Transfer timing output is already present. No change made.")
elif target not in text:
    raise RuntimeError("Could not find the actual result-storage comment.")
else:
    text = text.replace(target, replacement, 1)
    path.write_text(text)
    print("Transfer timing output added.")

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!nl -ba bfs.cu | sed -n '232,260p'

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!grep -n -E "h2d_|d2h_|Initial Host|Final Device" bfs.cu

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!nl -ba bfs.cu | sed -n '220,285p'

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!grep -n -E "cudaEvent(Create|Record|Synchronize|ElapsedTime|Destroy)" bfs.cu

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!grep -n "cudaMemcpy" bfs.cu

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!make clean
!make

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!ls -lh bfs

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

!./bfs ../../data/bfs/graph1MW_6.txt

In [ ]:
%cd /kaggle/working/Rodinia/cuda/bfs

import subprocess

for i in range(1, 7):
    print(f"========== GPU RUN {i} ==========")
    
    result = subprocess.run(
        ["./bfs", "../../data/bfs/graph1MW_6.txt"],
        capture_output=True,
        text=True
    )
    
    for line in result.stdout.splitlines():
        if any(x in line for x in [
            "GPU Kernel Time",
            "Initial Host to Device",
            "Final Device to Host",
            "Kernel Executed"
        ]):
            print(line)

In [ ]:
!nvidia-smi --query-gpu=name,memory.total,utilization.gpu --format=csv,noheader

In [ ]:
%cd /kaggle/working/Rodinia/openmp/bfs

!ls -lh bfs

In [ ]:
%cd /kaggle/working/Rodinia/openmp/bfs

import subprocess

for i in range(1, 7):
    print(f"========== CPU RUN {i} ==========")
    
    result = subprocess.run(
        ["./bfs", "4", "../../data/bfs/graph1MW_6.txt"],
        capture_output=True,
        text=True
    )
    
    for line in result.stdout.splitlines():
        if "Compute time" in line:
            print(line)

In [ ]:
%cd /kaggle/working/Rodinia

!ls -lh data/bfs/graph1MW_6.txt

In [ ]:
import pandas as pd

bfs_row = pd.DataFrame([{
    "workload": "bfs",
    "input_file": "graph1MW_6.txt",
    "input_size_mb": 62,
    "cpu_threads": 4,
    "gpu_type": "Tesla T4",
    "gpu_memory_mb": 15360,
    "cpu_execution_time_ms": 36.8665,
    "gpu_phase_time_ms": 3.5942,
    "host_to_device_time_ms": 14.6791,
    "device_to_host_time_ms": 0.6860,
    "gpu_kernel_iterations": 12
}])

bfs_row

In [ ]:
bfs_row["gpu_total_path_time_ms"] = (
    bfs_row["gpu_phase_time_ms"]
    + bfs_row["host_to_device_time_ms"]
    + bfs_row["device_to_host_time_ms"]
)

bfs_row

In [ ]:
bfs_row["preferred_device"] = bfs_row.apply(
    lambda row: "GPU"
    if row["gpu_total_path_time_ms"] < row["cpu_execution_time_ms"]
    else "CPU",
    axis=1
)

bfs_row

In [ ]:
dataset_path = "/kaggle/working/rodinia_cpu_gpu_dataset.csv"

bfs_row.to_csv(dataset_path, index=False)

print(f"Dataset saved to: {dataset_path}")

In [ ]:
# ============================================================
# RODINIA CPU-GPU AUTOMATED BENCHMARK SYSTEM
# ============================================================

import os
import re
import subprocess
import pandas as pd
import numpy as np
from pathlib import Path

# ------------------------------------------------------------
# CONFIGURATION
# ------------------------------------------------------------

RODINIA_ROOT = Path("/kaggle/working/Rodinia")

CPU_ROOT = RODINIA_ROOT / "openmp"
GPU_ROOT = RODINIA_ROOT / "cuda"
DATA_ROOT = RODINIA_ROOT / "data"

# Number of repeated measurements
N_RUNS = 6

# Output files
MASTER_DATASET = Path("/kaggle/working/rodinia_cpu_gpu_dataset.csv")
RAW_DATASET = Path("/kaggle/working/rodinia_raw_benchmark_results.csv")

print("Rodinia root:", RODINIA_ROOT)
print("CPU root:", CPU_ROOT)
print("GPU root:", GPU_ROOT)
print("Data root:", DATA_ROOT)
print("Number of runs per device:", N_RUNS)

In [ ]:
# ============================================================
# COMMAND EXECUTION FUNCTION
# ============================================================

def run_command(command, cwd):
    """
    Run a command inside a specified directory.

    Returns:
        stdout, stderr, return_code
    """

    result = subprocess.run(
        command,
        cwd=str(cwd),
        capture_output=True,
        text=True
    )

    return result.stdout, result.stderr, result.returncode

In [ ]:
# ============================================================
# CPU BENCHMARK FUNCTION
# ============================================================

def benchmark_cpu(
    workload,
    input_file,
    threads=4,
    n_runs=N_RUNS
):
    """
    Benchmark a Rodinia OpenMP workload.

    Expected command format:
        ./program <threads> <input_file>

    Returns a list containing raw CPU measurements.
    """

    cpu_dir = CPU_ROOT / workload
    executable = cpu_dir / workload

    if not executable.exists():
        raise FileNotFoundError(
            f"CPU executable not found:\n{executable}"
        )

    measurements = []

    print()
    print("=" * 60)
    print(f"CPU BENCHMARK: {workload}")
    print("=" * 60)

    for run in range(1, n_runs + 1):

        print(f"CPU Run {run}/{n_runs}")

        stdout, stderr, return_code = run_command(
            [
                f"./{workload}",
                str(threads),
                input_file
            ],
            cpu_dir
        )

        if return_code != 0:
            print("CPU execution failed.")
            print(stderr)
            raise RuntimeError(
                f"CPU benchmark failed for {workload}, run {run}"
            )

        # Rodinia BFS prints:
        # Compute time: 0.037446
        match = re.search(
            r"Compute time:\s*([0-9]*\.?[0-9]+)",
            stdout
        )

        if match is None:
            print(stdout)
            raise RuntimeError(
                f"Could not extract CPU execution time "
                f"for {workload}, run {run}"
            )

        cpu_time_seconds = float(match.group(1))
        cpu_time_ms = cpu_time_seconds * 1000.0

        measurements.append(cpu_time_ms)

        print(f"  CPU time: {cpu_time_ms:.6f} ms")

    print()
    print(
        f"CPU mean: {np.mean(measurements):.6f} ms"
    )

    return measurements

In [ ]:
# ============================================================
# GPU BENCHMARK FUNCTION
# ============================================================

def benchmark_gpu(
    workload,
    input_file,
    n_runs=N_RUNS
):
    """
    Benchmark a Rodinia CUDA workload.

    Extracts:
        GPU BFS/phase time
        H2D transfer time
        D2H transfer time
        Kernel iteration count
    """

    gpu_dir = GPU_ROOT / workload
    executable = gpu_dir / workload

    if not executable.exists():
        raise FileNotFoundError(
            f"GPU executable not found:\n{executable}"
        )

    measurements = []

    print()
    print("=" * 60)
    print(f"GPU BENCHMARK: {workload}")
    print("=" * 60)

    for run in range(1, n_runs + 1):

        print(f"GPU Run {run}/{n_runs}")

        stdout, stderr, return_code = run_command(
            [
                f"./{workload}",
                input_file
            ],
            gpu_dir
        )

        if return_code != 0:
            print(stdout)
            print(stderr)

            raise RuntimeError(
                f"GPU benchmark failed for {workload}, run {run}"
            )

        # ----------------------------------------------------
        # GPU phase time
        # ----------------------------------------------------

        phase_match = re.search(
            r"GPU Kernel Time:\s*([0-9]*\.?[0-9]+)\s*ms",
            stdout
        )

        # ----------------------------------------------------
        # H2D time
        # ----------------------------------------------------

        h2d_match = re.search(
            r"Initial Host to Device Time:\s*"
            r"([0-9]*\.?[0-9]+)\s*ms",
            stdout
        )

        # ----------------------------------------------------
        # D2H time
        # ----------------------------------------------------

        d2h_match = re.search(
            r"Final Device to Host Time:\s*"
            r"([0-9]*\.?[0-9]+)\s*ms",
            stdout
        )

        # ----------------------------------------------------
        # Kernel iterations
        # ----------------------------------------------------

        iteration_match = re.search(
            r"Kernel Executed\s+(\d+)\s+times",
            stdout
        )

        if phase_match is None:
            raise RuntimeError(
                f"Could not extract GPU phase time "
                f"for {workload}, run {run}"
            )

        if h2d_match is None:
            raise RuntimeError(
                f"Could not extract H2D time "
                f"for {workload}, run {run}"
            )

        if d2h_match is None:
            raise RuntimeError(
                f"Could not extract D2H time "
                f"for {workload}, run {run}"
            )

        if iteration_match is None:
            raise RuntimeError(
                f"Could not extract kernel iterations "
                f"for {workload}, run {run}"
            )

        phase_time_ms = float(phase_match.group(1))
        h2d_time_ms = float(h2d_match.group(1))
        d2h_time_ms = float(d2h_match.group(1))
        iterations = int(iteration_match.group(1))

        measurements.append({
            "gpu_phase_time_ms": phase_time_ms,
            "host_to_device_time_ms": h2d_time_ms,
            "device_to_host_time_ms": d2h_time_ms,
            "gpu_kernel_iterations": iterations
        })

        print(
            f"  GPU phase: {phase_time_ms:.6f} ms | "
            f"H2D: {h2d_time_ms:.6f} ms | "
            f"D2H: {d2h_time_ms:.6f} ms | "
            f"Iterations: {iterations}"
        )

    return measurements

In [ ]:
# ============================================================
# GPU HARDWARE INFORMATION
# ============================================================

def get_gpu_info():

    result = subprocess.run(
        [
            "nvidia-smi",
            "--query-gpu=name,memory.total",
            "--format=csv,noheader"
        ],
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        return "Unknown", np.nan

    lines = result.stdout.strip().splitlines()

    if len(lines) == 0:
        return "Unknown", np.nan

    # Use first GPU
    first_gpu = lines[0]

    parts = [x.strip() for x in first_gpu.split(",")]

    gpu_name = parts[0]

    memory_match = re.search(
        r"([0-9]+)",
        parts[1]
    )

    gpu_memory = (
        int(memory_match.group(1))
        if memory_match
        else np.nan
    )

    return gpu_name, gpu_memory


gpu_name, gpu_memory = get_gpu_info()

print("GPU:", gpu_name)
print("GPU memory:", gpu_memory, "MiB")

In [ ]:
# ============================================================
# COMPLETE WORKLOAD BENCHMARK
# ============================================================

def benchmark_workload(
    workload,
    cpu_input,
    gpu_input,
    input_size_mb=None,
    cpu_threads=4,
    n_runs=N_RUNS
):
    """
    Benchmark one Rodinia workload on both CPU and GPU.
    """

    print()
    print("#" * 70)
    print(f"# BENCHMARKING WORKLOAD: {workload}")
    print("#" * 70)

    # --------------------------------------------------------
    # CPU
    # --------------------------------------------------------

    cpu_times = benchmark_cpu(
        workload=workload,
        input_file=cpu_input,
        threads=cpu_threads,
        n_runs=n_runs
    )

    # --------------------------------------------------------
    # GPU
    # --------------------------------------------------------

    gpu_results = benchmark_gpu(
        workload=workload,
        input_file=gpu_input,
        n_runs=n_runs
    )

    # --------------------------------------------------------
    # Convert GPU measurements into arrays
    # --------------------------------------------------------

    gpu_phase_times = [
        x["gpu_phase_time_ms"]
        for x in gpu_results
    ]

    h2d_times = [
        x["host_to_device_time_ms"]
        for x in gpu_results
    ]

    d2h_times = [
        x["device_to_host_time_ms"]
        for x in gpu_results
    ]

    iterations = [
        x["gpu_kernel_iterations"]
        for x in gpu_results
    ]

    # --------------------------------------------------------
    # Calculate representative measurements
    # --------------------------------------------------------

    cpu_mean = np.mean(cpu_times)

    gpu_phase_mean = np.mean(gpu_phase_times)

    h2d_mean = np.mean(h2d_times)

    d2h_mean = np.mean(d2h_times)

    iteration_mean = np.mean(iterations)

    # Transfer-aware GPU path
    gpu_total = (
        gpu_phase_mean
        + h2d_mean
        + d2h_mean
    )

    # --------------------------------------------------------
    # Select measured device
    # --------------------------------------------------------

    preferred_device = (
        "GPU"
        if gpu_total < cpu_mean
        else "CPU"
    )

    # --------------------------------------------------------
    # Create dataset row
    # --------------------------------------------------------

    row = {
        "workload": workload,
        "input_file": Path(gpu_input).name,
        "input_size_mb": input_size_mb,

        "cpu_threads": cpu_threads,

        "gpu_type": gpu_name,
        "gpu_memory_mb": gpu_memory,

        "cpu_execution_time_ms": cpu_mean,

        "gpu_phase_time_ms": gpu_phase_mean,

        "host_to_device_time_ms": h2d_mean,

        "device_to_host_time_ms": d2h_mean,

        "gpu_total_path_time_ms": gpu_total,

        "gpu_kernel_iterations": iteration_mean,

        "preferred_device": preferred_device
    }

    # --------------------------------------------------------
    # Print summary
    # --------------------------------------------------------

    print()
    print("=" * 70)
    print(f"RESULT: {workload}")
    print("=" * 70)

    print(f"CPU mean time       : {cpu_mean:.6f} ms")
    print(f"GPU phase mean      : {gpu_phase_mean:.6f} ms")
    print(f"H2D mean            : {h2d_mean:.6f} ms")
    print(f"D2H mean            : {d2h_mean:.6f} ms")
    print(f"GPU total path      : {gpu_total:.6f} ms")
    print(f"Preferred device    : {preferred_device}")

    return row, cpu_times, gpu_results

In [ ]:
# ============================================================
# SAVE RAW BENCHMARK RESULTS
# ============================================================

def save_raw_results(
    workload,
    cpu_times,
    gpu_results
):

    rows = []

    for i in range(len(cpu_times)):

        gpu = gpu_results[i]

        rows.append({
            "workload": workload,
            "run": i + 1,

            "cpu_execution_time_ms":
                cpu_times[i],

            "gpu_phase_time_ms":
                gpu["gpu_phase_time_ms"],

            "host_to_device_time_ms":
                gpu["host_to_device_time_ms"],

            "device_to_host_time_ms":
                gpu["device_to_host_time_ms"],

            "gpu_kernel_iterations":
                gpu["gpu_kernel_iterations"]
        })

    new_data = pd.DataFrame(rows)

    if RAW_DATASET.exists():

        old_data = pd.read_csv(RAW_DATASET)

        combined = pd.concat(
            [old_data, new_data],
            ignore_index=True
        )

    else:

        combined = new_data

    combined.to_csv(
        RAW_DATASET,
        index=False
    )

    print()
    print("Raw results saved to:")
    print(RAW_DATASET)

In [ ]:
# ============================================================
# SAVE MASTER DATASET
# ============================================================

def save_master_row(row):

    new_row = pd.DataFrame([row])

    if MASTER_DATASET.exists():

        old_data = pd.read_csv(MASTER_DATASET)

        # Avoid accidental duplicate workload rows
        old_data = old_data[
            old_data["workload"] != row["workload"]
        ]

        combined = pd.concat(
            [old_data, new_row],
            ignore_index=True
        )

    else:

        combined = new_row

    combined.to_csv(
        MASTER_DATASET,
        index=False
    )

    print()
    print("Master dataset saved to:")
    print(MASTER_DATASET)

    return combined

In [ ]:
# ============================================================
# TEST COMPLETE SYSTEM ON BFS
# ============================================================

workload = "bfs"

input_file = "graph1MW_6.txt"

row, cpu_times, gpu_results = benchmark_workload(
    workload=workload,
    cpu_input=f"../../data/{workload}/{input_file}",
    gpu_input=f"../../data/{workload}/{input_file}",
    input_size_mb=62,
    cpu_threads=4,
    n_runs=6
)

save_raw_results(
    workload,
    cpu_times,
    gpu_results
)

dataset = save_master_row(row)

print()
print("CURRENT MASTER DATASET")
display(dataset)

In [ ]:
# ============================================================
# SECTION 51 — INSPECT GAUSSIAN
# ============================================================

from pathlib import Path

workload = "gaussian"

cpu_dir = CPU_ROOT / workload
gpu_dir = GPU_ROOT / workload
data_dir = DATA_ROOT / workload

print("CPU directory:", cpu_dir)
print("GPU directory:", gpu_dir)
print("Data directory:", data_dir)

print("\n--- CPU files ---")
for p in sorted(cpu_dir.iterdir()):
    print(p.name)

print("\n--- GPU files ---")
for p in sorted(gpu_dir.iterdir()):
    print(p.name)

print("\n--- Data files ---")
for p in sorted(data_dir.iterdir()):
    print(f"{p.name:40s} {p.stat().st_size / (1024**2):.2f} MB")


# ============================================================
# SECTION 52 — GAUSSIAN CPU RUN SCRIPT
# ============================================================

cpu_run = CPU_ROOT / "gaussian" / "run"

if cpu_run.exists():
    print(cpu_run.read_text())
else:
    print("CPU run script not found.")


# ============================================================
# SECTION 53 — GAUSSIAN GPU RUN SCRIPT
# ============================================================

gpu_run = GPU_ROOT / "gaussian" / "run"

if gpu_run.exists():
    print(gpu_run.read_text())
else:
    print("GPU run script not found.")

# ============================================================
# SECTION 54 — GAUSSIAN CPU MAKEFILE
# ============================================================

makefile = CPU_ROOT / "gaussian" / "Makefile"

if makefile.exists():
    print(makefile.read_text())
else:
    print("CPU Makefile not found.")



# ============================================================
# SECTION 55 — GAUSSIAN CUDA MAKEFILE
# ============================================================

makefile = GPU_ROOT / "gaussian" / "Makefile"

if makefile.exists():
    print(makefile.read_text())
else:
    print("GPU Makefile not found.")


# ============================================================
# SECTION 56 — CHECK GAUSSIAN EXECUTABLES
# ============================================================

print("CPU executable:")
print((CPU_ROOT / "gaussian" / "gaussian").exists())

print("GPU executable:")
print((GPU_ROOT / "gaussian" / "gaussian").exists())

CPU directory: /kaggle/working/Rodinia/openmp/gaussian
GPU directory: /kaggle/working/Rodinia/cuda/gaussian
Data directory: /kaggle/working/Rodinia/data/gaussian

--- CPU files ---

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/working/Rodinia/openmp/gaussian'

In [ ]:
# ============================================================
# SECTION 51 — FIND WORKLOADS AVAILABLE ON BOTH CPU AND GPU
# ============================================================

from pathlib import Path

CPU_ROOT = Path("/kaggle/working/Rodinia/openmp")
GPU_ROOT = Path("/kaggle/working/Rodinia/cuda")
DATA_ROOT = Path("/kaggle/working/Rodinia/data")

cpu_workloads = {
    p.name for p in CPU_ROOT.iterdir()
    if p.is_dir()
}

gpu_workloads = {
    p.name for p in GPU_ROOT.iterdir()
    if p.is_dir()
}

common_workloads = sorted(cpu_workloads & gpu_workloads)

print("CPU/OpenMP workloads:")
print(sorted(cpu_workloads))

print("\nCUDA workloads:")
print(sorted(gpu_workloads))

print("\n==============================================")
print("WORKLOADS AVAILABLE ON BOTH CPU AND GPU")
print("==============================================")

for i, workload in enumerate(common_workloads, 1):
    print(f"{i:2d}. {workload}")

print(f"\nTotal common workloads: {len(common_workloads)}")

CPU/OpenMP workloads:
['b+tree', 'backprop', 'bfs', 'cfd', 'heartwall', 'hotspot', 'hotspot3D', 'kmeans', 'lavaMD', 'leukocyte', 'lud', 'mummergpu', 'myocyte', 'nn', 'nw', 'particlefilter', 'pathfinder', 'srad', 'streamcluster']

CUDA workloads:
['b+tree', 'backprop', 'bfs', 'cfd', 'dwt2d', 'gaussian', 'heartwall', 'hotspot', 'hotspot3D', 'huffman', 'hybridsort', 'kmeans', 'lavaMD', 'leukocyte', 'lud', 'mummergpu', 'myocyte', 'nn', 'nw', 'particlefilter', 'pathfinder', 'srad', 'streamcluster']

==============================================
WORKLOADS AVAILABLE ON BOTH CPU AND GPU
==============================================
 1. b+tree
 2. backprop
 3. bfs
 4. cfd
 5. heartwall
 6. hotspot
 7. hotspot3D
 8. kmeans
 9. lavaMD
10. leukocyte
11. lud
12. mummergpu
13. myocyte
14. nn
15. nw
16. particlefilter
17. pathfinder
18. srad
19. streamcluster

Total common workloads: 19

In [ ]:
# ============================================================
# SECTION 52 — CHECK COMMON WORKLOADS + DATA
# ============================================================

print("Workload availability check:\n")

for workload in common_workloads:

    data_dir = DATA_ROOT / workload

    if data_dir.exists():
        files = [p for p in data_dir.iterdir() if p.is_file()]

        print(f"✓ {workload:18s} | CPU ✓ | GPU ✓ | DATA ✓ | {len(files)} files")

    else:
        print(f"✗ {workload:18s} | CPU ✓ | GPU ✓ | DATA ✗")

Workload availability check:

✓ b+tree             | CPU ✓ | GPU ✓ | DATA ✓ | 2 files
✗ backprop           | CPU ✓ | GPU ✓ | DATA ✗
✓ bfs                | CPU ✓ | GPU ✓ | DATA ✓ | 3 files
✓ cfd                | CPU ✓ | GPU ✓ | DATA ✓ | 3 files
✓ heartwall          | CPU ✓ | GPU ✓ | DATA ✓ | 2 files
✓ hotspot            | CPU ✓ | GPU ✓ | DATA ✓ | 6 files
✓ hotspot3D          | CPU ✓ | GPU ✓ | DATA ✓ | 8 files
✓ kmeans             | CPU ✓ | GPU ✓ | DATA ✓ | 4 files
✗ lavaMD             | CPU ✓ | GPU ✓ | DATA ✗
✓ leukocyte          | CPU ✓ | GPU ✓ | DATA ✓ | 1 files
✓ lud                | CPU ✓ | GPU ✓ | DATA ✓ | 4 files
✓ mummergpu          | CPU ✓ | GPU ✓ | DATA ✓ | 5 files
✓ myocyte            | CPU ✓ | GPU ✓ | DATA ✓ | 2 files
✓ nn                 | CPU ✓ | GPU ✓ | DATA ✓ | 5 files
✗ nw                 | CPU ✓ | GPU ✓ | DATA ✗
✗ particlefilter     | CPU ✓ | GPU ✓ | DATA ✗
✗ pathfinder         | CPU ✓ | GPU ✓ | DATA ✗
✓ srad               | CPU ✓ | GPU ✓ | DATA ✓ | 1 files
✗ streamcluster      | CPU ✓ | GPU ✓ | DATA ✗

In [ ]:
# ============================================================
# SECTION 53 — INSPECT ALL VALID CPU/GPU WORKLOADS
# ============================================================

from pathlib import Path

VALID_WORKLOADS = [
    "b+tree",
    "bfs",
    "cfd",
    "heartwall",
    "hotspot",
    "hotspot3D",
    "kmeans",
    "leukocyte",
    "lud",
    "mummergpu",
    "myocyte",
    "nn",
    "srad"
]

print("=" * 80)
print("RODINIA WORKLOAD INSPECTION")
print("=" * 80)

for workload in VALID_WORKLOADS:

    cpu_dir = CPU_ROOT / workload
    gpu_dir = GPU_ROOT / workload
    data_dir = DATA_ROOT / workload

    print("\n" + "=" * 80)
    print(f"WORKLOAD: {workload}")
    print("=" * 80)

    # --------------------------------------------------------
    # CPU run script
    # --------------------------------------------------------
    cpu_run = cpu_dir / "run"

    print("\n[CPU/OpenMP]")

    if cpu_run.exists():
        print("Run script:")
        print("-" * 60)
        print(cpu_run.read_text(errors="ignore"))
    else:
        print("No run script found.")

    # --------------------------------------------------------
    # GPU run script
    # --------------------------------------------------------
    gpu_run = gpu_dir / "run"

    print("\n[GPU/CUDA]")

    if gpu_run.exists():
        print("Run script:")
        print("-" * 60)
        print(gpu_run.read_text(errors="ignore"))
    else:
        print("No run script found.")

    # --------------------------------------------------------
    # Data files
    # --------------------------------------------------------
    print("\n[DATA FILES]")

    if data_dir.exists():

        files = [
            p for p in sorted(data_dir.rglob("*"))
            if p.is_file()
        ]

        if files:
            for p in files:
                size_mb = p.stat().st_size / (1024 * 1024)
                print(f"{p.name:45s} {size_mb:10.3f} MB")
        else:
            print("No files found.")

    else:
        print("Data directory not found.")

    # --------------------------------------------------------
    # Executables
    # --------------------------------------------------------
    print("\n[EXECUTABLES]")

    cpu_exes = [
        p.name for p in cpu_dir.iterdir()
        if p.is_file() and p.stat().st_mode & 0o111
    ]

    gpu_exes = [
        p.name for p in gpu_dir.iterdir()
        if p.is_file() and p.stat().st_mode & 0o111
    ]

    print("CPU:", cpu_exes if cpu_exes else "None")
    print("GPU:", gpu_exes if gpu_exes else "None")

================================================================================
RODINIA WORKLOAD INSPECTION
================================================================================

================================================================================
WORKLOAD: b+tree
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
./b+tree.out core 2 file ../../data/b+tree/mil.txt command ../../data/b+tree/command.txt


[GPU/CUDA]
Run script:
------------------------------------------------------------
./b+tree.out file ../../data/b+tree/mil.txt command ../../data/b+tree/command.txt


[DATA FILES]
command.txt                                        0.000 MB
mil.txt                                            6.570 MB

[EXECUTABLES]
CPU: ['penmp', 'run', 'common.h', 'main.h']
GPU: ['penmp', 'run', 'Makefile', 'common.h', 'main.h']

================================================================================
WORKLOAD: bfs
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
./bfs 4 ../../data/bfs/graph1MW_6.txt

[GPU/CUDA]
Run script:
------------------------------------------------------------
./bfs ../../data/bfs/graph1MW_6.txt


[DATA FILES]
graph1MW_6.txt                                    61.225 MB
graph4096.txt                                      0.190 MB
graph65536.txt                                     3.694 MB
Makefile                                           0.000 MB
gen_dataset.sh                                     0.000 MB
graphgen.cpp                                       0.003 MB

[EXECUTABLES]
CPU: ['run', 'bfs', 'Makefile', 'bfs.cpp']
GPU: ['bfs.cu', 'Makefile_nvidia', 'bfs_kernel_timed', 'run', 'bfs_kernel_timed.cu', 'bfs_before_transfer_timing_v2.cu', 'README', 'kernel.cu', 'Makefile', 'bfs_original.cu', 'bfs_before_transfer_timing.cu', 'kernel2.cu']

================================================================================
WORKLOAD: cfd
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
./euler3d_cpu ../../data/cfd/fvcorr.domn.193K


[GPU/CUDA]
Run script:
------------------------------------------------------------
There are three datasets:

./euler3d ../../data/cfd/fvcorr.domn.097K
./euler3d ../../data/cfd/fvcorr.domn.193K
./euler3d ../../data/cfd/missile.domn.0.2M

replace euler3d with other CFD programs

[DATA FILES]
fvcorr.domn.097K                                  21.842 MB
fvcorr.domn.193K                                  43.545 MB
missile.domn.0.2M                                 52.336 MB

[EXECUTABLES]
CPU: ['euler3d_cpu_double.cpp', 'makefile', 'run', 'pre_euler3d_cpu_double.cpp', 'README', 'euler3d_cpu.cpp', 'pre_euler3d_cpu.cpp']
GPU: ['Makefile_nvidia', 'run', 'euler3d.cu', 'pre_euler3d_double.cu', 'README', 'euler3d_double.cu', 'pre_euler3d.cu', 'euler3d', 'Makefile']

================================================================================
WORKLOAD: heartwall
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
./heartwall ../../data/heartwall/test.avi 20 4


[GPU/CUDA]
Run script:
------------------------------------------------------------
./heartwall ../../data/heartwall/test.avi 20

[DATA FILES]
input.txt                                          0.000 MB
test.avi                                          48.411 MB

[EXECUTABLES]
CPU: ['makefile', 'run', 'main.c', 'kernel.c', 'define.c']
GPU: ['setdevice.cu', 'run', 'main.cu', 'kernel.cu', 'Makefile', 'define.c']

================================================================================
WORKLOAD: hotspot
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
./hotspot 1024 1024 2 4 ../../data/hotspot/temp_1024 ../../data/hotspot/power_1024 output.out


[GPU/CUDA]
Run script:
------------------------------------------------------------
./hotspot 512 2 2 ../../data/hotspot/temp_512 ../../data/hotspot/power_512 output.out


[DATA FILES]
1024_16384.h                                       0.000 MB
1024_2048.h                                        0.000 MB
1024_4096.h                                        0.000 MB
1024_8192.h                                        0.000 MB
64_128.h                                           0.000 MB
64_256.h                                           0.000 MB
Makefile                                           0.000 MB
README                                             0.001 MB
hotspotex.cpp                                      0.002 MB
hotspotver.cpp                                     0.002 MB
power_1024                                         9.000 MB
power_512                                          2.250 MB
power_64                                           0.035 MB
temp_1024                                         11.000 MB
temp_512                                           2.750 MB
temp_64                                            0.043 MB

[EXECUTABLES]
CPU: ['run', 'README', 'hotspot_openmp.cpp', 'Makefile']
GPU: ['Makefile_nvidia', 'run', 'Makefile', 'hotspot.cu']

================================================================================
WORKLOAD: hotspot3D
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
./3D 512 8 100 ../../data/hotspot3D/power_512x8 ../../data/hotspot3D/temp_512x8 output.out


[GPU/CUDA]
Run script:
------------------------------------------------------------
./3D 512 8 100 ../../data/hotspot3D/power_512x8 ../../data/hotspot3D/temp_512x8 output.out


[DATA FILES]
power_512x2                                        4.500 MB
power_512x4                                        9.000 MB
power_512x8                                       18.000 MB
power_64x8                                         0.281 MB
temp_512x2                                         5.500 MB
temp_512x4                                        11.000 MB
temp_512x8                                        22.000 MB
temp_64x8                                          0.344 MB

[EXECUTABLES]
CPU: ['run', '3D', '3D.c', 'Makefile']
GPU: ['run', '3D', '3D.cu', 'Makefile', 'opt1.cu']

================================================================================
WORKLOAD: kmeans
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
./kmeans_serial/kmeans -i ../../data/kmeans/kdd_cup
./kmeans_openmp/kmeans -n 4 -i ../../data/kmeans/kdd_cup

[GPU/CUDA]
Run script:
------------------------------------------------------------
./kmeans -o -i ../../data/kmeans/kdd_cup


[DATA FILES]
100                                                0.012 MB
204800.txt                                        24.086 MB
819200.txt                                        96.984 MB
Makefile                                           0.000 MB
datagen.cpp                                        0.002 MB
gen_dataset.sh                                     0.000 MB
kdd_cup                                           58.387 MB

[EXECUTABLES]
CPU: ['run', 'README', 'Makefile']
GPU: ['kmeans_cuda_kernel.cu', 'Makefile_nvidia', 'run', 'unistd.h', 'kmeans.c', 'Makefile~', 'README', 'getopt.h', 'Makefile', 'cluster.c', 'kmeans_cuda.cu', 'getopt.c', 'rmse.c', 'kmeans_clustering.c', 'kmeans.h']

================================================================================
WORKLOAD: leukocyte
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
./OpenMP/leukocyte 5 4 ../../data/leukocyte/testfile.avi

[GPU/CUDA]
Run script:
------------------------------------------------------------
./CUDA/leukocyte  ../../data/leukocyte/testfile.avi 5


[DATA FILES]
testfile.avi                                     175.799 MB

[EXECUTABLES]
CPU: ['run', 'Makefile']
GPU: ['run', 'Makefile']

================================================================================
WORKLOAD: lud
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
# ./omp/lud_omp -n 4 -i ../../data/lud/512.dat
./omp/lud_omp -s 8000


[GPU/CUDA]
Run script:
------------------------------------------------------------
# cuda/lud_cuda -i ../../data/lud/256.dat
cuda/lud_cuda -s 256 -v


[DATA FILES]
2048.dat                                          42.445 MB
256.dat                                            0.608 MB
512.dat                                            2.476 MB
64.dat                                             0.036 MB

[EXECUTABLES]
CPU: ['run', 'README', 'Makefile']
GPU: ['run', 'README', 'Makefile']

================================================================================
WORKLOAD: mummergpu
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
usage: mummergpu [options] reference.fna query.fna   (-C run CPU version)

To change the number of OMP threads, please change N_THREADS in mummergpu_gold.cpp


bin/mummergpu -C ../../data/mummergpu/NC_003997.fna ../../data/mummergpu/NC_003997_q100bp.fna > NC_00399.out

[GPU/CUDA]
Run script:
------------------------------------------------------------
usage: mummergpu [options] reference.fna query.fna

bin/mummergpu ../../data/mummergpu/NC_003997.fna ../../data/mummergpu/NC_003997_q100bp.fna > NC_00399.out

[DATA FILES]
NC_003997.20k.fna                                  1.354 MB
NC_003997.fna                                      5.056 MB
NC_003997_q100bp.fna                             268.353 MB
NC_003997_q25bp.50k.fna                            1.706 MB
genreads.py                                        0.002 MB

[EXECUTABLES]
CPU: ['run', 'NOTES', 'README', 'Makefile', 'COPYING']
GPU: ['run', 'README', 'Makefile', 'COPYING']

================================================================================
WORKLOAD: myocyte
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
./myocyte.out 100 1 0 4


[GPU/CUDA]
Run script:
------------------------------------------------------------
./myocyte.out 100 1 0


[DATA FILES]
params.txt                                         0.000 MB
y.txt                                              0.001 MB

[EXECUTABLES]
CPU: ['cam.c', 'fin.c', 'run', 'embedded_fehlberg_7_8.c', 'Makefile', 'ecc.c', 'master.c', 'define.c', 'file.c']
GPU: ['embedded_fehlberg_7_8_2.cu', 'kernel_fin.cu', 'kernel_cam_2.cu', 'kernel_ecc_2.cu', 'embedded_fehlberg_7_8.cu', 'run', 'kernel_cam.cu', 'kernel_fin_2.cu', 'kernel_2.cu', 'main.cu', 'kernel.cu', 'Makefile', 'define.c', 'master.cu', 'kernel_ecc.cu', 'file.c']

================================================================================
WORKLOAD: nn
================================================================================

[CPU/OpenMP]
Run script:
------------------------------------------------------------
./nn filelist_4 5 30 90

[GPU/CUDA]
Run script:
------------------------------------------------------------
./nn filelist_4 -r 5 -lat 30 -lng 90

[DATA FILES]
cane4_0.db                                         0.500 MB
cane4_1.db                                         0.500 MB
cane4_2.db                                         0.500 MB
cane4_3.db                                         0.500 MB
filelist.txt                                       0.000 MB
Makefile                                           0.000 MB
gen_dataset.sh                                     0.000 MB
gen_dataset_multifile.sh                           0.000 MB
hurricanegen.c                                     0.003 MB

[EXECUTABLES]
CPU: ['filelist_4', 'hurricane_gen', 'run', 'gen_dataset.sh', 'nn_openmp.c', 'nn', 'hurricane_gen.c', 'README', 'Makefile']
GPU: ['filelist_4', 'nn_cuda.cu', 'run', 'gen_dataset.sh', 'hurricane_gen.c', 'nn_pbs.sh', 'README', 'Makefile']

================================================================================
WORKLOAD: srad
================================================================================

[CPU/OpenMP]
No run script found.

[GPU/CUDA]
No run script found.

[DATA FILES]
image.pgm                                          0.753 MB

[EXECUTABLES]
CPU: ['Makefile']
GPU: ['README']

In [ ]:
# ============================================================
# SECTION 54 — COMPACT WORKLOAD SUMMARY
# ============================================================

print("=" * 100)
print(f"{'WORKLOAD':18s} {'CPU RUN':10s} {'GPU RUN':10s} {'DATA':10s} {'CPU EXE':15s} {'GPU EXE':15s}")
print("=" * 100)

for workload in VALID_WORKLOADS:

    cpu_dir = CPU_ROOT / workload
    gpu_dir = GPU_ROOT / workload
    data_dir = DATA_ROOT / workload

    cpu_run = (cpu_dir / "run").exists()
    gpu_run = (gpu_dir / "run").exists()
    data_exists = data_dir.exists()

    cpu_exes = [
        p.name for p in cpu_dir.iterdir()
        if p.is_file() and p.stat().st_mode & 0o111
    ]

    gpu_exes = [
        p.name for p in gpu_dir.iterdir()
        if p.is_file() and p.stat().st_mode & 0o111
    ]

    cpu_exe = cpu_exes[0] if cpu_exes else "-"
    gpu_exe = gpu_exes[0] if gpu_exes else "-"

    print(
        f"{workload:18s} "
        f"{'✓' if cpu_run else '✗':10s} "
        f"{'✓' if gpu_run else '✗':10s} "
        f"{'✓' if data_exists else '✗':10s} "
        f"{cpu_exe:15s} "
        f"{gpu_exe:15s}"
    )

====================================================================================================
WORKLOAD           CPU RUN    GPU RUN    DATA       CPU EXE         GPU EXE
====================================================================================================
b+tree             ✓          ✓          ✓          penmp           penmp
bfs                ✓          ✓          ✓          run             bfs.cu
cfd                ✓          ✓          ✓          euler3d_cpu_double.cpp Makefile_nvidia
heartwall          ✓          ✓          ✓          makefile        setdevice.cu
hotspot            ✓          ✓          ✓          run             Makefile_nvidia
hotspot3D          ✓          ✓          ✓          run             run
kmeans             ✓          ✓          ✓          run             kmeans_cuda_kernel.cu
leukocyte          ✓          ✓          ✓          run             run
lud                ✓          ✓          ✓          run             run
mummergpu          ✓          ✓          ✓          run             run
myocyte            ✓          ✓          ✓          cam.c           embedded_fehlberg_7_8_2.cu
nn                 ✓          ✓          ✓          filelist_4      filelist_4
srad               ✗          ✗          ✓          Makefile        README

In [ ]:
# ============================================================
# SECTION 55 — FIND TIMING CODE FOR ALL VALID WORKLOADS
# ============================================================

import re
from pathlib import Path

VALID_WORKLOADS = [
    "b+tree",
    "cfd",
    "heartwall",
    "hotspot",
    "hotspot3D",
    "kmeans",
    "leukocyte",
    "lud",
    "mummergpu",
    "myocyte",
    "nn"
]

TIMING_PATTERNS = [
    r"gettimeofday",
    r"getrusage",
    r"clock_gettime",
    r"omp_get_wtime",
    r"cudaEvent",
    r"cudaThreadSynchronize",
    r"cudaDeviceSynchronize",
    r"Start time",
    r"End time",
    r"Compute time",
    r"Execution time",
    r"Time",
    r"time",
    r"timer",
    r"Timer"
]

SOURCE_EXTENSIONS = {
    ".c",
    ".cc",
    ".cpp",
    ".cu",
    ".h",
    ".hpp"
}

for workload in VALID_WORKLOADS:

    print("\n" + "=" * 90)
    print(f"WORKLOAD: {workload}")
    print("=" * 90)

    for implementation, root in [
        ("CPU/OpenMP", CPU_ROOT / workload),
        ("GPU/CUDA", GPU_ROOT / workload)
    ]:

        print(f"\n--- {implementation} ---")

        matches_found = False

        if not root.exists():
            print("Directory not found.")
            continue

        source_files = [
            p for p in root.rglob("*")
            if p.is_file() and p.suffix.lower() in SOURCE_EXTENSIONS
        ]

        for source in sorted(source_files):

            try:
                text_content = source.read_text(
                    errors="ignore"
                )
            except Exception:
                continue

            lines = text_content.splitlines()

            matching_lines = []

            for line_no, line in enumerate(lines, start=1):

                line_lower = line.lower()

                if any(
                    re.search(pattern, line_lower)
                    for pattern in TIMING_PATTERNS
                ):
                    matching_lines.append(
                        (line_no, line.strip())
                    )

            if matching_lines:

                matches_found = True

                print(f"\nFile: {source.name}")

                # Show maximum 12 useful timing-related lines
                for line_no, line in matching_lines[:12]:
                    print(f"  {line_no:4d}: {line}")

        if not matches_found:
            print("No obvious timing code found.")

==========================================================================================
WORKLOAD: b+tree
==========================================================================================

--- CPU/OpenMP ---

File: kernel_cpu.c
    27: #include "../util/timer/timer.h"					// (in directory provided here)
    54: // timer
    55: long long time0;
    56: long long time1;
    57: long long time2;
    59: time0 = get_time();
    74: time1 = get_time();
   125: time2 = get_time();
   131: printf("Time spent in different stages of CPU/MCPU KERNEL:\n");
   133: printf("%15.12f s, %15.12f % : MCPU: SET DEVICE\n",					(float) (time1-time0) / 1000000, (float) (time1-time0) / (float) (time2-time0) * 100);
   134: printf("%15.12f s, %15.12f % : CPU/MCPU: KERNEL\n",					(float) (time2-time1) / 1000000, (float) (time2-time1) / (float) (time2-time0) * 100);
   136: printf("Total time:\n");

File: kernel_cpu_2.c
    26: #include "../util/timer/timer.h"					// (in directory provided here)	needed by timer
    62: // timer
    63: long long time0;
    64: long long time1;
    65: long long time2;
    70: time0 = get_time();
    85: time1 = get_time();
   152: time2 = get_time();
   158: printf("Time spent in different stages of CPU/MCPU KERNEL:\n");
   160: printf("%15.12f s, %15.12f % : MCPU: SET DEVICE\n",					(float) (time1-time0) / 1000000, (float) (time1-time0) / (float) (time2-time0) * 100);
   161: printf("%15.12f s, %15.12f % : CPU/MCPU: KERNEL\n",					(float) (time2-time1) / 1000000, (float) (time2-time1) / (float) (time2-time0) * 100);
   163: printf("Total time:\n");

File: main.c
    62: // #include <sys/time.h>							// (in directory known to compiler)			needed by ???
    80: #include "./util/timer/timer.h"						// (in directory provided here)
   650: struct timeval one,two;
   651: double time;
   652: gettimeofday (&one, NULL);
   741: gettimeofday (&two, NULL);
   744: time = twoD-oneD;
   745: printf("Tree transformation took %f\n", time);
  1533: * Nonleaf nodes may sometimes need to remain split,
  1537: * and only sometimes set to true for nonleaf nodes.

File: timer.c
     6: //	TIMER CODE
    20: //	DISPLAY TIME
    23: // Returns the current system time in microseconds
    24: long long get_time() {
    25: struct timeval tv;
    26: gettimeofday(&tv, NULL);
    31: //	END TIMER CODE

File: timer.h
     6: //	TIMER HEADER
    14: get_time();
    17: //	END TIMER HEADER

--- GPU/CUDA ---

File: kernel_gpu_cuda_wrapper.cu
    20: #include "../util/timer/timer.h"					// (in path specified to compiler)	needed by timer
    59: // timer
    60: long long time0;
    61: long long time1;
    62: long long time2;
    63: long long time3;
    64: long long time4;
    65: long long time5;
    66: long long time6;
    68: time0 = get_time();
    91: time1 = get_time();
   153: time2 = get_time();

File: kernel_gpu_cuda_wrapper_2.cu
    20: #include "../util/timer/timer.h"						// (in library path specified to compiler)	needed by timer
    61: // timer
    62: long long time0;
    63: long long time1;
    64: long long time2;
    65: long long time3;
    66: long long time4;
    67: long long time5;
    68: long long time6;
    70: time0 = get_time();
    93: time1 = get_time();
   179: time2 = get_time();

File: main.c
    62: // #include <sys/time.h>							// (in directory known to compiler)			needed by ???
    80: #include "./util/timer/timer.h"						// (in directory provided here)
   650: struct timeval one,two;
   651: double time;
   652: gettimeofday (&one, NULL);
   741: gettimeofday (&two, NULL);
   744: time = twoD-oneD;
   745: printf("Tree transformation took %f\n", time);
  1533: * Nonleaf nodes may sometimes need to remain split,
  1537: * and only sometimes set to true for nonleaf nodes.

File: timer.c
     6: //	TIMER CODE
    20: //	DISPLAY TIME
    23: // Returns the current system time in microseconds
    24: long long get_time() {
    25: struct timeval tv;
    26: gettimeofday(&tv, NULL);
    31: //	END TIMER CODE

File: timer.h
     6: //	TIMER HEADER
    14: get_time();
    17: //	END TIMER HEADER

==========================================================================================
WORKLOAD: cfd
==========================================================================================

--- CPU/OpenMP ---

File: euler3d_cpu.cpp
   195: // dt = float(0.5f) * std::sqrt(areas[i]) /  (||v|| + c).... but when we do time stepping, this later would need to be divided by the area, so we just do it all at once
   345: void time_step(int j, int nelr, float* old_variables, float* variables, float* step_factors, float* fluxes)
   469: // these need to be computed the first time in order to compute time step
   472: double start = omp_get_wtime();
   482: // for the first iteration we compute the time step
   488: time_step(j, nelr, old_variables, variables, step_factors, fluxes);
   493: double end = omp_get_wtime();
   494: std::cout  << "Compute time: " << (end-start) << std::endl;

File: euler3d_cpu_double.cpp
   174: // dt = double(0.5) * std::sqrt(areas[i]) /  (||v|| + c).... but when we do time stepping, this later would need to be divided by the area, so we just do it all at once
   318: void time_step(int j, int nelr, double* old_variables, double* variables, double* step_factors, double* fluxes)
   428: // these need to be computed the first time in order to compute time step
   430: double start = omp_get_wtime();
   437: // for the first iteration we compute the time step
   443: time_step(j, nelr, old_variables, variables, step_factors, fluxes);
   447: double end = omp_get_wtime();

File: pre_euler3d_cpu.cpp
   174: // dt = float(0.5f) * std::sqrt(areas[i]) /  (||v|| + c).... but when we do time stepping, this later would need to be divided by the area, so we just do it all at once
   386: void time_step(int j, int nelr, float* old_variables, float* variables, float* step_factors, float* fluxes)
   501: // these need to be computed the first time in order to compute time step
   503: double start = omp_get_wtime();
   510: // for the first iteration we compute the time step
   517: time_step(j, nelr, old_variables, variables, step_factors, fluxes);
   521: double end = omp_get_wtime();

File: pre_euler3d_cpu_double.cpp
   175: // dt = double(0.5) * std::sqrt(areas[i]) /  (||v|| + c).... but when we do time stepping, this later would need to be divided by the area, so we just do it all at once
   389: void time_step(int j, int nelr, double* old_variables, double* variables, double* step_factors, double* fluxes)
   503: // these need to be computed the first time in order to compute time step
   505: double start = omp_get_wtime();
   512: // for the first iteration we compute the time step
   519: time_step(j, nelr, old_variables, variables, step_factors, fluxes);
   523: double end = omp_get_wtime();

--- GPU/CUDA ---

File: euler3d.cu
     6: #include <helper_timer.h>
   246: // dt = float(0.5f) * sqrtf(areas[i]) /  (||v|| + c).... but when we do time stepping, this later would need to be divided by the area, so we just do it all at once
   397: __global__ void cuda_time_step(int j, int nelr, float* old_variables, float* variables, float* step_factors, float* fluxes)
   409: void time_step(int j, int nelr, float* old_variables, float* variables, float* step_factors, float* fluxes)
   412: cuda_time_step<<<Dg,Db>>>(j, nelr, old_variables, variables, step_factors, fluxes);
   421: printf("WG size of kernel:initialize = %d, WG size of kernel:compute_step_factor = %d, WG size of kernel:compute_flux = %d, WG size of kernel:time_step = %d\n", BLOCK_SIZE_1, BLOCK_SIZE_2, BLOCK_SIZE_3, BLOCK_SIZE_4);
   557: // these need to be computed the first time in order to compute time step
   560: StopWatchInterface *timer = 0;
   561: //	unsigned int timer = 0;
   563: // CUT_SAFE_CALL( cutCreateTimer( &timer));
   564: // CUT_SAFE_CALL( cutStartTimer( timer));
   565: sdkCreateTimer(&timer);

File: euler3d_double.cu
     6: #include <helper_timer.h>
   203: // dt = double(0.5) * sqrt(areas[i]) /  (||v|| + c).... but when we do time stepping, this later would need to be divided by the area, so we just do it all at once
   366: __global__ void cuda_time_step(int j, int nelr, double* old_variables, double* variables, double* step_factors, double* fluxes)
   378: void time_step(int j, int nelr, double* old_variables, double* variables, double* step_factors, double* fluxes)
   381: cuda_time_step<<<Dg,Db>>>(j, nelr, old_variables, variables, step_factors, fluxes);
   535: // these need to be computed the first time in order to compute time step
   539: StopWatchInterface *timer = NULL;
   541: sdkCreateTimer( &timer);
   542: sdkStartTimer( &timer);
   549: // for the first iteration we compute the time step
   569: time_step(j, nelr, old_variables, variables, step_factors, fluxes);
   573: fprintf(stderr,"GPUassert: %s time_step failed\n", cudaGetErrorString(error));

File: pre_euler3d.cu
     6: #include <helper_timer.h>
   201: // dt = float(0.5f) * sqrtf(areas[i]) /  (||v|| + c).... but when we do time stepping, this later would need to be divided by the area, so we just do it all at once
   445: __global__ void cuda_time_step(int j, int nelr, float* old_variables, float* variables, float* step_factors, float* fluxes)
   457: void time_step(int j, int nelr, float* old_variables, float* variables, float* step_factors, float* fluxes)
   461: cuda_time_step<<<Dg,Db>>>(j, nelr, old_variables, variables, step_factors, fluxes);
   615: // these need to be computed the first time in order to compute time step
   618: StopWatchInterface *timer = NULL;
   619: sdkCreateTimer(&timer);
   620: sdkStartTimer(&timer);
   628: // for the first iteration we compute the time step
   656: time_step(j, nelr, old_variables, variables, step_factors, fluxes);
   660: fprintf(stderr,"GPUassert: %s time_step\n", cudaGetErrorString(error));

File: pre_euler3d_double.cu
     5: #include <helper_timer.h>
   205: // dt = double(0.5) * sqrt(areas[i]) /  (||v|| + c).... but when we do time stepping, this later would need to be divided by the area, so we just do it all at once
   456: __global__ void cuda_time_step(int j, int nelr, double* old_variables, double* variables, double* step_factors, double* fluxes)
   468: void time_step(int j, int nelr, double* old_variables, double* variables, double* step_factors, double* fluxes)
   472: cuda_time_step<<<Dg,Db>>>(j, nelr, old_variables, variables, step_factors, fluxes);
   627: // these need to be computed the first time in order to compute time step
   630: StopWatchInterface *timer = NULL;
   631: sdkCreateTimer( &timer);
   632: sdkStartTimer( &timer);
   639: // for the first iteration we compute the time step
   646: time_step(j, nelr, old_variables, variables, step_factors, fluxes);
   651: sdkStopTimer(&timer);

==========================================================================================
WORKLOAD: heartwall
==========================================================================================

--- CPU/OpenMP ---

File: avilib.c
    33: //#include <time.h>
   235: /* Since Linux needs a long time when deleting big files,
   403: OUTLONG(0);                  /* TimeScale:  Unit used to measure time */
   405: OUTLONG(0);                  /* StartTime:  Starting time of AVI data */
   589: //   time_t calptr;
   675: OUTLONG(0);                  /* TimeScale:  Unit used to measure time */
   677: OUTLONG(0);                  /* StartTime:  Starting time of AVI data */
   829: //   calptr=time(NULL);
   830: //   sprintf(id_str, "\t%s %s", ctime(&calptr), "");

File: main.c
    10: #include <time.h>

--- GPU/CUDA ---

File: avilib.c
    33: //#include <time.h>
   235: /* Since Linux needs a long time when deleting big files,
   403: OUTLONG(0);                  /* TimeScale:  Unit used to measure time */
   405: OUTLONG(0);                  /* StartTime:  Starting time of AVI data */
   589: //   time_t calptr;
   675: OUTLONG(0);                  /* TimeScale:  Unit used to measure time */
   677: OUTLONG(0);                  /* StartTime:  Starting time of AVI data */
   829: //   calptr=time(NULL);
   830: //   sprintf(id_str, "\t%s %s", ctime(&calptr), "");

File: kernel.cu
  1296: // time19 = clock();

==========================================================================================
WORKLOAD: hotspot
==========================================================================================

--- CPU/OpenMP ---

File: hotspot_openmp.cpp
     4: #include <sys/time.h>
     6: // Returns the current system time in microseconds
     7: long long get_time()
     9: struct timeval tv;
    10: gettimeofday(&tv, NULL);
    52: * by one time step
   264: fprintf(stderr, "Usage: %s <grid_rows> <grid_cols> <sim_time> <no. of threads><temp_file> <power_file>\n", argv[0]);
   267: fprintf(stderr, "\t<sim_time>   - number of iterations\n");
   277: int grid_rows, grid_cols, sim_time, i;
   286: (sim_time = atoi(argv[3])) <= 0 ||
   308: long long start_time = get_time();
   310: compute_tran_temp(result,sim_time, temp, power, grid_rows, grid_cols);

--- GPU/CUDA ---

File: hotspot.cu
     3: #include <time.h>
    36: /* define timer macros */
    39: #define pin_stats_dump(cycles)    printf("timer: %Lu\n", cycles)
   117: float time_elapsed){
   218: compute N time steps
   238: float time_elapsed;
   239: time_elapsed=0.001;
   248: col,row,borderCols, borderRows, Cap,Rx,Ry,Rz,step,time_elapsed);
   255: fprintf(stderr, "Usage: %s <grid_rows/grid_cols> <pyramid_height> <sim_time> <temp_file> <power_file> <output_file>\n", argv[0]);
   258: fprintf(stderr, "\t<sim_time>   - number of iterations\n");

==========================================================================================
WORKLOAD: hotspot3D
==========================================================================================

--- CPU/OpenMP ---

File: 3D.c
     2: #include <time.h>
     6: #include <sys/time.h>
   255: struct timeval start, stop;
   256: float time;
   257: gettimeofday(&start,NULL);
   259: gettimeofday(&stop,NULL);
   260: time = (stop.tv_usec-start.tv_usec)*1.0e-6 + stop.tv_sec - start.tv_sec;
   264: printf("Time: %.3f (s)\n",time);

--- GPU/CUDA ---

File: 3D.cu
     2: #include <time.h>
     6: #include <sys/time.h>

File: opt1.cu
     1: long long get_time() {
     2: struct timeval tv;
     3: gettimeofday(&tv, NULL);
    84: long long start = get_time();
    93: long long stop = get_time();
    94: float time = (float)((stop - start)/(1000.0 * 1000.0));
    95: printf("Time: %.3f (s)\n",time);

==========================================================================================
WORKLOAD: kmeans
==========================================================================================

--- CPU/OpenMP ---

File: kmeans.c
    83: extern double wtime(void);
   207: timing = omp_get_wtime();
   220: timing = omp_get_wtime() - timing;
   236: printf("Time for process: %f\n", timing);

File: kmeans_clustering.c
    75: extern double wtime(void);

File: unistd.h
   215: #define _XOPEN_REALTIME		(-1)
   216: #define _XOPEN_REALTIME_THREADS	(-1)
   253: #define _POSIX_CPUTIME         200112L
   263: #define _POSIX_THREAD_CPUTIME  200112L
   265: #define _POSIX_TIMEOUTS	200112L
   327: /* Realtime threads options for 1003.1c and XPG UNIX98 */
   334: /* Realtime options for 1003.1c and XPG UNIX98 */
   344: #define _POSIX_REALTIME_SIGNALS			200112L
   348: #define _POSIX_TIMERS				200112L
   629: #define _SC_DELAYTIMER_MAX			79
   643: #define _SC_REALTIME_SIGNALS			93
   652: #define _SC_TIMERS				102

File: kmeans.c
    82: extern double wtime(void);
   204: timing = omp_get_wtime();
   218: timing = omp_get_wtime() - timing;
   232: printf("Time for process: %f\n", timing);

File: kmeans_clustering.c
    75: extern double wtime(void);

File: unistd.h
   215: #define _XOPEN_REALTIME		(-1)
   216: #define _XOPEN_REALTIME_THREADS	(-1)
   253: #define _POSIX_CPUTIME         200112L
   263: #define _POSIX_THREAD_CPUTIME  200112L
   265: #define _POSIX_TIMEOUTS	200112L
   327: /* Realtime threads options for 1003.1c and XPG UNIX98 */
   334: /* Realtime options for 1003.1c and XPG UNIX98 */
   344: #define _POSIX_REALTIME_SIGNALS			200112L
   348: #define _POSIX_TIMERS				200112L
   629: #define _SC_DELAYTIMER_MAX			79
   643: #define _SC_REALTIME_SIGNALS			93
   652: #define _SC_TIMERS				102

--- GPU/CUDA ---

File: cluster.c
    78: extern double wtime(void);
   113: /* iterate nloops times for each number of clusters */

File: kmeans.c
    82: extern double wtime(void);
   160: //io_timing = omp_get_wtime();
   216: //io_timing = omp_get_wtime() - io_timing;
   236: //cluster_timing = omp_get_wtime();		/* Total clustering time */
   250: //cluster_timing = omp_get_wtime() - cluster_timing;
   271: //printf("Time for I/O: %.5fsec\n", io_timing);
   272: //printf("Time for Entire Clustering: %.5fsec\n", cluster_timing);
   276: //printf("Average Clustering Time: %fsec\n",
   281: //printf("Average Clustering Time: %fsec\n",
   288: //printf("Average Clustering Time: %.5fsec\n",

File: kmeans_clustering.c
    74: extern double wtime(void);
   171: printf("iterated %d times\n", c);

File: kmeans_cuda_kernel.cu
     9: // FIXME: Make this a runtime selectable variable!

File: rmse.c
    21: extern double wtime(void);

File: unistd.h
   215: #define _XOPEN_REALTIME		(-1)
   216: #define _XOPEN_REALTIME_THREADS	(-1)
   253: #define _POSIX_CPUTIME         200112L
   263: #define _POSIX_THREAD_CPUTIME  200112L
   265: #define _POSIX_TIMEOUTS	200112L
   327: /* Realtime threads options for 1003.1c and XPG UNIX98 */
   334: /* Realtime options for 1003.1c and XPG UNIX98 */
   344: #define _POSIX_REALTIME_SIGNALS			200112L
   348: #define _POSIX_TIMERS				200112L
   629: #define _SC_DELAYTIMER_MAX			79
   643: #define _SC_REALTIME_SIGNALS			93
   652: #define _SC_TIMERS				102

==========================================================================================
WORKLOAD: leukocyte
==========================================================================================

--- CPU/OpenMP ---

File: avilib.c
    29: //#include <time.h>
   231: /* Since Linux needs a long time when deleting big files,
   399: OUTLONG(0);                  /* TimeScale:  Unit used to measure time */
   401: OUTLONG(0);                  /* StartTime:  Starting time of AVI data */
   585: //   time_t calptr;
   671: OUTLONG(0);                  /* TimeScale:  Unit used to measure time */
   673: OUTLONG(0);                  /* StartTime:  Starting time of AVI data */
   825: //   calptr=time(NULL);
   826: //   sprintf(id_str, "\t%s %s", ctime(&calptr), "");

File: detect_main.c
     8: // Keep track of the start time of the program
     9: long long program_start_time = get_time();
    50: long long GICOV_start_time = get_time();
    62: long long GICOV_end_time = get_time();
    65: long long dilate_start_time = get_time();
    68: long long dilate_end_time = get_time();
   102: // Make an array t which holds each "time step" for the possible cells
   243: // Report the breakdown of the detection runtime
   244: printf("Detection runtime\n");
   246: printf("GICOV computation: %.5f seconds\n", ((float) (GICOV_end_time - GICOV_start_time)) / (1000*1000));
   247: printf("   GICOV dilation: %.5f seconds\n", ((float) (dilate_end_time - dilate_start_time)) / (1000*1000));
   248: printf("            Total: %.5f seconds\n", ((float) (get_time() - program_start_time)) / (1000*1000));

File: find_ellipse.c
     2: #include <sys/time.h>
    19: // Returns the current system time in microseconds
    20: long long get_time() {
    21: struct timeval tv;
    22: gettimeofday(&tv, NULL);

File: find_ellipse.h
    20: extern long long get_time();

File: track_ellipse.c
    56: // Keep track of the total time spent on computing
    58: long long  MGVF_time = 0;
    59: long long snake_time = 0;

In [ ]:
# ============================================================
# SECTION 56 — SHOW MAKEFILES FOR VALID WORKLOADS
# ============================================================

for workload in VALID_WORKLOADS:

    print("\n" + "=" * 90)
    print(f"WORKLOAD: {workload}")
    print("=" * 90)

    for implementation, root in [
        ("CPU/OpenMP", CPU_ROOT / workload),
        ("GPU/CUDA", GPU_ROOT / workload)
    ]:

        print(f"\n--- {implementation} ---")

        makefiles = [
            p for p in root.iterdir()
            if p.is_file()
            and (
                p.name.lower() == "makefile"
                or p.name.lower() == "makefile_nvidia"
                or p.name.lower() == "makefile_nvidia"
            )
        ]

        if not makefiles:
            print("No Makefile found.")
            continue

        for makefile in makefiles:

            print(f"\n### {makefile.name}")

            text_content = makefile.read_text(
                errors="ignore"
            )

            # Print only useful compiler/build lines
            for line in text_content.splitlines():

                stripped = line.strip()

                if (
                    stripped.startswith("CC")
                    or stripped.startswith("CXX")
                    or stripped.startswith("NVCC")
                    or "gcc" in stripped
                    or "g++" in stripped
                    or "nvcc" in stripped
                    or stripped.startswith("all:")
                ):
                    print(stripped)

==========================================================================================
WORKLOAD: b+tree
==========================================================================================

--- CPU/OpenMP ---

### Makefile
C_C = gcc

--- GPU/CUDA ---

### Makefile
C_C = gcc
CUD_C = nvcc
# C_C = pgcc

==========================================================================================
WORKLOAD: cfd
==========================================================================================

--- CPU/OpenMP ---

### makefile
all: euler3d_cpu euler3d_cpu_double pre_euler3d_cpu pre_euler3d_cpu_double euler3d_cpu_offload
#	nvcc -Xptxas -v -O3 --gpu-architecture=compute_13 --gpu-code=compute_13 euler3d.cu -o euler3d -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib  -lcutil
#	nvcc -Xptxas -v -O3 --gpu-architecture=compute_13 --gpu-code=compute_13 euler3d_double.cu -o euler3d_double -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib  -lcutil
g++ -O3 -Dblock_length=$(OMP_NUM_THREADS) -fopenmp euler3d_cpu.cpp -o euler3d_cpu
g++ -O3 -Dblock_length=$(OMP_NUM_THREADS) -fopenmp euler3d_cpu_double.cpp -o euler3d_cpu_double
#	nvcc -Xptxas -v -O3 --gpu-architecture=compute_13 --gpu-code=compute_13 pre_euler3d.cu -o pre_euler3d -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib  -lcutil
#	nvcc -Xptxas -v -O3 --gpu-architecture=compute_13 --gpu-code=compute_13 pre_euler3d_double.cu -o pre_euler3d_double -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib  -lcutil
g++ -O3 -Dblock_length=$(OMP_NUM_THREADS) -fopenmp pre_euler3d_cpu.cpp -o pre_euler3d_cpu
g++ -O3 -Dblock_length=$(OMP_NUM_THREADS) -fopenmp pre_euler3d_cpu_double.cpp -o pre_euler3d_cpu_double

--- GPU/CUDA ---

### Makefile_nvidia

### Makefile
all: euler3d euler3d_double  pre_euler3d  pre_euler3d_double
nvcc $(KERNEL_DIM) -O2 -Xptxas -v --gpu-architecture=compute_20 --gpu-code=compute_20 euler3d.cu -o euler3d -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib $(CUTIL_LIB)
nvcc -Xptxas -v -O3 --gpu-architecture=compute_20 --gpu-code=compute_20 euler3d_double.cu -o euler3d_double -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib $(CUTIL_LIB)
nvcc -Xptxas -v -O3 --gpu-architecture=compute_20 --gpu-code=compute_20 pre_euler3d.cu -o pre_euler3d -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib $(CUTIL_LIB)
nvcc -Xptxas -v -O3 --gpu-architecture=compute_20 --gpu-code=compute_20 pre_euler3d_double.cu -o pre_euler3d_double -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib $(CUTIL_LIB)

==========================================================================================
WORKLOAD: heartwall
==========================================================================================

--- CPU/OpenMP ---

### makefile
gcc main.o ./AVI/avilib.o ./AVI/avimod.o -lm -fopenmp -o heartwall
gcc $(OUTPUT) main.c -I./AVI -c -O3 -fopenmp

--- GPU/CUDA ---

### Makefile
nvcc main.o ./AVI/avilib.o ./AVI/avimod.o -I/usr/local/cuda/include -lm -o heartwall
nvcc $(OUTPUT) $(KERNEL_DIM) main.cu -I./AVI -c -O3

==========================================================================================
WORKLOAD: hotspot
==========================================================================================

--- CPU/OpenMP ---

### Makefile
CC = g++
CC_FLAGS = -g -fopenmp -O2
all: hotspot hotspot_offload

--- GPU/CUDA ---

### Makefile_nvidia
# C/C++ source files (compiled with gcc / c++)

### Makefile
CC := $(CUDA_DIR)/bin/nvcc

==========================================================================================
WORKLOAD: hotspot3D
==========================================================================================

--- CPU/OpenMP ---

### Makefile
CC = gcc
CCFLAGS = -g -fopenmp -O3

--- GPU/CUDA ---

### Makefile
CC := $(CUDA_DIR)/bin/nvcc

==========================================================================================
WORKLOAD: kmeans
==========================================================================================

--- CPU/OpenMP ---

### Makefile
all: OPENMP/kmeans SERIAL/kmeans

--- GPU/CUDA ---

### Makefile_nvidia
# C/C++ source files (compiled with gcc / c++)

### Makefile
CC = gcc
CC_FLAGS = -g -fopenmp -O2
NVCC = $(CUDA_DIR)/bin/nvcc
NVCC_FLAGS = -I$(CUDA_DIR)/include
NVCC_FLAGS += -g -O0
NVCC_FLAGS += -O2
NVCC_FLAGS += -deviceemu

==========================================================================================
WORKLOAD: leukocyte
==========================================================================================

--- CPU/OpenMP ---

### Makefile
all: OpenMP/leukocyte

--- GPU/CUDA ---

### Makefile
all: CUDA/leukocyte

==========================================================================================
WORKLOAD: lud
==========================================================================================

--- CPU/OpenMP ---

### Makefile
all: lud_omp lud_omp_offload

--- GPU/CUDA ---

### Makefile
all: lud_cuda

==========================================================================================
WORKLOAD: mummergpu
==========================================================================================

--- CPU/OpenMP ---

### Makefile
all: mummer

--- GPU/CUDA ---

### Makefile
all: mummer

==========================================================================================
WORKLOAD: myocyte
==========================================================================================

--- CPU/OpenMP ---

### Makefile
gcc	main.o \
gcc	main.c \

--- GPU/CUDA ---

### Makefile
nvcc	main.o \
nvcc	main.cu \

==========================================================================================
WORKLOAD: nn
==========================================================================================

--- CPU/OpenMP ---

### Makefile
LOCAL_CC = gcc -g -O3 -Wall
CC = gcc

--- GPU/CUDA ---

### Makefile
LOCAL_CC = gcc -g -O3 -Wall
CC := $(CUDA_DIR)/bin/nvcc

In [ ]:
# ============================================================
# SECTION 57 — RODINIA WORKLOAD CONFIGURATION
# ============================================================

from pathlib import Path
import subprocess
import time
import re
import csv
import json
import statistics
import math
import os

# ------------------------------------------------------------
# ROOT DIRECTORIES
# ------------------------------------------------------------

RODINIA_ROOT = Path("/kaggle/working/Rodinia")

CPU_ROOT = RODINIA_ROOT / "openmp"
GPU_ROOT = RODINIA_ROOT / "cuda"
DATA_ROOT = RODINIA_ROOT / "data"

# ------------------------------------------------------------
# BENCHMARK SETTINGS
# ------------------------------------------------------------

N_RUNS = 6

MASTER_DATASET = Path(
    "/kaggle/working/rodinia_cpu_gpu_dataset.csv"
)

RAW_DATASET = Path(
    "/kaggle/working/rodinia_raw_benchmark_results.csv"
)

# ------------------------------------------------------------
# WORKLOAD CONFIGURATION
#
# IMPORTANT:
# These commands are taken from the actual Rodinia run scripts
# inspected in your environment.
# ------------------------------------------------------------

WORKLOAD_CONFIG = {

    # ========================================================
    # B+TREE
    # ========================================================

    "b+tree": {
        "cpu": {
            "cwd": CPU_ROOT / "b+tree",
            "command": (
                "./b+tree.out core 2 "
                "file ../../data/b+tree/mil.txt "
                "command ../../data/b+tree/command.txt"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)",
                r"Time:\s*([0-9.]+)"
            ]
        },

        "gpu": {
            "cwd": GPU_ROOT / "b+tree",
            "command": (
                "./b+tree.out "
                "file ../../data/b+tree/mil.txt "
                "command ../../data/b+tree/command.txt"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms",
                r"Execution time:\s*([0-9.]+)\s*ms",
                r"Time:\s*([0-9.]+)\s*ms"
            ]
        },

        "input_files": [
            DATA_ROOT / "b+tree" / "mil.txt"
        ]
    },


    # ========================================================
    # BFS
    # ========================================================

    "bfs": {
        "cpu": {
            "cwd": CPU_ROOT / "bfs",
            "command": (
                "./bfs 4 "
                "../../data/bfs/graph1MW_6.txt"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)"
            ],
            "time_unit": "seconds"
        },

        "gpu": {
            "cwd": GPU_ROOT / "bfs",
            "command": (
                "./bfs "
                "../../data/bfs/graph1MW_6.txt"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms"
            ],
            "h2d_regex": [
                r"Initial Host to Device Time:\s*([0-9.]+)\s*ms"
            ],
            "d2h_regex": [
                r"Final Device to Host Time:\s*([0-9.]+)\s*ms"
            ],
            "iterations_regex": [
                r"Kernel Executed\s+([0-9]+)\s+times"
            ],
            "time_unit": "milliseconds",
            "instrumented": True
        },

        "input_files": [
            DATA_ROOT / "bfs" / "graph1MW_6.txt"
        ]
    },


    # ========================================================
    # CFD
    # ========================================================

    "cfd": {
        "cpu": {
            "cwd": CPU_ROOT / "cfd",
            "command": (
                "./euler3d_cpu "
                "../../data/cfd/fvcorr.domn.193K"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)",
                r"Total time:\s*([0-9.]+)"
            ]
        },

        "gpu": {
            "cwd": GPU_ROOT / "cfd",
            "command": (
                "./euler3d "
                "../../data/cfd/fvcorr.domn.193K"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms",
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)\s*ms"
            ]
        },

        "input_files": [
            DATA_ROOT / "cfd" / "fvcorr.domn.193K"
        ]
    },


    # ========================================================
    # HEARTWALL
    # ========================================================

    "heartwall": {
        "cpu": {
            "cwd": CPU_ROOT / "heartwall",
            "command": (
                "./heartwall "
                "../../data/heartwall/test.avi "
                "20 4"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)",
                r"Time:\s*([0-9.]+)"
            ]
        },

        "gpu": {
            "cwd": GPU_ROOT / "heartwall",
            "command": (
                "./heartwall "
                "../../data/heartwall/test.avi "
                "20"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms",
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)\s*ms"
            ]
        },

        "input_files": [
            DATA_ROOT / "heartwall" / "test.avi"
        ]
    },


    # ========================================================
    # HOTSPOT
    # ========================================================

    "hotspot": {
        "cpu": {
            "cwd": CPU_ROOT / "hotspot",
            "command": (
                "./hotspot "
                "1024 1024 2 4 "
                "../../data/hotspot/temp_1024 "
                "../../data/hotspot/power_1024 "
                "output.out"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)",
                r"Time:\s*([0-9.]+)"
            ]
        },

        "gpu": {
            "cwd": GPU_ROOT / "hotspot",
            "command": (
                "./hotspot "
                "512 2 2 "
                "../../data/hotspot/temp_512 "
                "../../data/hotspot/power_512 "
                "output.out"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms",
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)\s*ms"
            ]
        },

        "input_files": [
            DATA_ROOT / "hotspot" / "temp_1024",
            DATA_ROOT / "hotspot" / "power_1024"
        ]
    },


    # ========================================================
    # HOTSPOT 3D
    # ========================================================

    "hotspot3D": {
        "cpu": {
            "cwd": CPU_ROOT / "hotspot3D",
            "command": (
                "./3D 512 8 100 "
                "../../data/hotspot3D/power_512x8 "
                "../../data/hotspot3D/temp_512x8 "
                "output.out"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)",
                r"Time:\s*([0-9.]+)"
            ]
        },

        "gpu": {
            "cwd": GPU_ROOT / "hotspot3D",
            "command": (
                "./3D 512 8 100 "
                "../../data/hotspot3D/power_512x8 "
                "../../data/hotspot3D/temp_512x8 "
                "output.out"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms",
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)\s*ms"
            ]
        },

        "input_files": [
            DATA_ROOT / "hotspot3D" / "power_512x8",
            DATA_ROOT / "hotspot3D" / "temp_512x8"
        ]
    },


    # ========================================================
    # KMEANS
    # ========================================================

    "kmeans": {
        "cpu": {
            "cwd": CPU_ROOT / "kmeans",
            "command": (
                "./kmeans_openmp/kmeans "
                "-n 4 "
                "-i ../../data/kmeans/kdd_cup"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)",
                r"Time:\s*([0-9.]+)"
            ]
        },

        "gpu": {
            "cwd": GPU_ROOT / "kmeans",
            "command": (
                "./kmeans "
                "-o "
                "-i ../../data/kmeans/kdd_cup"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms",
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)\s*ms"
            ]
        },

        "input_files": [
            DATA_ROOT / "kmeans" / "kdd_cup"
        ]
    },


    # ========================================================
    # LEUKOCYTE
    # ========================================================

    "leukocyte": {
        "cpu": {
            "cwd": CPU_ROOT / "leukocyte",
            "command": (
                "./OpenMP/leukocyte "
                "5 4 "
                "../../data/leukocyte/testfile.avi"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)",
                r"Time:\s*([0-9.]+)"
            ]
        },

        "gpu": {
            "cwd": GPU_ROOT / "leukocyte",
            "command": (
                "./CUDA/leukocyte "
                "../../data/leukocyte/testfile.avi "
                "5"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms",
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)\s*ms"
            ]
        },

        "input_files": [
            DATA_ROOT / "leukocyte" / "testfile.avi"
        ]
    },


    # ========================================================
    # LUD
    # ========================================================

    "lud": {
        "cpu": {
            "cwd": CPU_ROOT / "lud",
            "command": (
                "./omp/lud_omp "
                "-s 8000"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)",
                r"Time:\s*([0-9.]+)"
            ]
        },

        "gpu": {
            "cwd": GPU_ROOT / "lud",
            "command": (
                "cuda/lud_cuda "
                "-s 256 -v"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms",
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)\s*ms"
            ]
        },

        "input_files": [
            DATA_ROOT / "lud" / "256.dat"
        ]
    },


    # ========================================================
    # MUMMERGPU
    # ========================================================

    "mummergpu": {
        "cpu": {
            "cwd": CPU_ROOT / "mummergpu",
            "command": (
                "bin/mummergpu -C "
                "../../data/mummergpu/NC_003997.fna "
                "../../data/mummergpu/NC_003997_q100bp.fna "
                "> NC_00399.out"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)",
                r"Time:\s*([0-9.]+)"
            ]
        },

        "gpu": {
            "cwd": GPU_ROOT / "mummergpu",
            "command": (
                "bin/mummergpu "
                "../../data/mummergpu/NC_003997.fna "
                "../../data/mummergpu/NC_003997_q100bp.fna "
                "> NC_00399.out"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms",
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)\s*ms"
            ]
        },

        "input_files": [
            DATA_ROOT / "mummergpu" / "NC_003997.fna",
            DATA_ROOT / "mummergpu" / "NC_003997_q100bp.fna"
        ]
    },


    # ========================================================
    # MYOCYTE
    # ========================================================

    "myocyte": {
        "cpu": {
            "cwd": CPU_ROOT / "myocyte",
            "command": (
                "./myocyte.out "
                "100 1 0 4"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)",
                r"Time:\s*([0-9.]+)"
            ]
        },

        "gpu": {
            "cwd": GPU_ROOT / "myocyte",
            "command": (
                "./myocyte.out "
                "100 1 0"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms",
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)\s*ms"
            ]
        },

        "input_files": [
            DATA_ROOT / "myocyte" / "params.txt",
            DATA_ROOT / "myocyte" / "y.txt"
        ]
    },


    # ========================================================
    # NN
    # ========================================================

    "nn": {
        "cpu": {
            "cwd": CPU_ROOT / "nn",
            "command": (
                "./nn filelist_4 5 30 90"
            ),
            "time_regex": [
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)",
                r"Time:\s*([0-9.]+)"
            ]
        },

        "gpu": {
            "cwd": GPU_ROOT / "nn",
            "command": (
                "./nn filelist_4 "
                "-r 5 -lat 30 -lng 90"
            ),
            "time_regex": [
                r"GPU Kernel Time:\s*([0-9.]+)\s*ms",
                r"Compute time:\s*([0-9.]+)",
                r"Execution time:\s*([0-9.]+)\s*ms"
            ]
        },

        "input_files": [
            DATA_ROOT / "nn" / "cane4_0.db",
            DATA_ROOT / "nn" / "cane4_1.db",
            DATA_ROOT / "nn" / "cane4_2.db",
            DATA_ROOT / "nn" / "cane4_3.db"
        ]
    }
}

print("Configuration created.")
print("Configured workloads:", len(WORKLOAD_CONFIG))

for i, workload in enumerate(WORKLOAD_CONFIG, 1):
    print(f"{i:2d}. {workload}")

Configuration created.
Configured workloads: 12
 1. b+tree
 2. bfs
 3. cfd
 4. heartwall
 5. hotspot
 6. hotspot3D
 7. kmeans
 8. leukocyte
 9. lud
10. mummergpu
11. myocyte
12. nn

In [ ]:
# ============================================================
# SECTION 58 — GENERIC 6-RUN BENCHMARK ENGINE
# ============================================================

def run_command(command, cwd):
    """
    Execute one Rodinia command and capture stdout/stderr.
    """

    start = time.perf_counter()

    result = subprocess.run(
        command,
        cwd=str(cwd),
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True
    )

    end = time.perf_counter()

    wall_time_ms = (end - start) * 1000.0

    return {
        "returncode": result.returncode,
        "stdout": result.stdout,
        "wall_time_ms": wall_time_ms
    }


def extract_value(text, regex_list):
    """
    Try multiple regex patterns.
    Return first successful numeric value.
    """

    for pattern in regex_list:

        match = re.search(
            pattern,
            text,
            flags=re.IGNORECASE
        )

        if match:

            try:
                return float(match.group(1))
            except:
                pass

    return None


def extract_all_values(text, regex_list):
    """
    Return all numeric values matching supplied patterns.
    """

    values = []

    for pattern in regex_list:

        matches = re.findall(
            pattern,
            text,
            flags=re.IGNORECASE
        )

        for match in matches:

            try:
                values.append(float(match))
            except:
                pass

    return values


def calculate_statistics(values):

    values = [
        float(x)
        for x in values
        if x is not None
        and math.isfinite(float(x))
    ]

    if not values:
        return {
            "mean": None,
            "median": None,
            "std": None,
            "min": None,
            "max": None
        }

    return {
        "mean": statistics.mean(values),
        "median": statistics.median(values),
        "std": statistics.stdev(values)
                if len(values) > 1 else 0.0,
        "min": min(values),
        "max": max(values)
    }


def get_gpu_info():

    try:

        command = (
            "nvidia-smi "
            "--query-gpu=name,memory.total "
            "--format=csv,noheader"
        )

        result = subprocess.run(
            command,
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True
        )

        lines = [
            line.strip()
            for line in result.stdout.splitlines()
            if line.strip()
        ]

        if lines:

            first_gpu = lines[0]

            parts = [
                x.strip()
                for x in first_gpu.split(",")
            ]

            gpu_name = parts[0]
            gpu_memory = parts[1]

            memory_match = re.search(
                r"([0-9.]+)",
                gpu_memory
            )

            gpu_memory_mb = (
                float(memory_match.group(1))
                if memory_match
                else None
            )

            return gpu_name, gpu_memory_mb

    except Exception:
        pass

    return None, None


def calculate_input_size_mb(input_files):

    total_bytes = 0

    for file_path in input_files:

        path = Path(file_path)

        if path.exists():

            total_bytes += path.stat().st_size

    return total_bytes / (1024 * 1024)


def benchmark_cpu(
    workload,
    config,
    n_runs=N_RUNS
):

    print("\n" + "-" * 70)
    print(f"CPU BENCHMARK: {workload}")
    print("-" * 70)

    times = []
    wall_times = []

    failed_runs = 0

    for run_number in range(1, n_runs + 1):

        print(
            f"CPU run {run_number}/{n_runs}...",
            end=" ",
            flush=True
        )

        result = run_command(
            config["command"],
            config["cwd"]
        )

        wall_times.append(
            result["wall_time_ms"]
        )

        if result["returncode"] != 0:

            failed_runs += 1

            print(
                f"FAILED (return code "
                f"{result['returncode']})"
            )

            print(result["stdout"][-1000:])

            continue

        measured = extract_value(
            result["stdout"],
            config.get("time_regex", [])
        )

        if measured is None:

            # Fall back to wall-clock time
            # but explicitly mark it.
            measured = result["wall_time_ms"]

            print(
                f"OK | wall={measured:.3f} ms "
                f"(application timing not detected)"
            )

        else:

            unit = config.get(
                "time_unit",
                "milliseconds"
            )

            if unit == "seconds":
                measured *= 1000.0

            print(
                f"OK | measured={measured:.3f} ms "
                f"| wall={result['wall_time_ms']:.3f} ms"
            )

        times.append(measured)

    stats = calculate_statistics(times)

    return {
        "times_ms": times,
        "wall_times_ms": wall_times,
        "statistics": stats,
        "failed_runs": failed_runs
    }


def benchmark_gpu(
    workload,
    config,
    n_runs=N_RUNS
):

    print("\n" + "-" * 70)
    print(f"GPU BENCHMARK: {workload}")
    print("-" * 70)

    phase_times = []
    h2d_times = []
    d2h_times = []
    iterations = []
    wall_times = []

    failed_runs = 0

    for run_number in range(1, n_runs + 1):

        print(
            f"GPU run {run_number}/{n_runs}...",
            end=" ",
            flush=True
        )

        result = run_command(
            config["command"],
            config["cwd"]
        )

        wall_times.append(
            result["wall_time_ms"]
        )

        if result["returncode"] != 0:

            failed_runs += 1

            print(
                f"FAILED (return code "
                f"{result['returncode']})"
            )

            print(result["stdout"][-1000:])

            continue

        phase = extract_value(
            result["stdout"],
            config.get("time_regex", [])
        )

        h2d = extract_value(
            result["stdout"],
            config.get("h2d_regex", [])
        )

        d2h = extract_value(
            result["stdout"],
            config.get("d2h_regex", [])
        )

        iteration = extract_value(
            result["stdout"],
            config.get("iterations_regex", [])
        )

        if phase is not None:

            unit = config.get(
                "time_unit",
                "milliseconds"
            )

            if unit == "seconds":
                phase *= 1000.0

            phase_times.append(phase)

        if h2d is not None:
            h2d_times.append(h2d)

        if d2h is not None:
            d2h_times.append(d2h)

        if iteration is not None:
            iterations.append(iteration)

        if phase is not None:

            print(
                f"OK | GPU phase={phase:.3f} ms"
            )

        else:

            # No application-level GPU timing found.
            # Keep wall-clock measurement separately.
            print(
                f"OK | GPU wall={result['wall_time_ms']:.3f} ms "
                f"(GPU phase timing not detected)"
            )

    phase_stats = calculate_statistics(
        phase_times
    )

    h2d_stats = calculate_statistics(
        h2d_times
    )

    d2h_stats = calculate_statistics(
        d2h_times
    )

    iteration_stats = calculate_statistics(
        iterations
    )

    wall_stats = calculate_statistics(
        wall_times
    )

    return {
        "phase_times_ms": phase_times,
        "h2d_times_ms": h2d_times,
        "d2h_times_ms": d2h_times,
        "iterations": iterations,
        "wall_times_ms": wall_times,

        "phase_statistics": phase_stats,
        "h2d_statistics": h2d_stats,
        "d2h_statistics": d2h_stats,
        "iteration_statistics": iteration_stats,
        "wall_statistics": wall_stats,

        "failed_runs": failed_runs
    }

In [ ]:
# ============================================================
# SECTION 59 — COMPLETE WORKLOAD BENCHMARK
# ============================================================

def benchmark_workload(
    workload,
    n_runs=N_RUNS
):

    if workload not in WORKLOAD_CONFIG:

        raise ValueError(
            f"{workload} is not configured."
        )

    config = WORKLOAD_CONFIG[workload]

    print("\n")
    print("=" * 80)
    print(f"BENCHMARKING: {workload}")
    print("=" * 80)

    # --------------------------------------------------------
    # Check directories
    # --------------------------------------------------------

    if not config["cpu"]["cwd"].exists():
        raise FileNotFoundError(
            f"CPU directory missing: "
            f"{config['cpu']['cwd']}"
        )

    if not config["gpu"]["cwd"].exists():
        raise FileNotFoundError(
            f"GPU directory missing: "
            f"{config['gpu']['cwd']}"
        )

    # --------------------------------------------------------
    # Input size
    # --------------------------------------------------------

    input_size_mb = calculate_input_size_mb(
        config.get("input_files", [])
    )

    # --------------------------------------------------------
    # GPU information
    # --------------------------------------------------------

    gpu_name, gpu_memory_mb = get_gpu_info()

    # --------------------------------------------------------
    # CPU
    # --------------------------------------------------------

    cpu_result = benchmark_cpu(
        workload,
        config["cpu"],
        n_runs
    )

    # --------------------------------------------------------
    # GPU
    # --------------------------------------------------------

    gpu_result = benchmark_gpu(
        workload,
        config["gpu"],
        n_runs
    )

    # --------------------------------------------------------
    # Extract means
    # --------------------------------------------------------

    cpu_mean = cpu_result[
        "statistics"
    ]["mean"]

    gpu_phase_mean = gpu_result[
        "phase_statistics"
    ]["mean"]

    h2d_mean = gpu_result[
        "h2d_statistics"
    ]["mean"]

    d2h_mean = gpu_result[
        "d2h_statistics"
    ]["mean"]

    gpu_wall_mean = gpu_result[
        "wall_statistics"
    ]["mean"]

    # --------------------------------------------------------
    # GPU total path
    #
    # Only calculate this when the GPU phase and both
    # transfer measurements are actually available.
    # --------------------------------------------------------

    if (
        gpu_phase_mean is not None
        and h2d_mean is not None
        and d2h_mean is not None
    ):

        gpu_total_path = (
            gpu_phase_mean
            + h2d_mean
            + d2h_mean
        )

    else:

        gpu_total_path = None

    # --------------------------------------------------------
    # Preferred device
    #
    # IMPORTANT:
    # This is a measured benchmark label.
    # It is NOT yet the ML prediction.
    # --------------------------------------------------------

    if (
        cpu_mean is not None
        and gpu_total_path is not None
    ):

        if gpu_total_path < cpu_mean:
            preferred_device = "GPU"
        else:
            preferred_device = "CPU"

    elif (
        cpu_mean is not None
        and gpu_wall_mean is not None
    ):

        if gpu_wall_mean < cpu_mean:
            preferred_device = "GPU"
        else:
            preferred_device = "CPU"

    else:

        preferred_device = "UNKNOWN"

    # --------------------------------------------------------
    # Result
    # --------------------------------------------------------

    row = {

        "workload": workload,

        "input_size_mb": round(
            input_size_mb,
            4
        ),

        "gpu_type": gpu_name,

        "gpu_memory_mb": gpu_memory_mb,

        "cpu_execution_time_ms":
            cpu_mean,

        "cpu_execution_median_ms":
            cpu_result["statistics"]["median"],

        "cpu_execution_std_ms":
            cpu_result["statistics"]["std"],

        "gpu_phase_time_ms":
            gpu_phase_mean,

        "gpu_phase_median_ms":
            gpu_result[
                "phase_statistics"
            ]["median"],

        "gpu_phase_std_ms":
            gpu_result[
                "phase_statistics"
            ]["std"],

        "host_to_device_time_ms":
            h2d_mean,

        "device_to_host_time_ms":
            d2h_mean,

        "gpu_wall_time_ms":
            gpu_wall_mean,

        "gpu_total_path_time_ms":
            gpu_total_path,

        "gpu_kernel_iterations":
            gpu_result[
                "iteration_statistics"
            ]["mean"],

        "preferred_device":
            preferred_device,

        "cpu_failed_runs":
            cpu_result["failed_runs"],

        "gpu_failed_runs":
            gpu_result["failed_runs"]
    }

    return row, cpu_result, gpu_result

In [ ]:
# ============================================================
# SECTION 60 — DATASET STORAGE
# ============================================================

def save_benchmark_row(row):

    # --------------------------------------------------------
    # Convert row to DataFrame
    # --------------------------------------------------------

    import pandas as pd

    new_row = pd.DataFrame([row])

    # --------------------------------------------------------
    # If dataset already exists, append/update workload
    # --------------------------------------------------------

    if MASTER_DATASET.exists():

        existing = pd.read_csv(
            MASTER_DATASET
        )

        # Remove previous result for the same workload
        existing = existing[
            existing["workload"]
            != row["workload"]
        ]

        combined = pd.concat(
            [existing, new_row],
            ignore_index=True
        )

    else:

        combined = new_row

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    combined.to_csv(
        MASTER_DATASET,
        index=False
    )

    return combined


def save_raw_run_results(
    workload,
    cpu_result,
    gpu_result
):

    import pandas as pd

    rows = []

    max_runs = max(
        len(cpu_result["times_ms"]),
        len(gpu_result["phase_times_ms"]),
        len(gpu_result["wall_times_ms"])
    )

    for i in range(max_runs):

        row = {
            "workload": workload,
            "run_number": i + 1,

            "cpu_time_ms": (
                cpu_result["times_ms"][i]
                if i < len(
                    cpu_result["times_ms"]
                )
                else None
            ),

            "cpu_wall_time_ms": (
                cpu_result["wall_times_ms"][i]
                if i < len(
                    cpu_result["wall_times_ms"]
                )
                else None
            ),

            "gpu_phase_time_ms": (
                gpu_result["phase_times_ms"][i]
                if i < len(
                    gpu_result["phase_times_ms"]
                )
                else None
            ),

            "h2d_time_ms": (
                gpu_result["h2d_times_ms"][i]
                if i < len(
                    gpu_result["h2d_times_ms"]
                )
                else None
            ),

            "d2h_time_ms": (
                gpu_result["d2h_times_ms"][i]
                if i < len(
                    gpu_result["d2h_times_ms"]
                )
                else None
            ),

            "gpu_wall_time_ms": (
                gpu_result["wall_times_ms"][i]
                if i < len(
                    gpu_result["wall_times_ms"]
                )
                else None
            ),

            "gpu_kernel_iterations": (
                gpu_result["iterations"][i]
                if i < len(
                    gpu_result["iterations"]
                )
                else None
            )
        }

        rows.append(row)

    new_raw = pd.DataFrame(rows)

    if RAW_DATASET.exists():

        existing_raw = pd.read_csv(
            RAW_DATASET
        )

        existing_raw = existing_raw[
            existing_raw["workload"]
            != workload
        ]

        combined_raw = pd.concat(
            [existing_raw, new_raw],
            ignore_index=True
        )

    else:

        combined_raw = new_raw

    combined_raw.to_csv(
        RAW_DATASET,
        index=False
    )

    return combined_raw

In [ ]:
# ============================================================
# SECTION 61 — VALIDATE AUTOMATION USING BFS
# ============================================================

row, cpu_result, gpu_result = benchmark_workload(
    "bfs",
    n_runs=6
)

print("\n")
print("=" * 80)
print("BFS FINAL RESULT")
print("=" * 80)

for key, value in row.items():
    print(f"{key:35s}: {value}")

# Save
dataset = save_benchmark_row(row)

raw_dataset = save_raw_run_results(
    "bfs",
    cpu_result,
    gpu_result
)

print("\nMaster dataset:")
display(dataset)

print("\nRaw six-run dataset:")
display(
    raw_dataset[
        raw_dataset["workload"] == "bfs"
    ]
)

================================================================================
BENCHMARKING: bfs
================================================================================

----------------------------------------------------------------------
CPU BENCHMARK: bfs
----------------------------------------------------------------------
CPU run 1/6... OK | measured=47.108 ms | wall=1457.675 ms
CPU run 2/6... OK | measured=35.163 ms | wall=1388.140 ms
CPU run 3/6... OK | measured=35.718 ms | wall=1339.795 ms
CPU run 4/6... OK | measured=36.731 ms | wall=1399.863 ms
CPU run 5/6... OK | measured=36.165 ms | wall=1393.792 ms
CPU run 6/6... OK | measured=35.655 ms | wall=1371.937 ms

----------------------------------------------------------------------
GPU BENCHMARK: bfs
----------------------------------------------------------------------
GPU run 1/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found

GPU run 2/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found

GPU run 3/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found

GPU run 4/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found

GPU run 5/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found

GPU run 6/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found



================================================================================
BFS FINAL RESULT
================================================================================
workload                           : bfs
input_size_mb                      : 61.225
gpu_type                           : Tesla T4
gpu_memory_mb                      : 15360.0
cpu_execution_time_ms              : 37.75666666666667
cpu_execution_median_ms            : 35.941500000000005
cpu_execution_std_ms               : 4.611574597322118
gpu_phase_time_ms                  : None
gpu_phase_median_ms                : None
gpu_phase_std_ms                   : None
host_to_device_time_ms             : None
device_to_host_time_ms             : None
gpu_wall_time_ms                   : 1.837455333353925
gpu_total_path_time_ms             : None
gpu_kernel_iterations              : None
preferred_device                   : GPU
cpu_failed_runs                    : 0
gpu_failed_runs                    : 6

Master dataset:

,workload,input_file,input_size_mb,cpu_threads,gpu_type,gpu_memory_mb,cpu_execution_time_ms,gpu_phase_time_ms,host_to_device_time_ms,device_to_host_time_ms,gpu_kernel_iterations,gpu_total_path_time_ms,preferred_device,cpu_execution_median_ms,cpu_execution_std_ms,gpu_phase_median_ms,gpu_phase_std_ms,gpu_wall_time_ms,cpu_failed_runs,gpu_failed_runs
0,bfs,NaN,61.225,NaN,Tesla T4,15360.0,37.756667,None,None,None,None,None,GPU,35.9415,4.611575,None,None,1.837455,0.0,6.0

Raw six-run dataset:

,workload,run,cpu_execution_time_ms,gpu_phase_time_ms,host_to_device_time_ms,device_to_host_time_ms,gpu_kernel_iterations,run_number,cpu_time_ms,cpu_wall_time_ms,h2d_time_ms,d2h_time_ms,gpu_wall_time_ms
0,bfs,NaN,NaN,None,NaN,NaN,None,1.0,47.108,1457.675043,None,None,2.196377
1,bfs,NaN,NaN,None,NaN,NaN,None,2.0,35.163,1388.139819,None,None,2.150986
2,bfs,NaN,NaN,None,NaN,NaN,None,3.0,35.718,1339.794816,None,None,1.815190
3,bfs,NaN,NaN,None,NaN,NaN,None,4.0,36.731,1399.862949,None,None,1.732729
4,bfs,NaN,NaN,None,NaN,NaN,None,5.0,36.165,1393.791943,None,None,1.608265
5,bfs,NaN,NaN,None,NaN,NaN,None,6.0,35.655,1371.936739,None,None,1.521185

In [ ]:
# ============================================================
# SECTION 62 — RUN CFD
# ============================================================

row, cpu_result, gpu_result = benchmark_workload(
    "cfd",
    n_runs=6
)

dataset = save_benchmark_row(row)

raw_dataset = save_raw_run_results(
    "cfd",
    cpu_result,
    gpu_result
)

print("\nCFD RESULT")
print("=" * 80)

for key, value in row.items():
    print(f"{key:35s}: {value}")

display(dataset)

================================================================================
BENCHMARKING: cfd
================================================================================

----------------------------------------------------------------------
CPU BENCHMARK: cfd
----------------------------------------------------------------------
CPU run 1/6... FAILED (return code 127)
/bin/sh: 1: ./euler3d_cpu: not found

CPU run 2/6... FAILED (return code 127)
/bin/sh: 1: ./euler3d_cpu: not found

CPU run 3/6... FAILED (return code 127)
/bin/sh: 1: ./euler3d_cpu: not found

CPU run 4/6... FAILED (return code 127)
/bin/sh: 1: ./euler3d_cpu: not found

CPU run 5/6... FAILED (return code 127)
/bin/sh: 1: ./euler3d_cpu: not found

CPU run 6/6... FAILED (return code 127)
/bin/sh: 1: ./euler3d_cpu: not found


----------------------------------------------------------------------
GPU BENCHMARK: cfd
----------------------------------------------------------------------
GPU run 1/6... FAILED (return code 127)
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory

GPU run 2/6... FAILED (return code 127)
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory

GPU run 3/6... FAILED (return code 127)
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory

GPU run 4/6... FAILED (return code 127)
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory

GPU run 5/6... FAILED (return code 127)
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory

GPU run 6/6... FAILED (return code 127)
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory


CFD RESULT
================================================================================
workload                           : cfd
input_size_mb                      : 43.5447
gpu_type                           : Tesla T4
gpu_memory_mb                      : 15360.0
cpu_execution_time_ms              : None
cpu_execution_median_ms            : None
cpu_execution_std_ms               : None
gpu_phase_time_ms                  : None
gpu_phase_median_ms                : None
gpu_phase_std_ms                   : None
host_to_device_time_ms             : None
device_to_host_time_ms             : None
gpu_wall_time_ms                   : 2.4809748332472736
gpu_total_path_time_ms             : None
gpu_kernel_iterations              : None
preferred_device                   : UNKNOWN
cpu_failed_runs                    : 6
gpu_failed_runs                    : 6

/tmp/ipykernel_58/1149215994.py:31: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat(
/tmp/ipykernel_58/1149215994.py:146: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_raw = pd.concat(

,workload,input_file,input_size_mb,cpu_threads,gpu_type,gpu_memory_mb,cpu_execution_time_ms,gpu_phase_time_ms,host_to_device_time_ms,device_to_host_time_ms,gpu_kernel_iterations,gpu_total_path_time_ms,preferred_device,cpu_execution_median_ms,cpu_execution_std_ms,gpu_phase_median_ms,gpu_phase_std_ms,gpu_wall_time_ms,cpu_failed_runs,gpu_failed_runs
0,bfs,NaN,61.2250,NaN,Tesla T4,15360.0,37.756667,NaN,NaN,NaN,NaN,NaN,GPU,35.9415,4.611575,NaN,NaN,1.837455,0.0,6.0
1,cfd,NaN,43.5447,NaN,Tesla T4,15360.0,NaN,None,None,None,None,None,UNKNOWN,NaN,NaN,None,None,2.480975,6.0,6.0

In [ ]:
# ============================================================
# SECTION 63 — CHECK ACTUAL BFS CPU/GPU OUTPUT
# ============================================================

print("=" * 80)
print("BFS CPU RAW OUTPUT")
print("=" * 80)

cpu_test = run_command(
    WORKLOAD_CONFIG["bfs"]["cpu"]["command"],
    WORKLOAD_CONFIG["bfs"]["cpu"]["cwd"]
)

print(cpu_test["stdout"])


print("\n" + "=" * 80)
print("BFS GPU RAW OUTPUT")
print("=" * 80)

gpu_test = run_command(
    WORKLOAD_CONFIG["bfs"]["gpu"]["command"],
    WORKLOAD_CONFIG["bfs"]["gpu"]["cwd"]
)

print(gpu_test["stdout"])

================================================================================
BFS CPU RAW OUTPUT
================================================================================
Reading File
Start traversing the tree
Compute time: 0.034885
Result stored in result.txt


================================================================================
BFS GPU RAW OUTPUT
================================================================================
/bin/sh: 1: ./bfs: not found

In [ ]:
# ============================================================
# SECTION 64 — TEST BFS TIMING PARSERS
# ============================================================

cpu_value = extract_value(
    cpu_test["stdout"],
    WORKLOAD_CONFIG["bfs"]["cpu"]["time_regex"]
)

gpu_value = extract_value(
    gpu_test["stdout"],
    WORKLOAD_CONFIG["bfs"]["gpu"]["time_regex"]
)

h2d_value = extract_value(
    gpu_test["stdout"],
    WORKLOAD_CONFIG["bfs"]["gpu"]["h2d_regex"]
)

d2h_value = extract_value(
    gpu_test["stdout"],
    WORKLOAD_CONFIG["bfs"]["gpu"]["d2h_regex"]
)

iteration_value = extract_value(
    gpu_test["stdout"],
    WORKLOAD_CONFIG["bfs"]["gpu"]["iterations_regex"]
)

print("CPU parsed value:", cpu_value)
print("GPU phase parsed value:", gpu_value)
print("H2D parsed value:", h2d_value)
print("D2H parsed value:", d2h_value)
print("GPU iterations:", iteration_value)

CPU parsed value: 0.034885
GPU phase parsed value: None
H2D parsed value: None
D2H parsed value: None
GPU iterations: None

In [ ]:
# ============================================================
# SECTION 65 — CORRECTED BFS CONFIGURATION
# ============================================================

WORKLOAD_CONFIG["bfs"] = {

    "cpu": {
        "cwd": CPU_ROOT / "bfs",

        "command": (
            "./bfs 4 "
            "../../data/bfs/graph1MW_6.txt"
        ),

        "time_regex": [
            r"Compute\s*time\s*:\s*([0-9]+(?:\.[0-9]+)?)",
        ],

        "time_unit": "seconds",

        "use_wall_fallback": False
    },

    "gpu": {
        "cwd": GPU_ROOT / "bfs",

        "command": (
            "./bfs "
            "../../data/bfs/graph1MW_6.txt"
        ),

        "time_regex": [
            r"GPU\s*Kernel\s*Time\s*:\s*([0-9]+(?:\.[0-9]+)?)\s*ms"
        ],

        "h2d_regex": [
            r"Initial\s*Host\s*to\s*Device\s*Time\s*:\s*([0-9]+(?:\.[0-9]+)?)\s*ms"
        ],

        "d2h_regex": [
            r"Final\s*Device\s*to\s*Host\s*Time\s*:\s*([0-9]+(?:\.[0-9]+)?)\s*ms"
        ],

        "iterations_regex": [
            r"Kernel\s*Executed\s*([0-9]+)\s*times"
        ],

        "time_unit": "milliseconds",

        "instrumented": True,

        "use_wall_fallback": False
    },

    "input_files": [
        DATA_ROOT / "bfs" / "graph1MW_6.txt"
    ]
}

print("BFS configuration corrected.")

BFS configuration corrected.

In [ ]:
# ============================================================
# SECTION 66 — CORRECTED CPU BENCHMARK
# ============================================================

def benchmark_cpu(
    workload,
    config,
    n_runs=N_RUNS
):

    print("\n" + "-" * 70)
    print(f"CPU BENCHMARK: {workload}")
    print("-" * 70)

    times = []
    wall_times = []

    failed_runs = 0
    parse_failures = 0

    for run_number in range(1, n_runs + 1):

        print(
            f"CPU run {run_number}/{n_runs}...",
            end=" ",
            flush=True
        )

        result = run_command(
            config["command"],
            config["cwd"]
        )

        wall_times.append(
            result["wall_time_ms"]
        )

        if result["returncode"] != 0:

            failed_runs += 1

            print(
                f"FAILED "
                f"(return code {result['returncode']})"
            )

            print(result["stdout"][-1000:])

            continue

        measured = extract_value(
            result["stdout"],
            config.get("time_regex", [])
        )

        if measured is None:

            parse_failures += 1

            print(
                "FAILED TO PARSE APPLICATION TIMING"
            )

            print(
                "Output:",
                result["stdout"][-500:]
            )

            continue

        unit = config.get(
            "time_unit",
            "milliseconds"
        )

        if unit == "seconds":
            measured *= 1000.0

        times.append(measured)

        print(
            f"OK | application time="
            f"{measured:.6f} ms"
        )

    stats = calculate_statistics(times)

    return {
        "times_ms": times,
        "wall_times_ms": wall_times,

        "statistics": stats,

        "failed_runs": failed_runs,

        "parse_failures": parse_failures
    }

In [ ]:
# ============================================================
# SECTION 67 — CORRECTED GPU BENCHMARK
# ============================================================

def benchmark_gpu(
    workload,
    config,
    n_runs=N_RUNS
):

    print("\n" + "-" * 70)
    print(f"GPU BENCHMARK: {workload}")
    print("-" * 70)

    phase_times = []
    h2d_times = []
    d2h_times = []
    iterations = []
    wall_times = []

    failed_runs = 0
    phase_parse_failures = 0

    for run_number in range(1, n_runs + 1):

        print(
            f"GPU run {run_number}/{n_runs}...",
            end=" ",
            flush=True
        )

        result = run_command(
            config["command"],
            config["cwd"]
        )

        wall_times.append(
            result["wall_time_ms"]
        )

        if result["returncode"] != 0:

            failed_runs += 1

            print(
                f"FAILED "
                f"(return code {result['returncode']})"
            )

            print(result["stdout"][-1000:])

            continue

        phase = extract_value(
            result["stdout"],
            config.get("time_regex", [])
        )

        h2d = extract_value(
            result["stdout"],
            config.get("h2d_regex", [])
        )

        d2h = extract_value(
            result["stdout"],
            config.get("d2h_regex", [])
        )

        iteration = extract_value(
            result["stdout"],
            config.get("iterations_regex", [])
        )

        if phase is None:

            phase_parse_failures += 1

            print(
                "FAILED TO PARSE GPU PHASE TIME"
            )

            print(
                "Output:",
                result["stdout"][-500:]
            )

            continue

        unit = config.get(
            "time_unit",
            "milliseconds"
        )

        if unit == "seconds":
            phase *= 1000.0

        phase_times.append(phase)

        if h2d is not None:
            h2d_times.append(h2d)

        if d2h is not None:
            d2h_times.append(d2h)

        if iteration is not None:
            iterations.append(iteration)

        print(
            f"OK | GPU phase="
            f"{phase:.6f} ms"
            f" | H2D="
            f"{h2d if h2d is not None else 'N/A'}"
            f" ms"
            f" | D2H="
            f"{d2h if d2h is not None else 'N/A'}"
            f" ms"
        )

    return {

        "phase_times_ms": phase_times,

        "h2d_times_ms": h2d_times,

        "d2h_times_ms": d2h_times,

        "iterations": iterations,

        "wall_times_ms": wall_times,

        "phase_statistics":
            calculate_statistics(phase_times),

        "h2d_statistics":
            calculate_statistics(h2d_times),

        "d2h_statistics":
            calculate_statistics(d2h_times),

        "iteration_statistics":
            calculate_statistics(iterations),

        "wall_statistics":
            calculate_statistics(wall_times),

        "failed_runs":
            failed_runs,

        "phase_parse_failures":
            phase_parse_failures
    }

In [ ]:
# ============================================================
# SECTION 68 — CLEAN DATASET SCHEMA
# ============================================================

import pandas as pd
from pathlib import Path

MASTER_DATASET = Path(
    "/kaggle/working/rodinia_cpu_gpu_dataset.csv"
)

RAW_DATASET = Path(
    "/kaggle/working/rodinia_raw_benchmark_results.csv"
)

# Remove the incorrectly structured files
if MASTER_DATASET.exists():
    MASTER_DATASET.unlink()

if RAW_DATASET.exists():
    RAW_DATASET.unlink()

print("Old benchmark CSV files removed.")
print("We will now rebuild them with one fixed schema.")

Old benchmark CSV files removed.
We will now rebuild them with one fixed schema.

In [ ]:
# ============================================================
# SECTION 69 — CORRECT RAW DATASET STORAGE
# ============================================================

def save_raw_run_results(
    workload,
    cpu_result,
    gpu_result
):

    import pandas as pd

    rows = []

    for i in range(N_RUNS):

        row = {
            "workload": workload,

            "run_number": i + 1,

            "cpu_time_ms": (
                cpu_result["times_ms"][i]
                if i < len(cpu_result["times_ms"])
                else None
            ),

            "cpu_wall_time_ms": (
                cpu_result["wall_times_ms"][i]
                if i < len(cpu_result["wall_times_ms"])
                else None
            ),

            "gpu_phase_time_ms": (
                gpu_result["phase_times_ms"][i]
                if i < len(gpu_result["phase_times_ms"])
                else None
            ),

            "h2d_time_ms": (
                gpu_result["h2d_times_ms"][i]
                if i < len(gpu_result["h2d_times_ms"])
                else None
            ),

            "d2h_time_ms": (
                gpu_result["d2h_times_ms"][i]
                if i < len(gpu_result["d2h_times_ms"])
                else None
            ),

            "gpu_wall_time_ms": (
                gpu_result["wall_times_ms"][i]
                if i < len(gpu_result["wall_times_ms"])
                else None
            ),

            "gpu_kernel_iterations": (
                gpu_result["iterations"][i]
                if i < len(gpu_result["iterations"])
                else None
            )
        }

        rows.append(row)

    new_raw = pd.DataFrame(rows)

    # Fixed column order
    columns = [
        "workload",
        "run_number",
        "cpu_time_ms",
        "cpu_wall_time_ms",
        "gpu_phase_time_ms",
        "h2d_time_ms",
        "d2h_time_ms",
        "gpu_wall_time_ms",
        "gpu_kernel_iterations"
    ]

    new_raw = new_raw[columns]

    # If the workload already exists, replace it
    if RAW_DATASET.exists():

        existing = pd.read_csv(
            RAW_DATASET
        )

        existing = existing[
            existing["workload"] != workload
        ]

        combined = pd.concat(
            [existing, new_raw],
            ignore_index=True
        )

        combined = combined[columns]

    else:

        combined = new_raw

    combined.to_csv(
        RAW_DATASET,
        index=False
    )

    return combined

In [ ]:
# ============================================================
# SECTION 70 — CORRECT MASTER DATASET STORAGE
# ============================================================

def save_benchmark_row(row):

    import pandas as pd

    columns = [
        "workload",
        "input_size_mb",
        "gpu_type",
        "gpu_memory_mb",

        "cpu_execution_time_ms",
        "cpu_execution_median_ms",
        "cpu_execution_std_ms",

        "gpu_phase_time_ms",
        "gpu_phase_median_ms",
        "gpu_phase_std_ms",

        "host_to_device_time_ms",
        "device_to_host_time_ms",

        "gpu_wall_time_ms",

        "gpu_total_path_time_ms",

        "gpu_kernel_iterations",

        "preferred_device",

        "cpu_failed_runs",
        "gpu_failed_runs"
    ]

    new_row = pd.DataFrame(
        [row],
        columns=columns
    )

    if MASTER_DATASET.exists():

        existing = pd.read_csv(
            MASTER_DATASET
        )

        # Remove previous result for same workload
        existing = existing[
            existing["workload"] != row["workload"]
        ]

        combined = pd.concat(
            [existing, new_row],
            ignore_index=True
        )

    else:

        combined = new_row

    combined = combined[columns]

    combined.to_csv(
        MASTER_DATASET,
        index=False
    )

    return combined

In [ ]:
# ============================================================
# SECTION 71 — CORRECT MASTER ROW CREATION
# ============================================================

def create_master_row(
    workload,
    cpu_result,
    gpu_result
):

    config = WORKLOAD_CONFIG[workload]

    input_size_mb = calculate_input_size_mb(
        config.get("input_files", [])
    )

    gpu_name, gpu_memory_mb = get_gpu_info()

    cpu_stats = cpu_result["statistics"]

    gpu_phase_stats = gpu_result[
        "phase_statistics"
    ]

    h2d_stats = gpu_result[
        "h2d_statistics"
    ]

    d2h_stats = gpu_result[
        "d2h_statistics"
    ]

    iteration_stats = gpu_result[
        "iteration_statistics"
    ]

    gpu_wall_stats = gpu_result[
        "wall_statistics"
    ]

    cpu_mean = cpu_stats["mean"]
    gpu_phase_mean = gpu_phase_stats["mean"]
    h2d_mean = h2d_stats["mean"]
    d2h_mean = d2h_stats["mean"]

    # --------------------------------------------------------
    # GPU total transfer-aware path
    # --------------------------------------------------------

    if (
        gpu_phase_mean is not None
        and h2d_mean is not None
        and d2h_mean is not None
    ):

        gpu_total = (
            gpu_phase_mean
            + h2d_mean
            + d2h_mean
        )

    else:

        gpu_total = None

    # --------------------------------------------------------
    # Measured scheduling label
    # --------------------------------------------------------

    if (
        cpu_mean is not None
        and gpu_total is not None
    ):

        if gpu_total < cpu_mean:
            preferred_device = "GPU"
        else:
            preferred_device = "CPU"

    else:

        preferred_device = "UNKNOWN"

    return {

        "workload": workload,

        "input_size_mb":
            input_size_mb,

        "gpu_type":
            gpu_name,

        "gpu_memory_mb":
            gpu_memory_mb,

        "cpu_execution_time_ms":
            cpu_mean,

        "cpu_execution_median_ms":
            cpu_stats["median"],

        "cpu_execution_std_ms":
            cpu_stats["std"],

        "gpu_phase_time_ms":
            gpu_phase_mean,

        "gpu_phase_median_ms":
            gpu_phase_stats["median"],

        "gpu_phase_std_ms":
            gpu_phase_stats["std"],

        "host_to_device_time_ms":
            h2d_mean,

        "device_to_host_time_ms":
            d2h_mean,

        "gpu_wall_time_ms":
            gpu_wall_stats["mean"],

        "gpu_total_path_time_ms":
            gpu_total,

        "gpu_kernel_iterations":
            iteration_stats["mean"],

        "preferred_device":
            preferred_device,

        "cpu_failed_runs":
            cpu_result["failed_runs"],

        "gpu_failed_runs":
            gpu_result["failed_runs"]
    }

In [ ]:
# ============================================================
# SECTION 72 — FINAL BFS VALIDATION
# ============================================================

row, cpu_result, gpu_result = benchmark_workload(
    "bfs",
    n_runs=6
)

# Create clean master row
master_row = create_master_row(
    "bfs",
    cpu_result,
    gpu_result
)

# Save master dataset
master_dataset = save_benchmark_row(
    master_row
)

# Save raw dataset
raw_dataset = save_raw_run_results(
    "bfs",
    cpu_result,
    gpu_result
)

print("\n")
print("=" * 80)
print("FINAL BFS MASTER RESULT")
print("=" * 80)

display(master_dataset)

print("\n")
print("=" * 80)
print("FINAL BFS RAW 6-RUN RESULT")
print("=" * 80)

display(raw_dataset)

================================================================================
BENCHMARKING: bfs
================================================================================

----------------------------------------------------------------------
CPU BENCHMARK: bfs
----------------------------------------------------------------------
CPU run 1/6... OK | application time=35.133000 ms
CPU run 2/6... OK | application time=36.672000 ms
CPU run 3/6... OK | application time=36.037000 ms
CPU run 4/6... OK | application time=36.217000 ms
CPU run 5/6... OK | application time=36.199000 ms
CPU run 6/6... OK | application time=35.702000 ms

----------------------------------------------------------------------
GPU BENCHMARK: bfs
----------------------------------------------------------------------
GPU run 1/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found

GPU run 2/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found

GPU run 3/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found

GPU run 4/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found

GPU run 5/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found

GPU run 6/6... FAILED (return code 127)
/bin/sh: 1: ./bfs: not found



================================================================================
FINAL BFS MASTER RESULT
================================================================================

,workload,input_size_mb,gpu_type,gpu_memory_mb,cpu_execution_time_ms,cpu_execution_median_ms,cpu_execution_std_ms,gpu_phase_time_ms,gpu_phase_median_ms,gpu_phase_std_ms,host_to_device_time_ms,device_to_host_time_ms,gpu_wall_time_ms,gpu_total_path_time_ms,gpu_kernel_iterations,preferred_device,cpu_failed_runs,gpu_failed_runs
0,bfs,61.225021,Tesla T4,15360.0,35.993333,36.118,0.525332,None,None,None,None,None,1.723669,None,None,UNKNOWN,0,6

================================================================================
FINAL BFS RAW 6-RUN RESULT
================================================================================

,workload,run_number,cpu_time_ms,cpu_wall_time_ms,gpu_phase_time_ms,h2d_time_ms,d2h_time_ms,gpu_wall_time_ms,gpu_kernel_iterations
0,bfs,1,35.133,1404.358124,None,None,None,2.035059,None
1,bfs,2,36.672,1360.435700,None,None,None,1.679742,None
2,bfs,3,36.037,1413.980430,None,None,None,1.691997,None
3,bfs,4,36.217,1394.275564,None,None,None,1.665728,None
4,bfs,5,36.199,1410.073926,None,None,None,1.585881,None
5,bfs,6,35.702,1350.526886,None,None,None,1.683608,None

In [ ]:
# ============================================================
# RODINIA 3.1 — CFD CPU/GPU 6-RUN BENCHMARK
# Clean measurement pipeline
# ============================================================

import os
import re
import time
import subprocess
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------
RODINIA_ROOT = "/kaggle/working/Rodinia"

CPU_DIR = f"{RODINIA_ROOT}/openmp/cfd"
GPU_DIR = f"{RODINIA_ROOT}/cuda/cfd"

DATA_FILE = f"{RODINIA_ROOT}/data/cfd/fvcorr.domn.193K"

N_RUNS = 6

RAW_CSV = "/kaggle/working/rodinia_cfd_raw_results.csv"
MASTER_CSV = "/kaggle/working/rodinia_cfd_master_dataset.csv"

# ------------------------------------------------------------
# 2. CHECK PATHS
# ------------------------------------------------------------
print("=" * 70)
print("CFD BENCHMARK")
print("=" * 70)

print("\nChecking paths...")

print("CPU directory :", CPU_DIR, os.path.exists(CPU_DIR))
print("GPU directory :", GPU_DIR, os.path.exists(GPU_DIR))
print("Input file    :", DATA_FILE, os.path.exists(DATA_FILE))

if not os.path.exists(DATA_FILE):
    raise FileNotFoundError(f"CFD input file not found: {DATA_FILE}")

# ------------------------------------------------------------
# 3. COMPILE CPU
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("COMPILING CPU VERSION")
print("=" * 70)

cpu_make = subprocess.run(
    ["make", "-j2"],
    cwd=CPU_DIR,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print(cpu_make.stdout[-4000:])

# Find likely CPU executable
CPU_EXEC = None

for candidate in [
    "euler3d_cpu",
    "euler3d_cpu.exe"
]:
    path = os.path.join(CPU_DIR, candidate)
    if os.path.exists(path):
        CPU_EXEC = path
        break

if CPU_EXEC is None:
    raise FileNotFoundError(
        "CPU CFD executable was not found after compilation."
    )

print("CPU executable:", CPU_EXEC)

# ------------------------------------------------------------
# 4. COMPILE GPU
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("COMPILING GPU VERSION")
print("=" * 70)

gpu_make = subprocess.run(
    ["make", "-j2"],
    cwd=GPU_DIR,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print(gpu_make.stdout[-4000:])

GPU_EXEC = None

for candidate in [
    "euler3d",
    "euler3d.exe"
]:
    path = os.path.join(GPU_DIR, candidate)
    if os.path.exists(path):
        GPU_EXEC = path
        break

if GPU_EXEC is None:
    raise FileNotFoundError(
        "GPU CFD executable was not found after compilation."
    )

print("GPU executable:", GPU_EXEC)

# ------------------------------------------------------------
# 5. RUN COMMAND FUNCTION
# ------------------------------------------------------------
def run_command(command, cwd):

    start = time.perf_counter()

    result = subprocess.run(
        command,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True
    )

    end = time.perf_counter()

    wall_ms = (end - start) * 1000.0

    return result.returncode, wall_ms, result.stdout


# ------------------------------------------------------------
# 6. TIMING PARSERS
# ------------------------------------------------------------
def parse_cpu_time(output):

    patterns = [

        # Example:
        # Compute time: 123.456
        r"Compute\s*time\s*:\s*([0-9.]+)",

        # Example:
        # Execution time: 123.456 ms
        r"Execution\s*time\s*:\s*([0-9.]+)",

        # Example:
        # Time: 123.456
        r"\bTime\s*:\s*([0-9.]+)"
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            output,
            re.IGNORECASE
        )

        if match:
            return float(match.group(1))

    return np.nan


def parse_gpu_phase(output):

    patterns = [

        r"GPU\s+Phase\s+Time\s*:\s*([0-9.]+)\s*ms",

        r"GPU\s+Kernel\s+Time\s*:\s*([0-9.]+)\s*ms",

        r"Kernel\s+Time\s*:\s*([0-9.]+)\s*ms",

        r"GPU\s+Execution\s+Time\s*:\s*([0-9.]+)\s*ms"
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            output,
            re.IGNORECASE
        )

        if match:
            return float(match.group(1))

    return np.nan


def parse_h2d(output):

    patterns = [

        r"Initial\s+Host\s+to\s+Device\s+Time\s*:\s*([0-9.]+)\s*ms",

        r"Host\s+to\s+Device\s+Time\s*:\s*([0-9.]+)\s*ms",

        r"H2D\s+Time\s*:\s*([0-9.]+)\s*ms"
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            output,
            re.IGNORECASE
        )

        if match:
            return float(match.group(1))

    return np.nan


def parse_d2h(output):

    patterns = [

        r"Final\s+Device\s+to\s+Host\s+Time\s*:\s*([0-9.]+)\s*ms",

        r"Device\s+to\s+Host\s+Time\s*:\s*([0-9.]+)\s*ms",

        r"D2H\s+Time\s*:\s*([0-9.]+)\s*ms"
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            output,
            re.IGNORECASE
        )

        if match:
            return float(match.group(1))

    return np.nan


def parse_iterations(output):

    patterns = [

        r"Kernel\s+Executed\s+(\d+)\s+times",

        r"Iterations\s*:\s*(\d+)"
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            output,
            re.IGNORECASE
        )

        if match:
            return int(match.group(1))

    return np.nan


# ------------------------------------------------------------
# 7. COMMANDS
# ------------------------------------------------------------

CPU_COMMAND = [
    "./euler3d_cpu",
    "../../data/cfd/fvcorr.domn.193K"
]

GPU_COMMAND = [
    "./euler3d",
    "../../data/cfd/fvcorr.domn.193K"
]

# ------------------------------------------------------------
# 8. BENCHMARK
# ------------------------------------------------------------

records = []

for run in range(1, N_RUNS + 1):

    print("\n" + "-" * 70)
    print(f"RUN {run}/{N_RUNS}")
    print("-" * 70)

    # --------------------------------------------------------
    # CPU
    # --------------------------------------------------------
    print("\nCPU running...")

    cpu_return, cpu_wall, cpu_output = run_command(
        CPU_COMMAND,
        CPU_DIR
    )

    cpu_time = parse_cpu_time(cpu_output)

    if cpu_return != 0:
        print("CPU FAILED")
        print(cpu_output[-2000:])

    else:
        print("CPU return code :", cpu_return)
        print("CPU application time:", cpu_time, "ms")
        print("CPU wall time:", cpu_wall, "ms")

    # --------------------------------------------------------
    # GPU
    # --------------------------------------------------------
    print("\nGPU running...")

    gpu_return, gpu_wall, gpu_output = run_command(
        GPU_COMMAND,
        GPU_DIR
    )

    gpu_phase = parse_gpu_phase(gpu_output)
    h2d = parse_h2d(gpu_output)
    d2h = parse_d2h(gpu_output)
    iterations = parse_iterations(gpu_output)

    if gpu_return != 0:

        print("GPU FAILED")
        print(gpu_output[-3000:])

    else:

        print("GPU return code :", gpu_return)
        print("GPU phase time  :", gpu_phase, "ms")
        print("H2D time        :", h2d, "ms")
        print("D2H time        :", d2h, "ms")
        print("GPU wall time   :", gpu_wall, "ms")
        print("Iterations      :", iterations)

    # --------------------------------------------------------
    # STORE ONE COMPLETE RECORD
    # --------------------------------------------------------
    records.append({
        "workload": "cfd",
        "run_number": run,

        "cpu_time_ms": cpu_time,
        "cpu_wall_time_ms": cpu_wall,

        "gpu_phase_time_ms": gpu_phase,
        "h2d_time_ms": h2d,
        "d2h_time_ms": d2h,

        "gpu_wall_time_ms": gpu_wall,
        "gpu_kernel_iterations": iterations,

        "cpu_return_code": cpu_return,
        "gpu_return_code": gpu_return
    })

# ------------------------------------------------------------
# 9. RAW DATASET
# ------------------------------------------------------------

raw_df = pd.DataFrame(records)

raw_df.to_csv(
    RAW_CSV,
    index=False
)

print("\n" + "=" * 70)
print("RAW DATASET")
print("=" * 70)

display(raw_df)

# ------------------------------------------------------------
# 10. VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TIMING VALIDATION")
print("=" * 70)

print(
    "CPU timing values available:",
    raw_df["cpu_time_ms"].notna().sum(),
    "/",
    N_RUNS
)

print(
    "GPU phase values available:",
    raw_df["gpu_phase_time_ms"].notna().sum(),
    "/",
    N_RUNS
)

print(
    "H2D timing values available:",
    raw_df["h2d_time_ms"].notna().sum(),
    "/",
    N_RUNS
)

print(
    "D2H timing values available:",
    raw_df["d2h_time_ms"].notna().sum(),
    "/",
    N_RUNS
)

# ------------------------------------------------------------
# 11. SUMMARY STATISTICS
# ------------------------------------------------------------

cpu_mean = raw_df["cpu_time_ms"].mean()
cpu_median = raw_df["cpu_time_ms"].median()
cpu_std = raw_df["cpu_time_ms"].std()

gpu_phase_mean = raw_df["gpu_phase_time_ms"].mean()
gpu_phase_median = raw_df["gpu_phase_time_ms"].median()
gpu_phase_std = raw_df["gpu_phase_time_ms"].std()

h2d_mean = raw_df["h2d_time_ms"].mean()
d2h_mean = raw_df["d2h_time_ms"].mean()

# Transfer-aware GPU execution path
if not np.isnan(gpu_phase_mean) and not np.isnan(h2d_mean) and not np.isnan(d2h_mean):

    gpu_total = (
        gpu_phase_mean
        + h2d_mean
        + d2h_mean
    )

else:

    gpu_total = np.nan

# ------------------------------------------------------------
# 12. DEVICE LABEL
# ------------------------------------------------------------

if not np.isnan(cpu_mean) and not np.isnan(gpu_total):

    if gpu_total < cpu_mean:
        preferred_device = "GPU"
    else:
        preferred_device = "CPU"

else:

    preferred_device = "UNKNOWN"

# ------------------------------------------------------------
# 13. MASTER DATASET
# ------------------------------------------------------------

master_row = {

    "workload": "cfd",

    "input_file": "fvcorr.domn.193K",

    "cpu_execution_time_ms": cpu_mean,
    "cpu_execution_median_ms": cpu_median,
    "cpu_execution_std_ms": cpu_std,

    "gpu_phase_time_ms": gpu_phase_mean,
    "gpu_phase_median_ms": gpu_phase_median,
    "gpu_phase_std_ms": gpu_phase_std,

    "host_to_device_time_ms": h2d_mean,
    "device_to_host_time_ms": d2h_mean,

    "gpu_total_path_time_ms": gpu_total,

    "gpu_kernel_iterations":
        raw_df["gpu_kernel_iterations"].median(),

    "preferred_device": preferred_device,

    "cpu_failed_runs":
        int((raw_df["cpu_return_code"] != 0).sum()),

    "gpu_failed_runs":
        int((raw_df["gpu_return_code"] != 0).sum())
}

master_df = pd.DataFrame([master_row])

master_df.to_csv(
    MASTER_CSV,
    index=False
)

# ------------------------------------------------------------
# 14. FINAL RESULT
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CFD MASTER RESULT")
print("=" * 70)

display(master_df)

print("\nFiles created:")
print(RAW_CSV)
print(MASTER_CSV)

print("\n" + "=" * 70)
print("IMPORTANT")
print("=" * 70)

print("""
CPU execution time  = application-reported CPU computation time
GPU phase time      = application-reported GPU phase time, if instrumented
H2D/D2H              = measured transfer times, if instrumented
GPU total path       = GPU phase + H2D + D2H

GPU wall time is NOT used as GPU execution time.
If a timing parser returns NaN, the code does NOT replace it with wall time.
""")

======================================================================
CFD BENCHMARK
======================================================================

Checking paths...
CPU directory : /kaggle/working/Rodinia/openmp/cfd True
GPU directory : /kaggle/working/Rodinia/cuda/cfd True
Input file    : /kaggle/working/Rodinia/data/cfd/fvcorr.domn.193K True

======================================================================
COMPILING CPU VERSION
======================================================================
g++ -O3 -Dblock_length=8 -fopenmp euler3d_cpu.cpp -o euler3d_cpu
g++ -O3 -Dblock_length=8 -fopenmp euler3d_cpu_double.cpp -o euler3d_cpu_double
g++ -O3 -Dblock_length=8 -fopenmp pre_euler3d_cpu.cpp -o pre_euler3d_cpu
g++ -O3 -Dblock_length=8 -fopenmp pre_euler3d_cpu_double.cpp -o pre_euler3d_cpu_double
icc -g -O3 -DOMP_OFFLOAD -Dblock_length=216 -fopenmp -offload-option,mic,compiler,"-no-opt-prefetch" euler3d_cpu.cpp -o euler3d_cpu_offload
/bin/sh: 1: icc: not found
make: *** [makefile:18: euler3d_cpu_offload] Error 127
make: *** Waiting for unfinished jobs....

CPU executable: /kaggle/working/Rodinia/openmp/cfd/euler3d_cpu

======================================================================
COMPILING GPU VERSION
======================================================================
nvcc -Xptxas -v -O3 --gpu-architecture=compute_20 --gpu-code=compute_20 euler3d_double.cu -o euler3d_double -I/usr/local/cuda-5.5/samples//common/inc  -L/usr/local/cuda-5.5/samples//lib
nvcc -Xptxas -v -O3 --gpu-architecture=compute_20 --gpu-code=compute_20 pre_euler3d.cu -o pre_euler3d -I/usr/local/cuda-5.5/samples//common/inc  -L/usr/local/cuda-5.5/samples//lib
nvcc fatal   : Value 'compute_20' is not defined for option 'gpu-code'
make: *** [Makefile:20: euler3d_double] Error 1
make: *** Waiting for unfinished jobs....
nvcc fatal   : Value 'compute_20' is not defined for option 'gpu-code'
make: *** [Makefile:24: pre_euler3d] Error 1

GPU executable: /kaggle/working/Rodinia/cuda/cfd/euler3d

----------------------------------------------------------------------
RUN 1/6
----------------------------------------------------------------------

CPU running...
CPU return code : 0
CPU application time: 77.4126 ms
CPU wall time: 79727.68922399996 ms

GPU running...
GPU FAILED
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory


----------------------------------------------------------------------
RUN 2/6
----------------------------------------------------------------------

CPU running...
CPU return code : 0
CPU application time: 77.4909 ms
CPU wall time: 79706.31204599999 ms

GPU running...
GPU FAILED
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory


----------------------------------------------------------------------
RUN 3/6
----------------------------------------------------------------------

CPU running...
CPU return code : 0
CPU application time: 77.4162 ms
CPU wall time: 79616.27943200005 ms

GPU running...
GPU FAILED
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory


----------------------------------------------------------------------
RUN 4/6
----------------------------------------------------------------------

CPU running...
CPU return code : 0
CPU application time: 77.5837 ms
CPU wall time: 79844.95777200004 ms

GPU running...
GPU FAILED
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory


----------------------------------------------------------------------
RUN 5/6
----------------------------------------------------------------------

CPU running...
CPU return code : 0
CPU application time: 77.9699 ms
CPU wall time: 80237.50630900008 ms

GPU running...
GPU FAILED
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory


----------------------------------------------------------------------
RUN 6/6
----------------------------------------------------------------------

CPU running...
CPU return code : 0
CPU application time: 77.8667 ms
CPU wall time: 80058.78956800007 ms

GPU running...
GPU FAILED
./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory


======================================================================
RAW DATASET
======================================================================

,workload,run_number,cpu_time_ms,cpu_wall_time_ms,gpu_phase_time_ms,h2d_time_ms,d2h_time_ms,gpu_wall_time_ms,gpu_kernel_iterations,cpu_return_code,gpu_return_code
0,cfd,1,77.4126,79727.689224,NaN,NaN,NaN,1.739922,NaN,0,127
1,cfd,2,77.4909,79706.312046,NaN,NaN,NaN,1.687943,NaN,0,127
2,cfd,3,77.4162,79616.279432,NaN,NaN,NaN,1.631999,NaN,0,127
3,cfd,4,77.5837,79844.957772,NaN,NaN,NaN,1.713525,NaN,0,127
4,cfd,5,77.9699,80237.506309,NaN,NaN,NaN,1.505495,NaN,0,127
5,cfd,6,77.8667,80058.789568,NaN,NaN,NaN,1.841739,NaN,0,127

======================================================================
TIMING VALIDATION
======================================================================
CPU timing values available: 6 / 6
GPU phase values available: 0 / 6
H2D timing values available: 0 / 6
D2H timing values available: 0 / 6

======================================================================
CFD MASTER RESULT
======================================================================

,workload,input_file,cpu_execution_time_ms,cpu_execution_median_ms,cpu_execution_std_ms,gpu_phase_time_ms,gpu_phase_median_ms,gpu_phase_std_ms,host_to_device_time_ms,device_to_host_time_ms,gpu_total_path_time_ms,gpu_kernel_iterations,preferred_device,cpu_failed_runs,gpu_failed_runs
0,cfd,fvcorr.domn.193K,77.623333,77.5373,0.239064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN,0,6

Files created:
/kaggle/working/rodinia_cfd_raw_results.csv
/kaggle/working/rodinia_cfd_master_dataset.csv

======================================================================
IMPORTANT
======================================================================

CPU execution time  = application-reported CPU computation time
GPU phase time      = application-reported GPU phase time, if instrumented
H2D/D2H              = measured transfer times, if instrumented
GPU total path       = GPU phase + H2D + D2H

GPU wall time is NOT used as GPU execution time.
If a timing parser returns NaN, the code does NOT replace it with wall time.

In [ ]:
import pandas as pd

print("========== RAW CFD RESULTS ==========")
display(pd.read_csv("/kaggle/working/rodinia_cfd_raw_results.csv"))

print("\n========== CFD MASTER DATASET ==========")
display(pd.read_csv("/kaggle/working/rodinia_cfd_master_dataset.csv"))

========== RAW CFD RESULTS ==========

,workload,run_number,cpu_time_ms,cpu_wall_time_ms,gpu_phase_time_ms,h2d_time_ms,d2h_time_ms,gpu_wall_time_ms,gpu_kernel_iterations,cpu_return_code,gpu_return_code
0,cfd,1,77.4126,79727.689224,NaN,NaN,NaN,1.739922,NaN,0,127
1,cfd,2,77.4909,79706.312046,NaN,NaN,NaN,1.687943,NaN,0,127
2,cfd,3,77.4162,79616.279432,NaN,NaN,NaN,1.631999,NaN,0,127
3,cfd,4,77.5837,79844.957772,NaN,NaN,NaN,1.713525,NaN,0,127
4,cfd,5,77.9699,80237.506309,NaN,NaN,NaN,1.505495,NaN,0,127
5,cfd,6,77.8667,80058.789568,NaN,NaN,NaN,1.841739,NaN,0,127

========== CFD MASTER DATASET ==========

,workload,input_file,cpu_execution_time_ms,cpu_execution_median_ms,cpu_execution_std_ms,gpu_phase_time_ms,gpu_phase_median_ms,gpu_phase_std_ms,host_to_device_time_ms,device_to_host_time_ms,gpu_total_path_time_ms,gpu_kernel_iterations,preferred_device,cpu_failed_runs,gpu_failed_runs
0,cfd,fvcorr.domn.193K,77.623333,77.5373,0.239064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN,0,6

In [ ]:
import subprocess

GPU_DIR = "/kaggle/working/Rodinia/cuda/cfd"

result = subprocess.run(
    ["./euler3d", "../../data/cfd/fvcorr.domn.193K"],
    cwd=GPU_DIR,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print("Return code:", result.returncode)
print("\n========== CFD GPU OUTPUT ==========\n")
print(result.stdout)

Return code: 127

========== CFD GPU OUTPUT ==========

./euler3d: error while loading shared libraries: libcudart.so.4: cannot open shared object file: No such file or directory

In [ ]:
print(open("/kaggle/working/Rodinia/cuda/cfd/Makefile").read())

include ../../common/make.config

CUDA_SDK_PATH := $(SDK_DIR)

# Determine the correct version of the cutil library
CUTIL_LIB = # -lcutil
ifeq ($(shell uname -m), x86_64)
     ifeq ($(shell if test -e $(SDK_DIR)/lib/libcutil_x86_64.a; then echo T; else echo F; fi), T)
        CUTIL_LIB = #-lcutil_x86_64
     endif
endif


all: euler3d euler3d_double  pre_euler3d  pre_euler3d_double

euler3d: euler3d.cu
	nvcc $(KERNEL_DIM) -O2 -Xptxas -v --gpu-architecture=compute_20 --gpu-code=compute_20 euler3d.cu -o euler3d -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib $(CUTIL_LIB)

euler3d_double: euler3d_double.cu
	nvcc -Xptxas -v -O3 --gpu-architecture=compute_20 --gpu-code=compute_20 euler3d_double.cu -o euler3d_double -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib $(CUTIL_LIB)


pre_euler3d: pre_euler3d.cu
	nvcc -Xptxas -v -O3 --gpu-architecture=compute_20 --gpu-code=compute_20 pre_euler3d.cu -o pre_euler3d -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib $(CUTIL_LIB)

pre_euler3d_double: pre_euler3d_double.cu
	nvcc -Xptxas -v -O3 --gpu-architecture=compute_20 --gpu-code=compute_20 pre_euler3d_double.cu -o pre_euler3d_double -I$(CUDA_SDK_PATH)/common/inc  -L$(CUDA_SDK_PATH)/lib $(CUTIL_LIB)


clean:
	rm -f euler3d euler3d_double pre_euler3d pre_euler3d_double *.linkinfo

# ============================================================
# REBUILD RODINIA CFD CUDA FOR THE KAGGLE CUDA TOOLKIT
# ============================================================

import os
import subprocess

GPU_DIR = "/kaggle/working/Rodinia/cuda/cfd"

print("=" * 70)
print("CUDA ENVIRONMENT")
print("=" * 70)

print(subprocess.run(
    ["nvcc", "--version"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
).stdout)

print("=" * 70)
print("BACKING UP OLD CFD EXECUTABLE")
print("=" * 70)

# Keep the original executable in case we need it later
if os.path.exists(f"{GPU_DIR}/euler3d"):
    os.rename(
        f"{GPU_DIR}/euler3d",
        f"{GPU_DIR}/euler3d_old"
    )

# ------------------------------------------------------------
# Compile only the single-precision euler3d executable
# ------------------------------------------------------------
print("=" * 70)
print("COMPILING CFD GPU VERSION")
print("=" * 70)

cmd = [
    "nvcc",
    "-O2",
    "-Xptxas", "-v",
    "-arch=sm_75",
    "euler3d.cu",
    "-o", "euler3d"
]

result = subprocess.run(
    cmd,
    cwd=GPU_DIR,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print(result.stdout)

if result.returncode != 0:
    raise RuntimeError(
        "CFD CUDA compilation failed."
    )

print("\nCompilation successful.")

# ------------------------------------------------------------
# Verify executable
# ------------------------------------------------------------
exe = f"{GPU_DIR}/euler3d"

print("\nExecutable exists:", os.path.exists(exe))

# Check dynamic libraries
print("\n" + "=" * 70)
print("CHECKING LINKED CUDA LIBRARIES")
print("=" * 70)

ldd_result = subprocess.run(
    ["ldd", exe],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print(ldd_result.stdout)

# ------------------------------------------------------------
# Test execution
# ------------------------------------------------------------
print("=" * 70)
print("TESTING CFD GPU EXECUTION")
print("=" * 70)

test = subprocess.run(
    [
        "./euler3d",
        "../../data/cfd/fvcorr.domn.193K"
    ],
    cwd=GPU_DIR,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print("Return code:", test.returncode)
print("\n========== OUTPUT ==========\n")
print(test.stdout)

if test.returncode == 0:
    print("\nSUCCESS: CFD GPU executable runs.")
else:
    print("\nCFD GPU executable still failed.")

In [ ]:
import os
import subprocess

GPU_DIR = "/kaggle/working/Rodinia/cuda/cfd"

print("=" * 70)
print("CUDA VERSION")
print("=" * 70)

print(subprocess.run(
    ["nvcc", "--version"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
).stdout)

print("=" * 70)
print("CFD CUDA COMPILATION")
print("=" * 70)

cmd = [
    "nvcc",
    "-O2",
    "-Xptxas", "-v",
    "-arch=sm_75",
    "euler3d.cu",
    "-o", "euler3d"
]

result = subprocess.run(
    cmd,
    cwd=GPU_DIR,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print("Return code:", result.returncode)
print("\n========== FULL NVCC OUTPUT ==========\n")
print(result.stdout)

======================================================================
CUDA VERSION
======================================================================
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Fri_Feb_21_20:23:50_PST_2025
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0

======================================================================
CFD CUDA COMPILATION
======================================================================
Return code: 1

========== FULL NVCC OUTPUT ==========

euler3d.cu:5:10: fatal error: helper_cuda.h: No such file or directory
    5 | #include <helper_cuda.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

In [ ]:
import os

RODINIA_ROOT = "/kaggle/working/Rodinia"

matches = []

for root, dirs, files in os.walk(RODINIA_ROOT):
    if "helper_cuda.h" in files:
        matches.append(os.path.join(root, "helper_cuda.h"))

print("helper_cuda.h files found:")

if matches:
    for path in matches:
        print(path)
else:
    print("NONE FOUND")

helper_cuda.h files found:
/kaggle/working/Rodinia/cuda/hybridsort/helper_cuda.h

In [ ]:
import os
import subprocess

GPU_DIR = "/kaggle/working/Rodinia/cuda/cfd"
HELPER_DIR = "/kaggle/working/Rodinia/cuda/hybridsort"

# ------------------------------------------------------------
# Backup current CUDA source/executable if present
# ------------------------------------------------------------
if os.path.exists(f"{GPU_DIR}/euler3d"):
    os.rename(
        f"{GPU_DIR}/euler3d",
        f"{GPU_DIR}/euler3d_before_helper_fix"
    )

# ------------------------------------------------------------
# Compile CFD using the available helper_cuda.h
# and Tesla T4 architecture (sm_75)
# ------------------------------------------------------------
cmd = [
    "nvcc",
    "-O2",
    "-Xptxas", "-v",
    "-arch=sm_75",
    f"-I{HELPER_DIR}",
    "euler3d.cu",
    "-o", "euler3d"
]

print("=" * 70)
print("COMPILING CFD GPU VERSION")
print("=" * 70)

result = subprocess.run(
    cmd,
    cwd=GPU_DIR,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print("Return code:", result.returncode)
print("\n========== NVCC OUTPUT ==========\n")
print(result.stdout)

if result.returncode == 0:

    print("\nCompilation successful.")

    # --------------------------------------------------------
    # Test executable
    # --------------------------------------------------------
    print("\n" + "=" * 70)
    print("TESTING CFD GPU")
    print("=" * 70)

    test = subprocess.run(
        [
            "./euler3d",
            "../../data/cfd/fvcorr.domn.193K"
        ],
        cwd=GPU_DIR,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True
    )

    print("Return code:", test.returncode)
    print("\n========== CFD GPU OUTPUT ==========\n")
    print(test.stdout)

else:

    print("\nCompilation failed.")
    print("Do NOT change anything else yet.")

======================================================================
COMPILING CFD GPU VERSION
======================================================================
Return code: 0

========== NVCC OUTPUT ==========

ptxas info    : 0 bytes gmem, 68 bytes cmem[3]
ptxas info    : Compiling entry function '_Z14cuda_time_stepiiPfS_S_S_' for 'sm_75'
ptxas info    : Function properties for _Z14cuda_time_stepiiPfS_S_S_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 26 registers, used 0 barriers, 392 bytes cmem[0]
ptxas info    : Compile time = 24.596 ms
ptxas info    : Compiling entry function '_Z17cuda_compute_fluxiPiPfS0_S0_' for 'sm_75'
ptxas info    : Function properties for _Z17cuda_compute_fluxiPiPfS0_S0_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 58 registers, used 0 barriers, 392 bytes cmem[0]
ptxas info    : Compile time = 55.198 ms
ptxas info    : Compiling entry function '_Z24cuda_compute_step_factoriPfS_S_' for 'sm_75'
ptxas info    : Function properties for _Z24cuda_compute_step_factoriPfS_S_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 20 registers, used 0 barriers, 384 bytes cmem[0]
ptxas info    : Compile time = 12.167 ms
ptxas info    : Compiling entry function '_Z25cuda_initialize_variablesiPf' for 'sm_75'
ptxas info    : Function properties for _Z25cuda_initialize_variablesiPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 24 registers, used 0 barriers, 368 bytes cmem[0]
ptxas info    : Compile time = 1.229 ms
euler3d.cu: In function ‘int main(int, char**)’:
euler3d.cu:555:29: warning: ‘cudaError_t cudaThreadSynchronize()’ is deprecated [-Wdeprecated-declarations]
  555 |         cudaThreadSynchronize();
      |         ~~~~~~~~~~~~~~~~~~~~^~
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime_api.h:1172:46: note: declared here
 1172 | extern __CUDA_DEPRECATED __host__ cudaError_t CUDARTAPI cudaThreadSynchronize(void);
      |                                              ^~~~~~~~~~~~~~~~~~~~~
euler3d.cu:585:29: warning: ‘cudaError_t cudaThreadSynchronize()’ is deprecated [-Wdeprecated-declarations]
  585 |         cudaThreadSynchronize();
      |         ~~~~~~~~~~~~~~~~~~~~^~
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime_api.h:1172:46: note: declared here
 1172 | extern __CUDA_DEPRECATED __host__ cudaError_t CUDARTAPI cudaThreadSynchronize(void);
      |                                              ^~~~~~~~~~~~~~~~~~~~~


Compilation successful.

======================================================================
TESTING CFD GPU
======================================================================
Return code: 0

========== CFD GPU OUTPUT ==========

WG size of kernel:initialize = 192, WG size of kernel:compute_step_factor = 192, WG size of kernel:compute_flux = 192, WG size of kernel:time_step = 192
Name:                     Tesla T4
Starting...
0.000578458 seconds per iteration
Saving solution...
Saved solution...
Cleaning up...
Done...

In [ ]:
import subprocess

GPU_DIR = "/kaggle/working/Rodinia/cuda/cfd"

result = subprocess.run(
    [
        "./euler3d",
        "../../data/cfd/fvcorr.domn.193K"
    ],
    cwd=GPU_DIR,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print("Return code:", result.returncode)
print("\n========== CFD GPU OUTPUT ==========\n")
print(result.stdout)

Return code: 0

========== CFD GPU OUTPUT ==========

WG size of kernel:initialize = 192, WG size of kernel:compute_step_factor = 192, WG size of kernel:compute_flux = 192, WG size of kernel:time_step = 192
Name:                     Tesla T4
Starting...
0.000571731 seconds per iteration
Saving solution...
Saved solution...
Cleaning up...
Done...

In [ ]:
import subprocess
import re
import numpy as np
import pandas as pd

GPU_DIR = "/kaggle/working/Rodinia/cuda/cfd"
DATA_FILE = "../../data/cfd/fvcorr.domn.193K"

N_RUNS = 6
results = []

print("=" * 70)
print("CFD GPU — 6 RUNS")
print("=" * 70)

for run in range(1, N_RUNS + 1):

    result = subprocess.run(
        ["./euler3d", DATA_FILE],
        cwd=GPU_DIR,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True
    )

    output = result.stdout

    # CFD prints:
    # 0.00054809 seconds per iteration
    match = re.search(
        r"([0-9]+(?:\.[0-9]+)?)\s+seconds\s+per\s+iteration",
        output,
        re.IGNORECASE
    )

    gpu_time_ms = np.nan

    if match:
        seconds_per_iteration = float(match.group(1))
        gpu_time_ms = seconds_per_iteration * 1000.0

    results.append({
        "workload": "cfd",
        "run_number": run,
        "gpu_execution_time_ms": gpu_time_ms,
        "return_code": result.returncode
    })

    print(
        f"Run {run}: "
        f"{gpu_time_ms:.6f} ms per iteration "
        f"| return code = {result.returncode}"
    )

gpu_df = pd.DataFrame(results)

print("\n" + "=" * 70)
print("CFD GPU RESULTS")
print("=" * 70)

display(gpu_df)

print("\n" + "=" * 70)
print("SUMMARY")
print("=" * 70)

print(
    f"Mean   : {gpu_df['gpu_execution_time_ms'].mean():.6f} ms"
)

print(
    f"Median : {gpu_df['gpu_execution_time_ms'].median():.6f} ms"
)

print(
    f"Std    : {gpu_df['gpu_execution_time_ms'].std():.6f} ms"
)

======================================================================
CFD GPU — 6 RUNS
======================================================================
Run 1: 0.556622 ms per iteration | return code = 0
Run 2: 0.562261 ms per iteration | return code = 0
Run 3: 0.564197 ms per iteration | return code = 0
Run 4: 0.559237 ms per iteration | return code = 0
Run 5: 0.562786 ms per iteration | return code = 0
Run 6: 0.565982 ms per iteration | return code = 0

======================================================================
CFD GPU RESULTS
======================================================================

  workload  run_number  gpu_execution_time_ms  return_code
0      cfd           1               0.556622            0
1      cfd           2               0.562261            0
2      cfd           3               0.564197            0
3      cfd           4               0.559237            0
4      cfd           5               0.562786            0
5      cfd           6               0.565982            0

======================================================================
SUMMARY
======================================================================
Mean   : 0.561847 ms
Median : 0.562523 ms
Std    : 0.003400 ms

In [ ]:
import subprocess
import re
import numpy as np
import pandas as pd

# ---------------------------------------------------------
# 1. Location of CFD CUDA program and input data
# ---------------------------------------------------------

GPU_DIR = "/kaggle/working/Rodinia/cuda/cfd"
DATA_FILE = "../../data/cfd/fvcorr.domn.193K"

# We want 6 repeated measurements
N_RUNS = 6

results = []

print("=" * 70)
print("CFD GPU — 6 RUNS")
print("=" * 70)

# ---------------------------------------------------------
# 2. Run CFD six times
# ---------------------------------------------------------

for run in range(1, N_RUNS + 1):

    result = subprocess.run(
        ["./euler3d", DATA_FILE],
        cwd=GPU_DIR,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True
    )

    output = result.stdout

    # CFD prints a line like:
    #
    # 0.00054809 seconds per iteration
    #
    # We extract the number before
    # "seconds per iteration".

    match = re.search(
        r"([0-9]+(?:\.[0-9]+)?)\s+seconds\s+per\s+iteration",
        output,
        re.IGNORECASE
    )

    gpu_time_ms = np.nan

    if match:
        seconds_per_iteration = float(match.group(1))

        # Convert seconds to milliseconds
        gpu_time_ms = seconds_per_iteration * 1000.0

    # Store this run
    results.append({
        "workload": "cfd",
        "run_number": run,
        "gpu_execution_time_ms": gpu_time_ms,
        "return_code": result.returncode
    })

    print(
        f"Run {run}: "
        f"{gpu_time_ms:.6f} ms per iteration "
        f"| return code = {result.returncode}"
    )


# ---------------------------------------------------------
# 3. Create a table containing all 6 runs
# ---------------------------------------------------------

gpu_df = pd.DataFrame(results)

print("\n" + "=" * 70)
print("CFD GPU RESULTS")
print("=" * 70)

display(gpu_df)


# ---------------------------------------------------------
# 4. Calculate statistics
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("SUMMARY")
print("=" * 70)

print(
    f"Mean   : "
    f"{gpu_df['gpu_execution_time_ms'].mean():.6f} ms"
)

print(
    f"Median : "
    f"{gpu_df['gpu_execution_time_ms'].median():.6f} ms"
)

print(
    f"Std    : "
    f"{gpu_df['gpu_execution_time_ms'].std():.6f} ms"
)

======================================================================
CFD GPU — 6 RUNS
======================================================================
Run 1: 0.566927 ms per iteration | return code = 0
Run 2: 0.560800 ms per iteration | return code = 0
Run 3: 0.564223 ms per iteration | return code = 0
Run 4: 0.560205 ms per iteration | return code = 0
Run 5: 0.563826 ms per iteration | return code = 0
Run 6: 0.564576 ms per iteration | return code = 0

======================================================================
CFD GPU RESULTS
======================================================================

  workload  run_number  gpu_execution_time_ms  return_code
0      cfd           1               0.566927            0
1      cfd           2               0.560800            0
2      cfd           3               0.564223            0
3      cfd           4               0.560205            0
4      cfd           5               0.563826            0
5      cfd           6               0.564576            0

======================================================================
SUMMARY
======================================================================
Mean   : 0.563426 ms
Median : 0.564025 ms
Std    : 0.002516 ms